MUTANT_FAST_GRAV_MULT = 3 

MutantScout_x = {

	NoFallDamage = 1,
	MeleeHitType="melee_slash",
	bNoImpulseOnDamage = 1,
	MUTANT = "fast",	

	PropertiesInstance = {	
			sightrange = 110,
			soundrange = 10,
			aibehavior_behaviour = "MutantJob_Idling",
			groupid = 100,
			fileHelmetModel = "",
			bHelmetOnStart = 0,
			specialInfo= "",
			attackrange = 300,
			accuracy = .7,
			aggression = 0,
			bHasLight = 0,
		},


	Properties = {
			aicharacter_character = "Fast",
			equipEquipment = "AG36",
			equipDropPack = "AG36_pickup",
			bAwareOfPlayerTargeting = 1,
			fMeleeDamage = 100,
			fMeleeDistance = 1.5,
			-- fDamageMultiplier = .5,
			fJumpAngle = 45,
			gravity_multiplier = MUTANT_FAST_GRAV_MULT,
			bSingleMeleeKillAI = 0,
			JUMP_TABLE = "MUTANT_FAST",
			KEYFRAME_TABLE = "MUTANT_FAST",
			SOUND_TABLE = "MUTANT_FAST",
			fRushPercentage=-1,
			bSmartMelee = 1,
			bInvulnerable = 0,
			suppressedThrhld = 5.5,
			bAffectSOM = 1,
			bSleepOnSpawn = 1,
			bHasArmor = 1,
			horizontal_fov = 160,
			eye_height = 2.1,
			forward_speed = 3.24,
			back_speed = 3.24,
			responsiveness = 7.5,
			fSpeciesHostility = 2,
			fGroupHostility = 0,
			fPersistence = 0,
			AnimPack = "Basic",
			SoundPack = "mutant_readability",
			fileModel = "Objects/characters/mutants/mutant_fast/mutant_fast.cgf",
			max_health = 255,
			pathname = "none",
			pathsteps = 0,
			pathstart = 0,
			ReinforcePoint = "none",
			bPushPlayers = 1,
			bPushedByPlayers = 1,
			commrange = 30,
			species = 100,
			special = 0,
			bTrackable = 1,

		speed_scales={
			run			=1.67,
			crouch		=.8,
			prone		=.5,
			xrun		=1.5,
			xwalk		=.81,
			rrun		=1.67,
			rwalk		=.38,
			},
		AniRefSpeeds = {
			WalkFwd = 3.24,
			WalkSide = 3.24,
			WalkBack = 3.24,
			WalkRelaxedFwd = 1.25,
			WalkRelaxedSide = 1.25,
			WalkRelaxedBack = 1.25,
			XWalkFwd = 3.24,
			XWalkSide = 3.24,
			XWalkBack = 3.24,
			XRunFwd = 4.5,
			XRunSide = 3.5,
			XRunBack = 4.5,
			RunFwd = 5.4,
			RunSide = 5.4,
			RunBack = 5.4,
			CrouchFwd = 3.24,
			CrouchSide = 3.24,
			CrouchBack = 3.24,
		},
	},

	PhysParams = {
		mass = 80,
		height = 2.8,
		eyeheight = 2.7,
		sphereheight = 1.2,
		radius = 3.45,
	},

--pe_player_dimensions structure
	PlayerDimNormal = {
		height = 2.2,
		eye_height = 2.1,
		ellipsoid_height = 1.3,
		x = .5,
		y = 0,
		z = .6,
	},
	PlayerDimCrouch = {
		height = 2.2,
		eye_height = 2.1,
		ellipsoid_height = 1.3,
		x = .5,
		y = .8,
		z = .3,
	},
	PlayerDimProne = {
		height = .4,
		eye_height = .5,
		ellipsoid_height = .35,
		x = .5,
		y = .45,
		z = .2,
	},


	AI_DynProp = {
		air_control = .4, -- default .6
		gravity = MUTANT_FAST_GRAV_MULT*9.81,
		swimming_gravity = -.5,
		inertia = 10,
		swimming_inertia = .5,
		nod_speed = 60,
		min_slide_angle = 46,
		max_climb_angle = 60,
		min_fall_angle = 70,
		max_jump_angle = 55,
	},
	


	DeadBodyParams = {
	  sim_type = 1,
	  max_time_step = .025,
	  gravityz = -7.5,
	  sleep_speed = .025,
	  damping = .3,
	  freefall_gravityz = -9.81,
	  freefall_damping = .1,

	  lying_mode_ncolls = 4,
	  lying_gravityz = -5,
	  lying_sleep_speed = .065,
	  lying_damping = 1,
	},
	BulletImpactParams = {
    stiffness_scale = 73,
    max_time_step = .02
	},

	Ammo = {
		Pistol = 0,
		Assault = 0,
		Sniper = 0,
		Minigun = 0,
		Shotgun = 0,
		MortarShells = 0,
		Grenades = 0,
		HandGrenades = 0,
		Rocket = 0,
		Battery = 0,
	},

	GrenadeType = "ProjFlashbangGrenade",
}