SoundPresetDB = {
	m5nighttimesounds1 = {
		SOUNDS_M5components_wierd3_wav = {
			Sound = "SOUNDS/M5components/wierd3.wav",
			Centered = "0",
			Chance = "100",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		SOUNDS_M5components_wierd1_wav = {
			Sound = "SOUNDS/M5components/wierd1.wav",
			Centered = "0",
			Chance = "120",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		SOUNDS_M5components_wierd2_wav = {
			Sound = "SOUNDS/M5components/wierd2.wav",
			Centered = "0",
			Chance = "90",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
	},
	silenceID3 = {
	},
	rebellionexplosion = {
		Sounds_explosions_rebexp2_wav = {
			Sound = "Sounds/explosions/rebexp2.wav",
			Centered = "0",
			Chance = "65",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		Sounds_explosions_rebexp1_wav = {
			Sound = "Sounds/explosions/rebexp1.wav",
			Centered = "0",
			Chance = "0",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "150",
		},
		Sounds_explosions_rebexp4_wav = {
			Sound = "Sounds/explosions/rebexp4.wav",
			Centered = "0",
			Chance = "67",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		Sounds_explosions_rebexp5_wav = {
			Sound = "Sounds/explosions/rebexp5.wav",
			Centered = "0",
			Chance = "70",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		Sounds_explosions_rebexp3_wav = {
			Sound = "Sounds/explosions/rebexp3.wav",
			Centered = "0",
			Chance = "0",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
	},
	volcanebridgegroans = {
		Sounds_creaks_groan1_wav = {
			Sound = "Sounds/creaks/groan1.wav",
			Centered = "0",
			Chance = "75",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "100",
		},
		Sounds_creaks_groan4_wav = {
			Sound = "Sounds/creaks/groan4.wav",
			Centered = "0",
			Chance = "85",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "100",
		},
		Sounds_creaks_groan3_wav = {
			Sound = "Sounds/creaks/groan3.wav",
			Centered = "0",
			Chance = "95",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "100",
		},
		Sounds_creaks_groan2_wav = {
			Sound = "Sounds/creaks/groan2.wav",
			Centered = "0",
			Chance = "100",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "100",
		},
		Sounds_creaks_groan5_wav = {
			Sound = "Sounds/creaks/groan5.wav",
			Centered = "0",
			Chance = "105",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "100",
		},
	},
	pierannouncers = {
		LANGUAGES_English_missiontalk_pier_announce1_wav = {
			Sound = "languages/missiontalk/pier/announce1.wav",
			Centered = "1",
			Chance = "85",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "60",
			Volume = "255",
		},
		LANGUAGES_English_missiontalk_pier_announce8_wav = {
			Sound = "languages/missiontalk/pier/announce8.wav",
			Centered = "1",
			Chance = "92",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "60",
			Volume = "255",
		},
		LANGUAGES_English_missiontalk_pier_announce4_wav = {
			Sound = "languages/missiontalk/pier/announce4.wav",
			Centered = "1",
			Chance = "89",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "60",
			Volume = "255",
		},
		LANGUAGES_English_missiontalk_pier_announce5_wav = {
			Sound = "languages/missiontalk/pier/announce5.wav",
			Centered = "1",
			Chance = "90",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "60",
			Volume = "255",
		},
		LANGUAGES_English_missiontalk_pier_announce2_wav = {
			Sound = "languages/missiontalk/pier/announce2.wav",
			Centered = "1",
			Chance = "86",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "60",
			Volume = "255",
		},
		LANGUAGES_English_missiontalk_pier_announce7_wav = {
			Sound = "languages/missiontalk/pier/announce7.wav",
			Centered = "1",
			Chance = "91",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "60",
			Volume = "255",
		},
		LANGUAGES_English_missiontalk_pier_announce3_wav = {
			Sound = "languages/missiontalk/pier/announce3.wav",
			Centered = "1",
			Chance = "88",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "60",
			Volume = "255",
		},
		LANGUAGES_English_missiontalk_pier_announce6_wav = {
			Sound = "languages/missiontalk/pier/announce6.wav",
			Centered = "1",
			Chance = "91",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "60",
			Volume = "255",
		},
	},
	silenceID1 = {
		SOUNDS_building_cryoroomlp1_wav = {
			Sound = "SOUNDS/building/cryoroomlp1.wav",
			Centered = "1",
			Chance = "0",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "0",
		},
	},
	thunderSEX = {
		SOUNDS_thunder_trumble3_wav = {
			Sound = "SOUNDS/thunder/trumble3.wav",
			Centered = "0",
			Chance = "425",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
		SOUNDS_thunder_trumble2_wav = {
			Sound = "SOUNDS/thunder/trumble2.wav",
			Centered = "0",
			Chance = "481",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
		SOUNDS_thunder_trumble4_wav = {
			Sound = "SOUNDS/thunder/trumble4.wav",
			Centered = "0",
			Chance = "359",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
		SOUNDS_thunder_trumble1_wav = {
			Sound = "SOUNDS/thunder/trumble1.wav",
			Centered = "0",
			Chance = "500",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
	},
	monkeys = {
		SOUNDS_animals_monkey1_wav = {
			Sound = "SOUNDS/animals/monkey1.wav",
			Centered = "0",
			Chance = "75",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "28",
		},
		SOUNDS_animals_monkey2_wav = {
			Sound = "SOUNDS/animals/monkey2.wav",
			Centered = "0",
			Chance = "70",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "28",
		},
	},
	islandaminalsPST = {
		SOUNDS_newcrickets_swamp244k_wav = {
			Sound = "SOUNDS/newcrickets/swamp244k.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "10",
		},
		SOUNDS_birds_jbird5_wav = {
			Sound = "SOUNDS/birds/jbird5.wav",
			Centered = "0",
			Chance = "85",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "20",
			Volume = "200",
		},
		SOUNDS_Ambient_E3_weird_j_sound_wav = {
			Sound = "SOUNDS/Ambient/E3/weird_j_sound.wav",
			Centered = "0",
			Chance = "92",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "20",
			Volume = "150",
		},
		SOUNDS_birds_jbird8_wav = {
			Sound = "SOUNDS/birds/jbird8.wav",
			Centered = "0",
			Chance = "102",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "20",
			Volume = "150",
		},
		SOUNDS_Ambient_crickets_cr_night5_wav = {
			Sound = "SOUNDS/Ambient/crickets/cr_night5.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "50",
		},
		SOUNDS_Ambient_crickets_triplecrick_wav = {
			Sound = "SOUNDS/Ambient/crickets/triplecrick.wav",
			Centered = "0",
			Chance = "90",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "20",
			Volume = "100",
		},
		SOUNDS_birds_jbird1_wav = {
			Sound = "SOUNDS/birds/jbird1.wav",
			Centered = "0",
			Chance = "75",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "20",
			Volume = "200",
		},
		SOUNDS_Ambient_E3_parrot1_wav = {
			Sound = "SOUNDS/Ambient/E3/parrot1.wav",
			Centered = "0",
			Chance = "160",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "20",
			Volume = "150",
		},
	},
	grasscrickandshakers = {
		SOUNDS_missionbirds_shakerbug_wav = {
			Sound = "SOUNDS/missionbirds/shakerbug.wav",
			Centered = "1",
			Chance = "105",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "28",
			Volume = "10",
		},
		SOUNDS_Ambient_crickets_triplecrick_wav = {
			Sound = "SOUNDS/Ambient/crickets/triplecrick.wav",
			Centered = "0",
			Chance = "102",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "150",
		},
		SOUNDS_Ambient_crickets_quadcrick_wav = {
			Sound = "SOUNDS/Ambient/crickets/quadcrick.wav",
			Centered = "0",
			Chance = "130",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "35",
			Volume = "150",
		},
		SOUNDS_Ambient_crickets_cr_chirping1_wav = {
			Sound = "SOUNDS/Ambient/crickets/cr_chirping1.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "15",
		},
		SOUNDS_missionbirds_shakerbug2_wav = {
			Sound = "SOUNDS/missionbirds/shakerbug2.wav",
			Centered = "0",
			Chance = "96",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "10",
		},
		SOUNDS_Ambient_crickets_singlecrick_wav = {
			Sound = "SOUNDS/Ambient/crickets/singlecrick.wav",
			Centered = "0",
			Chance = "120",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "150",
		},
	},
	m3playerfallingwind = {
		SOUNDS_Ambient_E3_whistlewindLP2_wav = {
			Sound = "SOUNDS/Ambient/E3/whistlewindLP2.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
	},
	seagulls = {
		SOUNDS_Ambient_E3_gull1_wav = {
			Sound = "SOUNDS/Ambient/E3/gull1.wav",
			Centered = "0",
			Chance = "150",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
		SOUNDS_Ambient_E3_gull2_wav = {
			Sound = "SOUNDS/Ambient/E3/gull2.wav",
			Centered = "0",
			Chance = "140",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
	},
	M8junglenight = {
		SOUNDS_jungle_M08jungleambientLP_ogg = {
			Sound = "SOUNDS/jungle/M08jungleambientLP.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "1",
			Timeout = "0",
			Volume = "100",
		},
	},
	Misceets = {
		SOUNDS_Ambient_bugs_misceets_wav = {
			Sound = "SOUNDS/Ambient/bugs/misceets.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "25",
		},
	},
	undergroundPST = {
		SOUNDS_building_undergroundtone_wav = {
			Sound = "SOUNDS/building/undergroundtone.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "150",
		},
	},
	swampjungleambience = {
		SOUNDS_jungle_jungleswamp_wav = {
			Sound = "SOUNDS/jungle/jungleswamp.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "50",
		},
	},
	treerain = {
		SOUNDS_rain_rainleaves1_wav = {
			Sound = "SOUNDS/rain/rainleaves1.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "35",
		},
	},
	shipdrips = {
		SOUNDS_building_drip4_wav = {
			Sound = "SOUNDS/building/drip4.wav",
			Centered = "0",
			Chance = "105",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
		SOUNDS_building_drip11_wav = {
			Sound = "SOUNDS/building/drip11.wav",
			Centered = "0",
			Chance = "109",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
		SOUNDS_building_drip2_wav = {
			Sound = "SOUNDS/building/drip2.wav",
			Centered = "0",
			Chance = "100",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
		SOUNDS_building_drip6_wav = {
			Sound = "SOUNDS/building/drip6.wav",
			Centered = "0",
			Chance = "99",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
		SOUNDS_building_drip1_wav = {
			Sound = "SOUNDS/building/drip1.wav",
			Centered = "0",
			Chance = "97",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
		SOUNDS_building_drip5_wav = {
			Sound = "SOUNDS/building/drip5.wav",
			Centered = "0",
			Chance = "93",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
		SOUNDS_building_drip8_wav = {
			Sound = "SOUNDS/building/drip8.wav",
			Centered = "0",
			Chance = "90",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
		SOUNDS_building_drip10_wav = {
			Sound = "SOUNDS/building/drip10.wav",
			Centered = "0",
			Chance = "89",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
		SOUNDS_building_drip3_wav = {
			Sound = "SOUNDS/building/drip3.wav",
			Centered = "0",
			Chance = "87",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
		SOUNDS_building_drip9_wav = {
			Sound = "SOUNDS/building/drip9.wav",
			Centered = "0",
			Chance = "85",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
		SOUNDS_building_drip7_wav = {
			Sound = "SOUNDS/building/drip7.wav",
			Centered = "0",
			Chance = "83",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
	},
	swamp1 = {
		SOUNDS_Ambient_E3_frog2_wav = {
			Sound = "SOUNDS/Ambient/E3/frog2.wav",
			Centered = "0",
			Chance = "66",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "40",
		},
		SOUNDS_Ambient_bugs_misceets_wav = {
			Sound = "SOUNDS/Ambient/bugs/misceets.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "7",
		},
		SOUNDS_Ambient_E3_frog3_wav = {
			Sound = "SOUNDS/Ambient/E3/frog3.wav",
			Centered = "0",
			Chance = "60",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "40",
		},
		SOUNDS_Ambient_E3_frog4_wav = {
			Sound = "SOUNDS/Ambient/E3/frog4.wav",
			Centered = "0",
			Chance = "70",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "40",
		},
	},
	treecricket1 = {
		SOUNDS_newcrickets_crick1444k_wav = {
			Sound = "SOUNDS/newcrickets/crick1444k.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "7",
		},
	},
	areatest = {
		SOUNDS_testaudio_sine0db_wav = {
			Sound = "SOUNDS/testaudio/sine0db.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "1",
			Timeout = "0",
			Volume = "25",
		},
	},
	m3happybirds2 = {
		SOUNDS_missionbirds_warbler6_wav = {
			Sound = "SOUNDS/missionbirds/warbler62.wav",
			Centered = "0",
			Chance = "75",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "40",
			Volume = "255",
		},
		SOUNDS_missionbirds_robin1_wav = {
			Sound = "SOUNDS/missionbirds/robin12.wav",
			Centered = "0",
			Chance = "115",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "40",
			Volume = "255",
		},
		SOUNDS_missionbirds_skylark2_wav = {
			Sound = "SOUNDS/missionbirds/skylark22.wav",
			Centered = "0",
			Chance = "83",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "40",
			Volume = "255",
		},
		SOUNDS_missionbirds_skylark3_wav = {
			Sound = "SOUNDS/missionbirds/skylark32.wav",
			Centered = "0",
			Chance = "72",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "40",
			Volume = "255",
		},
		SOUNDS_missionbirds_warbler2_wav = {
			Sound = "SOUNDS/missionbirds/warbler22.wav",
			Centered = "0",
			Chance = "63",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "40",
			Volume = "255",
		},
		SOUNDS_missionbirds_nightigale5_wav = {
			Sound = "SOUNDS/missionbirds/nightigale52.wav",
			Centered = "0",
			Chance = "130",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "40",
			Volume = "255",
		},
		SOUNDS_missionbirds_warbler1_wav = {
			Sound = "SOUNDS/missionbirds/warbler12.wav",
			Centered = "0",
			Chance = "80",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "40",
			Volume = "255",
		},
		SOUNDS_missionbirds_skylark1_wav = {
			Sound = "SOUNDS/missionbirds/skylark12.wav",
			Centered = "0",
			Chance = "93",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "40",
			Volume = "255",
		},
		SOUNDS_missionbirds_nightigale4_wav = {
			Sound = "SOUNDS/missionbirds/nightigale42.wav",
			Centered = "0",
			Chance = "100",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "40",
			Volume = "255",
		},
		SOUNDS_missionbirds_pileated2_wav = {
			Sound = "SOUNDS/missionbirds/pileated22.wav",
			Centered = "0",
			Chance = "105",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "40",
			Volume = "255",
		},
	},
	grasscricketpreset = {
		SOUNDS_Ambient_crickets_cr_field1_wav = {
			Sound = "SOUNDS/Ambient/crickets/cr_field1.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "30",
		},
	},
	m03bugs2 = {
		SOUNDS_jungle_cool_insects2lp_ogg = {
			Sound = "SOUNDS/jungle/cool_insects2lp.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "1",
			Timeout = "0",
			Volume = "50",
		},
	},
	m05windPST = {
		SOUNDS_wind44KADPCM_wind244k_wav = {
			Sound = "SOUNDS/wind44KADPCM/wind244k.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "2",
		},
	},
	compoundresohumm = {
		SOUNDS_building_resonentlp_wav = {
			Sound = "SOUNDS/building/resonentlp.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "50",
		},
	},
	m3streamingwind2 = {
		SOUNDS_jungle_m3wind_ogg = {
			Sound = "SOUNDS/jungle/m3wind.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "1",
			Timeout = "0",
			Volume = "65",
		},
	},
	birds = {
		SOUNDS_birds_parret1_wav = {
			Sound = "SOUNDS/birds/parret1.wav",
			Centered = "0",
			Chance = "79",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "10",
			Volume = "75",
		},
		SOUNDS_birds_WINGFLAP1_wav = {
			Sound = "SOUNDS/birds/WINGFLAP1.wav",
			Centered = "0",
			Chance = "81",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "10",
			Volume = "65",
		},
		SOUNDS_birds_larkchirp2_wav = {
			Sound = "SOUNDS/birds/larkchirp2.wav",
			Centered = "0",
			Chance = "110",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "10",
			Volume = "100",
		},
		SOUNDS_birds_WING_FLAP2_wav = {
			Sound = "SOUNDS/birds/WING FLAP2.wav",
			Centered = "0",
			Chance = "71",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "10",
			Volume = "65",
		},
		SOUNDS_birds_larkchirp1_wav = {
			Sound = "SOUNDS/birds/larkchirp1.wav",
			Centered = "0",
			Chance = "80",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "10",
			Volume = "100",
		},
		SOUNDS_birds_flicker1_wav = {
			Sound = "SOUNDS/birds/flicker1.wav",
			Centered = "0",
			Chance = "85",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "10",
			Volume = "65",
		},
		SOUNDS_birds_flickersingle1_wav = {
			Sound = "SOUNDS/birds/flickersingle1.wav",
			Centered = "0",
			Chance = "90",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "10",
			Volume = "100",
		},
		SOUNDS_birds_WING_FLAP3_wav = {
			Sound = "SOUNDS/birds/WING FLAP3.wav",
			Centered = "0",
			Chance = "76",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "10",
			Volume = "65",
		},
		SOUNDS_birds_parret2_wav = {
			Sound = "SOUNDS/birds/parret2.wav",
			Centered = "0",
			Chance = "65",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "10",
			Volume = "75",
		},
	},
	clearingwind = {
		SOUNDS_Ambient_E3_steadywind_wav = {
			Sound = "SOUNDS/Ambient/E3/steadywind.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "11",
		},
		SOUNDS_Ambient_E3_storm_gust_3_wav = {
			Sound = "SOUNDS/Ambient/E3/storm_gust_3.wav",
			Centered = "0",
			Chance = "140",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "100",
		},
		SOUNDS_Ambient_E3_storm_gust_2_wav = {
			Sound = "SOUNDS/Ambient/E3/storm_gust_2.wav",
			Centered = "0",
			Chance = "130",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "100",
		},
		SOUNDS_Ambient_E3_storm_gust_1_wav = {
			Sound = "SOUNDS/Ambient/E3/storm_gust_1.wav",
			Centered = "0",
			Chance = "155",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "100",
		},
	},
	m3streamingwind = {
		SOUNDS_jungle_desertwind_ogg = {
			Sound = "SOUNDS/jungle/desertwind.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "1",
			Timeout = "0",
			Volume = "65",
		},
	},
	coolinsects1 = {
		SOUNDS_jungle_cool_insects1lp_ogg = {
			Sound = "SOUNDS/jungle/cool_insects1lp.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "1",
			Timeout = "0",
			Volume = "200",
		},
	},
	shorewind = {
		SOUNDS_Ambient_E3_whistlinggust_1_wav = {
			Sound = "SOUNDS/Ambient/E3/whistlinggust 1.wav",
			Centered = "0",
			Chance = "130",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "140",
		},
		SOUNDS_Ambient_E3_whistlinggust3_wav = {
			Sound = "SOUNDS/Ambient/E3/whistlinggust3.wav",
			Centered = "0",
			Chance = "140",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "140",
		},
		SOUNDS_Ambient_E3_whistlinggust2_wav = {
			Sound = "SOUNDS/Ambient/E3/whistlinggust2.wav",
			Centered = "0",
			Chance = "155",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "140",
		},
		SOUNDS_Ambient_E3_steadywind_wav = {
			Sound = "SOUNDS/Ambient/E3/steadywind.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "32",
		},
	},
	m3playersplash = {
		SOUNDS_player_water_WaterSplash_wav = {
			Sound = "SOUNDS/player/water/WaterSplash.wav",
			Centered = "1",
			Chance = "999",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "1000",
			Volume = "255",
		},
	},
	archivewater = {
		Sounds_items_archive_water_wav = {
			Sound = "Sounds/items/archive_water.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "100",
		},
	},
	bunkerwindowshoreline = {
		SOUNDS_M3_waterlap5_wav = {
			Sound = "SOUNDS/M3/waterlap52.wav",
			Centered = "0",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "100",
		},
	},
	M10islandwindSEX = {
		SOUNDS_wind44KADPCM_wind144k_wav = {
			Sound = "SOUNDS/wind44KADPCM/wind144k.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "5",
		},
	},
	silenceID2 = {
	},
	bunkerwallholes = {
		SOUNDS_jungle__cool_insects1lpmono2_wav = {
			Sound = "SOUNDS/jungle//cool_insects1lpmono2.wav",
			Centered = "0",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
	},
	sparks = {
		SOUNDS_explosions_spark2_wav = {
			Sound = "SOUNDS/explosions/spark2.wav",
			Centered = "0",
			Chance = "400",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "5",
			Volume = "100",
		},
		SOUNDS_explosions_spark4_wav = {
			Sound = "SOUNDS/explosions/spark4.wav",
			Centered = "0",
			Chance = "450",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "100",
		},
		SOUNDS_explosions_spark3_wav = {
			Sound = "SOUNDS/explosions/spark3.wav",
			Centered = "0",
			Chance = "300",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "100",
		},
		SOUNDS_explosions_spark1_wav = {
			Sound = "SOUNDS/explosions/spark1.wav",
			Centered = "0",
			Chance = "350",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "100",
		},
	},
	beachwindPST = {
		SOUNDS_Ambient_E3_gust_3_wav = {
			Sound = "SOUNDS/Ambient/E3/gust_3.wav",
			Centered = "0",
			Chance = "135",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "75",
		},
		SOUNDS_wind44KADPCM_calmbeachwind44k_wav = {
			Sound = "SOUNDS/wind44KADPCM/calmbeachwind44k.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "9",
		},
		SOUNDS_Ambient_E3_gust_1_wav = {
			Sound = "SOUNDS/Ambient/E3/gust_1.wav",
			Centered = "0",
			Chance = "115",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "75",
		},
		SOUNDS_Ambient_E3_gust_2_wav = {
			Sound = "SOUNDS/Ambient/E3/gust_2.wav",
			Centered = "0",
			Chance = "125",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "75",
		},
	},
	shorelinedroneLP = {
		SOUNDS_Ambient_E3_shoredroneloop_wav = {
			Sound = "SOUNDS/Ambient/E3/shoredroneloop.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "100",
		},
	},
	bunkerwindowwind = {
		Sounds_jungle_m3wind_ogg = {
			Sound = "Sounds/jungle/m3wind.wav",
			Centered = "0",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "1",
			Timeout = "0",
			Volume = "255",
		},
	},
	buildingrumblenoclank = {
		SOUNDS_building_strain_wav = {
			Sound = "SOUNDS/building/strain.wav",
			Centered = "0",
			Chance = "65",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "90",
			Volume = "85",
		},
		SOUNDS_building_shudder1_wav = {
			Sound = "SOUNDS/building/shudder1.wav",
			Centered = "0",
			Chance = "115",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		SOUNDS_building_rumblelp_wav = {
			Sound = "SOUNDS/building/rumblelp.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "100",
		},
		SOUNDS_building_shudder2_wav = {
			Sound = "SOUNDS/building/shudder2.wav",
			Centered = "0",
			Chance = "105",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
	},
	islandnight = {
		SOUNDS_Ambient_crickets_nightcr3_wav = {
			Sound = "SOUNDS/Ambient/crickets/nightcr3.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "1",
		},
		SOUNDS_Ambient_crickets_doublecr_wav = {
			Sound = "SOUNDS/Ambient/crickets/doublecr.wav",
			Centered = "0",
			Chance = "80",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "65",
		},
		SOUNDS_Ambient_crickets_quadcrick_wav = {
			Sound = "SOUNDS/Ambient/crickets/quadcrick.wav",
			Centered = "0",
			Chance = "70",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "57",
		},
		SOUNDS_Ambient_E3_weird_j_sound_wav = {
			Sound = "SOUNDS/Ambient/E3/weird_j_sound.wav",
			Centered = "0",
			Chance = "55",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "55",
		},
		SOUNDS_Ambient_bugs_buzjungle4_wav = {
			Sound = "SOUNDS/Ambient/bugs/buzjungle4.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "50",
		},
		SOUNDS_Ambient_E3_parrot1_wav = {
			Sound = "SOUNDS/Ambient/E3/parrot1.wav",
			Centered = "0",
			Chance = "83",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "105",
		},
	},
	chasmwindboxes = {
		SOUNDS_wind44KADPCM_CHASMWIND144MK_wav = {
			Sound = "SOUNDS/wind44KADPCM/CHASMWIND144MK.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "7",
		},
	},
	gullywind = {
		SOUNDS_M3_stormwind2_LP_wav = {
			Sound = "SOUNDS/M3/stormwind2_LP.wav",
			Centered = "0",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
	},
	m3tunnelwind = {
		SOUNDS_M3_tunnelwind2LP_wav = {
			Sound = "SOUNDS/M3/tunnelwind2LP.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "200",
		},
	},
	m3happybirds = {
		SOUNDS_missionbirds_warbler6_wav = {
			Sound = "SOUNDS/missionbirds/warbler6.wav",
			Centered = "0",
			Chance = "75",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "40",
			Volume = "255",
		},
		SOUNDS_missionbirds_robin1_wav = {
			Sound = "SOUNDS/missionbirds/robin1.wav",
			Centered = "0",
			Chance = "115",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "40",
			Volume = "255",
		},
		SOUNDS_missionbirds_skylark2_wav = {
			Sound = "SOUNDS/missionbirds/skylark2.wav",
			Centered = "0",
			Chance = "83",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "40",
			Volume = "255",
		},
		SOUNDS_missionbirds_skylark3_wav = {
			Sound = "SOUNDS/missionbirds/skylark3.wav",
			Centered = "0",
			Chance = "72",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "40",
			Volume = "255",
		},
		SOUNDS_missionbirds_warbler2_wav = {
			Sound = "SOUNDS/missionbirds/warbler2.wav",
			Centered = "0",
			Chance = "63",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "40",
			Volume = "255",
		},
		SOUNDS_missionbirds_nightigale5_wav = {
			Sound = "SOUNDS/missionbirds/nightigale5.wav",
			Centered = "0",
			Chance = "130",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "40",
			Volume = "255",
		},
		SOUNDS_missionbirds_warbler1_wav = {
			Sound = "SOUNDS/missionbirds/warbler1.wav",
			Centered = "0",
			Chance = "80",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "40",
			Volume = "255",
		},
		SOUNDS_missionbirds_skylark1_wav = {
			Sound = "SOUNDS/missionbirds/skylark1.wav",
			Centered = "0",
			Chance = "93",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "40",
			Volume = "255",
		},
		SOUNDS_missionbirds_nightigale4_wav = {
			Sound = "SOUNDS/missionbirds/nightigale4.wav",
			Centered = "0",
			Chance = "100",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "40",
			Volume = "255",
		},
		SOUNDS_missionbirds_pileated2_wav = {
			Sound = "SOUNDS/missionbirds/pileated2.wav",
			Centered = "0",
			Chance = "105",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "40",
			Volume = "255",
		},
	},
	m5nightambient = {
		SOUNDS_jungle_junglenightfall1lp_ogg = {
			Sound = "SOUNDS/jungle/junglenightfall1lp.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "1",
			Timeout = "0",
			Volume = "25",
		},
	},
	roomtone1 = {
		SOUNDS_jungle_roomtone1_ogg = {
			Sound = "SOUNDS/jungle/roomtone1.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "1",
			Timeout = "0",
			Volume = "100",
		},
	},
	M4basic = {
		SOUNDS_newcrickets_crick522k_wav = {
			Sound = "SOUNDS/newcrickets/crick522k.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "4",
		},
	},
	m5basiccricket2 = {
	},
	m3deepheavyjunglebirds = {
		SOUNDS_M3_testbirds_shakerbug2_wav = {
			Sound = "SOUNDS/missionbirds/shakerbug2.wav",
			Centered = "0",
			Chance = "125",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "45",
			Volume = "255",
		},
		SOUNDS_M3_testbirds_warbler3_wav = {
			Sound = "SOUNDS/missionbirds/warbler3.wav",
			Centered = "0",
			Chance = "110",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "45",
			Volume = "255",
		},
		SOUNDS_M3_testbirds_belize1_wav = {
			Sound = "SOUNDS/missionbirds/belize1.wav",
			Centered = "0",
			Chance = "50",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "45",
			Volume = "50",
		},
		SOUNDS_M3_testbirds_warbler4_wav = {
			Sound = "SOUNDS/missionbirds/warbler4.wav",
			Centered = "0",
			Chance = "135",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "45",
			Volume = "255",
		},
		SOUNDS_M3_testbirds_pileated1_wav = {
			Sound = "SOUNDS/missionbirds/pileated1.wav",
			Centered = "0",
			Chance = "120",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "45",
			Volume = "255",
		},
		SOUNDS_M3_testbirds_belize2_wav = {
			Sound = "SOUNDS/missionbirds/belize2.wav",
			Centered = "0",
			Chance = "40",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "45",
			Volume = "50",
		},
		SOUNDS_M3_testbirds_coot_wav = {
			Sound = "SOUNDS/missionbirds/coot.wav",
			Centered = "0",
			Chance = "130",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "45",
			Volume = "255",
		},
		SOUNDS_M3_testbirds_shakerbug_wav = {
			Sound = "SOUNDS/missionbirds/shakerbug.wav",
			Centered = "0",
			Chance = "140",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "45",
			Volume = "255",
		},
	},
	treewind = {
		SOUNDS_jungle_treewind22_wav = {
			Sound = "SOUNDS/jungle/treewind22.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "100",
		},
	},
	inletwatersounds = {
		SOUNDS_Ambient_E3_brook2_wav = {
			Sound = "SOUNDS/Ambient/E3/brook2.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "65",
		},
	},
	silence = {
		SOUNDS_jungle_silence_wav = {
			Sound = "SOUNDS/jungle/silence.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
	},
	M10rainSEX = {
		SOUNDS_rain_rainbasiclight1_wav = {
			Sound = "SOUNDS/rain/rainbasiclight1.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "40",
		},
	},
	rainonmetal = {
		Sounds_rain__rainmetal1_wav = {
			Sound = "Sounds/rain//rainmetal1.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "150",
		},
	},
	winggusts1 = {
		SOUNDS_Ambient_E3_storm_gust_2_wav = {
			Sound = "SOUNDS/Ambient/E3/storm_gust_2.wav",
			Centered = "0",
			Chance = "155",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "150",
		},
		SOUNDS_Ambient_E3_storm_gust_1_wav = {
			Sound = "SOUNDS/Ambient/E3/storm_gust_1.wav",
			Centered = "0",
			Chance = "165",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "150",
		},
		SOUNDS_Ambient_E3_storm_gust_3_wav = {
			Sound = "SOUNDS/Ambient/E3/storm_gust_3.wav",
			Centered = "0",
			Chance = "175",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "150",
		},
	},
	shipclanges = {
		SOUNDS_creaks_metaldoor2_wav = {
			Sound = "SOUNDS/creaks/metaldoor2.wav",
			Centered = "0",
			Chance = "175",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "255",
		},
		SOUNDS_objectimpact_v22creak1_wav = {
			Sound = "SOUNDS/objectimpact/v22creak1.wav",
			Centered = "0",
			Chance = "180",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "255",
		},
		SOUNDS_creaks_metaldoor1_wav = {
			Sound = "SOUNDS/creaks/metaldoor1.wav",
			Centered = "0",
			Chance = "165",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "255",
		},
		SOUNDS_objectimpact_distantmetalhit_wav = {
			Sound = "SOUNDS/objectimpact/distantmetalhit.wav",
			Centered = "0",
			Chance = "220",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "150",
		},
		SOUNDS_creaks_metaldoor3_wav = {
			Sound = "SOUNDS/creaks/metaldoor3.wav",
			Centered = "0",
			Chance = "179",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "255",
		},
		SOUNDS_building_distantclank1_wav = {
			Sound = "SOUNDS/building/distantclank1.wav",
			Centered = "0",
			Chance = "170",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "150",
		},
		SOUNDS_objectimpact_v22creak2_wav = {
			Sound = "SOUNDS/objectimpact/v22creak2.wav",
			Centered = "0",
			Chance = "150",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "200",
		},
		SOUNDS_objectimpact_distantmetalhit2_wav = {
			Sound = "SOUNDS/objectimpact/distantmetalhit2.wav",
			Centered = "0",
			Chance = "172",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "255",
		},
		SOUNDS_objectimpact_distantmetalhit3_wav = {
			Sound = "SOUNDS/objectimpact/distantmetalhit3.wav",
			Centered = "0",
			Chance = "183",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "255",
		},
	},
	cliffwind = {
		SOUNDS_Ambient_E3_whistlinggust_1_wav = {
			Sound = "SOUNDS/Ambient/E3/whistlinggust 1.wav",
			Centered = "0",
			Chance = "190",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "150",
		},
		SOUNDS_Ambient_E3_whistlinggust3_wav = {
			Sound = "SOUNDS/Ambient/E3/whistlinggust3.wav",
			Centered = "0",
			Chance = "200",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "150",
		},
		SOUNDS_Ambient_E3_whistlinggust2_wav = {
			Sound = "SOUNDS/Ambient/E3/whistlinggust2.wav",
			Centered = "0",
			Chance = "180",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "150",
		},
		SOUNDS_wind44KADPCM_mountainwind144k_wav = {
			Sound = "SOUNDS/wind44KADPCM/mountainwind144k.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "18",
		},
	},
	treebuzz = {
		SOUNDS_birds_jbird5_wav = {
			Sound = "SOUNDS/birds/jbird5.wav",
			Centered = "0",
			Chance = "90",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "155",
		},
		SOUNDS_Ambient_E3_chipmunk_wav = {
			Sound = "SOUNDS/Ambient/E3/chipmunk.wav",
			Centered = "0",
			Chance = "72",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "105",
		},
		SOUNDS_birds_jbird2_wav = {
			Sound = "SOUNDS/birds/jbird2.wav",
			Centered = "0",
			Chance = "100",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "130",
		},
		SOUNDS_Ambient_E3_beachwindLP_wav = {
			Sound = "SOUNDS/Ambient/E3/beachwindLP.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "23",
		},
		SOUNDS_birds_jbird7_wav = {
			Sound = "SOUNDS/birds/jbird7.wav",
			Centered = "0",
			Chance = "118",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "155",
		},
		SOUNDS_birds_bird4_wav = {
			Sound = "SOUNDS/birds/bird4.wav",
			Centered = "0",
			Chance = "75",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "155",
		},
		SOUNDS_birds_jbird6_wav = {
			Sound = "SOUNDS/birds/jbird6.wav",
			Centered = "0",
			Chance = "0",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "155",
		},
		SOUNDS_Ambient_bugs_deep_jungle_wav = {
			Sound = "SOUNDS/Ambient/bugs/deep jungle.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "5",
		},
		SOUNDS_birds_jbird3_wav = {
			Sound = "SOUNDS/birds/jbird3.wav",
			Centered = "0",
			Chance = "85",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "130",
		},
		SOUNDS_birds_jbird1_wav = {
			Sound = "SOUNDS/birds/jbird1.wav",
			Centered = "0",
			Chance = "80",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "155",
		},
		SOUNDS_Ambient_E3_forestbird1_wav = {
			Sound = "SOUNDS/Ambient/E3/forestbird1.wav",
			Centered = "0",
			Chance = "66",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "180",
		},
		SOUNDS_Ambient_E3_weird_j_sound_wav = {
			Sound = "SOUNDS/Ambient/E3/weird_j_sound.wav",
			Centered = "0",
			Chance = "60",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "180",
		},
		SOUNDS_Ambient_E3_cricketfrognightLP_wav = {
			Sound = "SOUNDS/Ambient/E3/cricketfrognightLP.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "0",
		},
	},
	m3lightambi = {
		SOUNDS_jungle___M3_LIGHT_jungle_LP_ogg = {
			Sound = "SOUNDS/jungle///M3_LIGHT_jungle_LP.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "1",
			Timeout = "0",
			Volume = "75",
		},
	},
	metalcatwalks = {
		SOUNDS_metal_creak2_wav = {
			Sound = "SOUNDS/metal/creak2.wav",
			Centered = "0",
			Chance = "80",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
		SOUNDS_metal_creak1_wav = {
			Sound = "SOUNDS/metal/creak1.wav",
			Centered = "0",
			Chance = "85",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
		SOUNDS_metal_creak5_wav = {
			Sound = "SOUNDS/metal/creak5.wav",
			Centered = "0",
			Chance = "100",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
		SOUNDS_metal_creak3_wav = {
			Sound = "SOUNDS/metal/creak3.wav",
			Centered = "0",
			Chance = "90",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
		SOUNDS_metal_creak4_wav = {
			Sound = "SOUNDS/metal/creak4.wav",
			Centered = "0",
			Chance = "105",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
	},
	M10rain = {
		SOUNDS_rain_rainbasiclight1_wav = {
			Sound = "SOUNDS/rain/rainbasiclight1.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "80",
		},
	},
	shipexteriorgroans = {
		SOUNDS_building_shudder1_wav = {
			Sound = "SOUNDS/building/shudder1.wav",
			Centered = "0",
			Chance = "350",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "150",
		},
		SOUNDS_building_shudder2_wav = {
			Sound = "SOUNDS/building/shudder2.wav",
			Centered = "0",
			Chance = "400",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "150",
		},
		SOUNDS_objectimpact_v22creak2_wav = {
			Sound = "SOUNDS/objectimpact/v22creak2.wav",
			Centered = "0",
			Chance = "250",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "100",
		},
		SOUNDS_objectimpact_v22creak1_wav = {
			Sound = "SOUNDS/objectimpact/v22creak1.wav",
			Centered = "0",
			Chance = "280",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "100",
		},
	},
	rainwater = {
		SOUNDS_rain_rainpuddle2_wav = {
			Sound = "SOUNDS/rain/rainpuddle2.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "30",
		},
	},
	bullhorntraining = {
		LANGUAGES_English_missiontalk_armstraining_wav = {
			Sound = "languages/missiontalk/armstraining.wav",
			Centered = "0",
			Chance = "85",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "35",
			Volume = "255",
		},
		LANGUAGES_English_missiontalk_inbound_wav = {
			Sound = "languages/missiontalk/inbound.wav",
			Centered = "0",
			Chance = "80",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "35",
			Volume = "255",
		},
		LANGUAGES_English_missiontalk_command_wav = {
			Sound = "languages/missiontalk/command.wav",
			Centered = "0",
			Chance = "75",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "35",
			Volume = "255",
		},
		LANGUAGES_English_missiontalk_lassie_wav = {
			Sound = "languages/missiontalk/lassie.wav",
			Centered = "0",
			Chance = "30",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "35",
			Volume = "255",
		},
	},
	playerfallingwind = {
		Sounds_ambient_e3_whistlewindlp2_wav = {
			Sound = "Sounds/ambient/e3/whistlewindlp2.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
	},
	m3heavyambi = {
		SOUNDS_jungle_M3_heavy_jungle_LP_ogg = {
			Sound = "SOUNDS/jungle/M3_heavy_jungle_LP.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "1",
			Timeout = "0",
			Volume = "255",
		},
	},
	shipshudders = {
		SOUNDS_building_shudder1_wav = {
			Sound = "SOUNDS/building/shudder1.wav",
			Centered = "0",
			Chance = "250",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "255",
		},
		SOUNDS_building_shudder2_wav = {
			Sound = "SOUNDS/building/shudder2.wav",
			Centered = "0",
			Chance = "275",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "255",
		},
	},
	inlet = {
		SOUNDS_Ambient_E3_frogsloop_wav = {
			Sound = "SOUNDS/Ambient/E3/frogsloop.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "25",
		},
	},
	m3seagulls = {
		SOUNDS_missionbirds_gull3_wav = {
			Sound = "SOUNDS/missionbirds/gull3.wav",
			Centered = "0",
			Chance = "85",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "15",
			Volume = "225",
		},
		SOUNDS_missionbirds_gull1_wav = {
			Sound = "SOUNDS/missionbirds/gull1.wav",
			Centered = "0",
			Chance = "80",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "15",
			Volume = "225",
		},
		SOUNDS_missionbirds_gull4_wav = {
			Sound = "SOUNDS/missionbirds/gull4.wav",
			Centered = "0",
			Chance = "75",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "15",
			Volume = "225",
		},
		SOUNDS_missionbirds_gull2_wav = {
			Sound = "SOUNDS/missionbirds/gull2.wav",
			Centered = "0",
			Chance = "70",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "15",
			Volume = "225",
		},
	},
	m5nighttimeanimals2 = {
		SOUNDS_missionbirds_shakerbug2_wav = {
			Sound = "SOUNDS/missionbirds/shakerbug2.wav",
			Centered = "0",
			Chance = "82",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "15",
			Volume = "200",
		},
		SOUNDS_birds_WINGFLAP1_wav = {
			Sound = "SOUNDS/birds/WINGFLAP1.wav",
			Centered = "0",
			Chance = "75",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "15",
			Volume = "200",
		},
		SOUNDS_birds_wren_wav = {
			Sound = "SOUNDS/birds/wren.wav",
			Centered = "0",
			Chance = "112",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "15",
			Volume = "200",
		},
		SOUNDS_missionbirds_shakerbug_wav = {
			Sound = "SOUNDS/missionbirds/shakerbug.wav",
			Centered = "0",
			Chance = "80",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "15",
			Volume = "200",
		},
		SOUNDS_birds_WING_FLAP3_wav = {
			Sound = "SOUNDS/birds/WING FLAP3.wav",
			Centered = "0",
			Chance = "70",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "15",
			Volume = "200",
		},
		SOUNDS_birds_WING_FLAP2_wav = {
			Sound = "SOUNDS/birds/WING FLAP2.wav",
			Centered = "0",
			Chance = "65",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "15",
			Volume = "200",
		},
	},
	M10islandwind = {
		SOUNDS_wind44KADPCM_wind144k_wav = {
			Sound = "SOUNDS/wind44KADPCM/wind144k.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "8",
		},
	},
	m3deepheavyjungleambi = {
		SOUNDS_jungle_M3_deepheavyjungle_ogg = {
			Sound = "SOUNDS/jungle/M3_deepheavyjungle.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "1",
			Timeout = "0",
			Volume = "255",
		},
	},
	torturehutwindow2 = {
		SOUNDS_Ambient_E3_whistlewindLP_wav = {
			Sound = "SOUNDS/Ambient/E3/whistlewindLP.wav",
			Centered = "0",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "40",
		},
	},
	volcanobowl = {
		Sounds_Jungle_volcano_wav = {
			Sound = "Sounds/Jungle/volcano.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "100",
		},
	},
	m3stormwind = {
		SOUNDS_M3_stormwind2_LP_wav = {
			Sound = "SOUNDS/M3/stormwind2_LP.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "125",
		},
	},
	jungleday5lp2 = {
		SOUNDS_jungle_jungleday5lp2_ogg = {
			Sound = "SOUNDS/jungle/jungleday5lp2.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "50",
		},
	},
	smallroomtone2 = {
		Sounds_jungle_roomtone2_ogg = {
			Sound = "Sounds/jungle/roomtone2.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "150",
		},
	},
	cave1M04 = {
		SOUNDS_building_drip4_wav = {
			Sound = "SOUNDS/building/drip4.wav",
			Centered = "0",
			Chance = "95",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "255",
		},
		SOUNDS_building_drip11_wav = {
			Sound = "SOUNDS/building/drip11.wav",
			Centered = "0",
			Chance = "99",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "255",
		},
		SOUNDS_building_angels_wav = {
			Sound = "SOUNDS/building/angels.wav",
			Centered = "0",
			Chance = "175",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "220",
		},
		SOUNDS_building_drip2_wav = {
			Sound = "SOUNDS/building/drip2.wav",
			Centered = "0",
			Chance = "90",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "255",
		},
		SOUNDS_building_drip6_wav = {
			Sound = "SOUNDS/building/drip6.wav",
			Centered = "0",
			Chance = "89",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "255",
		},
		SOUNDS_building_drip1_wav = {
			Sound = "SOUNDS/building/drip1.wav",
			Centered = "0",
			Chance = "87",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "255",
		},
		SOUNDS_building_drip7_wav = {
			Sound = "SOUNDS/building/drip7.wav",
			Centered = "0",
			Chance = "73",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "255",
		},
		SOUNDS_building_drip5_wav = {
			Sound = "SOUNDS/building/drip5.wav",
			Centered = "0",
			Chance = "83",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "255",
		},
		SOUNDS_building_drip8_wav = {
			Sound = "SOUNDS/building/drip8.wav",
			Centered = "0",
			Chance = "80",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "255",
		},
		SOUNDS_birds_WINGFLAP1_wav = {
			Sound = "SOUNDS/birds/WINGFLAP1.wav",
			Centered = "0",
			Chance = "100",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "255",
		},
		SOUNDS_building_drip10_wav = {
			Sound = "SOUNDS/building/drip10.wav",
			Centered = "0",
			Chance = "79",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "255",
		},
		SOUNDS_building_drip3_wav = {
			Sound = "SOUNDS/building/drip3.wav",
			Centered = "0",
			Chance = "77",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "255",
		},
		SOUNDS_building_chill_wav = {
			Sound = "SOUNDS/building/chill.wav",
			Centered = "0",
			Chance = "150",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "255",
		},
		SOUNDS_building_drip9_wav = {
			Sound = "SOUNDS/building/drip9.wav",
			Centered = "0",
			Chance = "75",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "25",
			Volume = "255",
		},
		SOUNDS_Ambient_E3_hallwindLP_wav = {
			Sound = "SOUNDS/Ambient/E3/hallwindLP.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "120",
		},
	},
	M3shoreline = {
		SOUNDS_M3_waterlap5_wav = {
			Sound = "SOUNDS/M3/waterlap5.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "150",
		},
	},
	torturehutcreaking = {
		SOUNDS_creaks_creak3_wav = {
			Sound = "SOUNDS/creaks/creak3.wav",
			Centered = "0",
			Chance = "100",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "15",
			Volume = "255",
		},
		SOUNDS_creaks_creak1_wav = {
			Sound = "SOUNDS/creaks/creak1.wav",
			Centered = "0",
			Chance = "110",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "15",
			Volume = "255",
		},
		SOUNDS_creaks_creak2_wav = {
			Sound = "SOUNDS/creaks/creak2.wav",
			Centered = "0",
			Chance = "115",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "15",
			Volume = "255",
		},
		SOUNDS_creaks_creak4_wav = {
			Sound = "SOUNDS/creaks/creak4.wav",
			Centered = "0",
			Chance = "105",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "15",
			Volume = "255",
		},
	},
	m5basiccrickets = {
		SOUNDS_Ambient_crickets_cr_night5_wav = {
			Sound = "SOUNDS/Ambient/crickets/cr_night5.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "50",
		},
	},
	localcrickets = {
		SOUNDS_Ambient_crickets_quadcrick_wav = {
			Sound = "SOUNDS/Ambient/crickets/quadcrick.wav",
			Centered = "0",
			Chance = "100",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "200",
		},
		SOUNDS_Ambient_crickets_doublecr_wav = {
			Sound = "SOUNDS/Ambient/crickets/doublecr.wav",
			Centered = "0",
			Chance = "90",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "200",
		},
	},
	canyonwind1 = {
		SOUNDS_wind44KADPCM_CHASMWIND144K_wav = {
			Sound = "SOUNDS/wind44KADPCM/CHASMWIND144K.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "100",
		},
	},
	torturehutwind1 = {
		SOUNDS_Ambient_E3_whistlewindLP_wav = {
			Sound = "SOUNDS/Ambient/E3/whistlewindLP.wav",
			Centered = "0",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "40",
		},
	},
	riverrainpst = {
		SOUNDS_rain_rainpuddle1_wav = {
			Sound = "SOUNDS/rain/rainpuddle1.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "35",
		},
	},
	coolinsects1mono = {
		Sounds_jungle_cool_insects1lpmono_wav = {
			Sound = "Sounds/jungle/cool_insects1lpmono.wav",
			Centered = "0",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
	},
	m8basiccrickets = {
		SOUNDS_Ambient_crickets_cr_night6_wav = {
			Sound = "SOUNDS/Ambient/crickets/cr_night6.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "15",
		},
	},
	m03bugs1 = {
		SOUNDS_jungle_cool_insects1lp_ogg = {
			Sound = "SOUNDS/jungle/cool_insects1lp.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "1",
			Timeout = "0",
			Volume = "150",
		},
	},
	ropebridges = {
		SOUNDS_creaks_creak1_wav = {
			Sound = "SOUNDS/creaks/creak1.wav",
			Centered = "0",
			Chance = "120",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "20",
			Volume = "130",
		},
		SOUNDS_creaks_creak2_wav = {
			Sound = "SOUNDS/creaks/creak2.wav",
			Centered = "0",
			Chance = "140",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "20",
			Volume = "130",
		},
	},
	cliffwind2 = {
		SOUNDS_Ambient_E3_storm_gust_1_wav = {
			Sound = "SOUNDS/Ambient/E3/storm_gust_1.wav",
			Centered = "0",
			Chance = "150",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "125",
		},
		SOUNDS_Ambient_E3_storm_gust_3_wav = {
			Sound = "SOUNDS/Ambient/E3/storm_gust_3.wav",
			Centered = "0",
			Chance = "140",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "125",
		},
		SOUNDS_Ambient_E3_storm_gust_2_wav = {
			Sound = "SOUNDS/Ambient/E3/storm_gust_2.wav",
			Centered = "0",
			Chance = "130",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "125",
		},
		SOUNDS_wind44KADPCM_mountainwind144k_wav = {
			Sound = "SOUNDS/wind44KADPCM/mountainwind144k.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "9",
		},
	},
	lava = {
		Sounds_thunder_lavalp_wav = {
			Sound = "Sounds/thunder/lavalp.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
	},
	coolinsectsinteriorholes = {
		SOUNDS_jungle_cool_insects1lp_ogg = {
			Sound = "SOUNDS/jungle/cool_insects1lp.wav",
			Centered = "0",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "1",
			Timeout = "0",
			Volume = "255",
		},
	},
	Misceetandcrick = {
		SOUNDS_newcrickets_swamp244k_wav = {
			Sound = "SOUNDS/newcrickets/swamp244k.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "25",
		},
		SOUNDS_Ambient_bugs_misceets_wav = {
			Sound = "SOUNDS/Ambient/bugs/misceets.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "25",
		},
	},
	thunder = {
		SOUNDS_thunder_tclap2_wav = {
			Sound = "SOUNDS/thunder/tclap2.wav",
			Centered = "0",
			Chance = "30",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "250",
		},
		SOUNDS_thunder_trumble3_wav = {
			Sound = "SOUNDS/thunder/trumble3.wav",
			Centered = "0",
			Chance = "425",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
		SOUNDS_thunder_trumble2_wav = {
			Sound = "SOUNDS/thunder/trumble2.wav",
			Centered = "0",
			Chance = "481",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
		SOUNDS_thunder_tclap3_wav = {
			Sound = "SOUNDS/thunder/tclap3.wav",
			Centered = "0",
			Chance = "40",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "250",
		},
		SOUNDS_thunder_tclap1_wav = {
			Sound = "SOUNDS/thunder/tclap1.wav",
			Centered = "0",
			Chance = "55",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "250",
		},
		SOUNDS_thunder_trumble4_wav = {
			Sound = "SOUNDS/thunder/trumble4.wav",
			Centered = "0",
			Chance = "359",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
		SOUNDS_thunder_trumble1_wav = {
			Sound = "SOUNDS/thunder/trumble1.wav",
			Centered = "0",
			Chance = "500",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
	},
	tunnelwindpre = {
		SOUNDS_Ambient_E3_tunnelwind2LP_wav = {
			Sound = "SOUNDS/Ambient/E3/tunnelwind2LP.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "50",
		},
	},
	test = {
		SOUNDS_newcrickets_crick1044k_wav = {
			Sound = "SOUNDS/newcrickets/crick1044k.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "25",
		},
	},
	m05interiorsounds = {
		SOUNDS_building_distantclank1_wav = {
			Sound = "SOUNDS/building/distantclank1.wav",
			Centered = "0",
			Chance = "86",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "15",
			Volume = "150",
		},
		SOUNDS_building_shudder1_wav = {
			Sound = "SOUNDS/building/shudder1.wav",
			Centered = "0",
			Chance = "100",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "15",
			Volume = "255",
		},
		SOUNDS_objectimpact_distantmetalhit3_wav = {
			Sound = "SOUNDS/objectimpact/distantmetalhit3.wav",
			Centered = "0",
			Chance = "93",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "15",
			Volume = "200",
		},
		SOUNDS_objectimpact_distantmetalhit2_wav = {
			Sound = "SOUNDS/objectimpact/distantmetalhit2.wav",
			Centered = "0",
			Chance = "95",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "15",
			Volume = "200",
		},
		SOUNDS_building_shudder2_wav = {
			Sound = "SOUNDS/building/shudder2.wav",
			Centered = "0",
			Chance = "110",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "17",
			Volume = "255",
		},
	},
	rebellionguns = {
		Sounds_explosions_rebgun10_wav = {
			Sound = "Sounds/explosions/rebgun10.wav",
			Centered = "0",
			Chance = "49",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		Sounds_explosions_rebgun9_wav = {
			Sound = "Sounds/explosions/rebgun9.wav",
			Centered = "0",
			Chance = "48",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		Sounds_explosions_rebgun17_wav = {
			Sound = "Sounds/explosions/rebgun17.wav",
			Centered = "0",
			Chance = "57",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		Sounds_explosions_rebgun15_wav = {
			Sound = "Sounds/explosions/rebgun15.wav",
			Centered = "0",
			Chance = "55",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		Sounds_explosions_rebgun1_wav = {
			Sound = "Sounds/explosions/rebgun1.wav",
			Centered = "0",
			Chance = "42",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		Sounds_explosions_rebgun11_wav = {
			Sound = "Sounds/explosions/rebgun11.wav",
			Centered = "0",
			Chance = "50",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		Sounds_explosions_rebgun16_wav = {
			Sound = "Sounds/explosions/rebgun16.wav",
			Centered = "0",
			Chance = "56",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		Sounds_explosions_rebgun4_wav = {
			Sound = "Sounds/explosions/rebgun4.wav",
			Centered = "0",
			Chance = "44",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		Sounds_explosions_rebgun19_wav = {
			Sound = "Sounds/explosions/rebgun19.wav",
			Centered = "0",
			Chance = "59",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		Sounds_explosions_rebgun7_wav = {
			Sound = "Sounds/explosions/rebgun7.wav",
			Centered = "0",
			Chance = "47",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		Sounds_explosions_rebgun18_wav = {
			Sound = "Sounds/explosions/rebgun18.wav",
			Centered = "0",
			Chance = "58",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		Sounds_explosions_rebgun6_wav = {
			Sound = "Sounds/explosions/rebgun6.wav",
			Centered = "0",
			Chance = "0",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		Sounds_explosions_rebgun13_wav = {
			Sound = "Sounds/explosions/rebgun13.wav",
			Centered = "0",
			Chance = "53",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "255",
		},
		Sounds_explosions_rebgun8_wav = {
			Sound = "Sounds/explosions/rebgun8.wav",
			Centered = "0",
			Chance = "47",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		Sounds_explosions_rebgun12_wav = {
			Sound = "Sounds/explosions/rebgun12.wav",
			Centered = "0",
			Chance = "52",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		Sounds_explosions_rebgun5_wav = {
			Sound = "Sounds/explosions/rebgun5.wav",
			Centered = "0",
			Chance = "45",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		Sounds_explosions_rebgun2_wav = {
			Sound = "Sounds/explosions/rebgun2.wav",
			Centered = "0",
			Chance = "43",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		Sounds_explosions_rebgun14_wav = {
			Sound = "Sounds/explosions/rebgun14.wav",
			Centered = "0",
			Chance = "54",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
	},
	buildingrumble = {
		SOUNDS_building_strain_wav = {
			Sound = "SOUNDS/building/strain.wav",
			Centered = "0",
			Chance = "65",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "90",
			Volume = "85",
		},
		SOUNDS_building_shudder1_wav = {
			Sound = "SOUNDS/building/shudder1.wav",
			Centered = "0",
			Chance = "115",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		SOUNDS_building_rumblelp_wav = {
			Sound = "SOUNDS/building/rumblelp.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "100",
		},
		SOUNDS_building_shudder2_wav = {
			Sound = "SOUNDS/building/shudder2.wav",
			Centered = "0",
			Chance = "105",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "255",
		},
		SOUNDS_building_clank1_wav = {
			Sound = "SOUNDS/building/clank1.wav",
			Centered = "0",
			Chance = "75",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "135",
		},
	},
	m5firsttressaeaPST = {
		SOUNDS_M5components_crickchichmix10down_wav = {
			Sound = "SOUNDS/M5components/crickchichmix10down.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "15",
		},
	},
	volcanowind = {
		Sounds_wind44kadpcm_chasmwind144k_wav = {
			Sound = "Sounds/wind44kadpcm/chasmwind144k.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "5",
		},
	},
	carrier = {
		LANGUAGES_English_missiontalk_carrier2_wav = {
			Sound = "languages/missiontalk/carrier2.wav",
			Centered = "1",
			Chance = "68",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "60",
			Volume = "75",
		},
		LANGUAGES_English_missiontalk_carrier1_wav = {
			Sound = "languages/missiontalk/carrier1.wav",
			Centered = "0",
			Chance = "69",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "60",
			Volume = "75",
		},
		LANGUAGES_English_missiontalk_carrier4_wav = {
			Sound = "languages/missiontalk/carrier4.wav",
			Centered = "1",
			Chance = "79",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "60",
			Volume = "75",
		},
		LANGUAGES_English_missiontalk_carrier3_wav = {
			Sound = "languages/missiontalk/carrier3.wav",
			Centered = "1",
			Chance = "78",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "60",
			Volume = "75",
		},
		LANGUAGES_English_missiontalk_carrier7_wav = {
			Sound = "languages/missiontalk/carrier7.wav",
			Centered = "1",
			Chance = "77",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "60",
			Volume = "75",
		},
		LANGUAGES_English_missiontalk_carrier6_wav = {
			Sound = "languages/missiontalk/carrier6.wav",
			Centered = "1",
			Chance = "76",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "60",
			Volume = "75",
		},
		LANGUAGES_English_missiontalk_carrier5_wav = {
			Sound = "languages/missiontalk/carrier5.wav",
			Centered = "1",
			Chance = "75",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "30",
			Volume = "75",
		},
	},
	cavethunderrumblePST = {
		SOUNDS_thunder_trumble1_wav = {
			Sound = "SOUNDS/thunder/trumble1.wav",
			Centered = "0",
			Chance = "500",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "150",
		},
		SOUNDS_thunder_trumble2_wav = {
			Sound = "SOUNDS/thunder/trumble2.wav",
			Centered = "0",
			Chance = "425",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "150",
		},
		SOUNDS_thunder_trumble4_wav = {
			Sound = "SOUNDS/thunder/trumble4.wav",
			Centered = "0",
			Chance = "450",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "150",
		},
		SOUNDS_thunder_trumble3_wav = {
			Sound = "SOUNDS/thunder/trumble3.wav",
			Centered = "0",
			Chance = "475",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "150",
		},
	},
	steamingshoreline = {
		SOUNDS_jungle_wavesmono_ogg = {
			Sound = "SOUNDS/jungle/wavesmono.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "1",
			Timeout = "0",
			Volume = "50",
		},
	},
	damjungle = {
		Sounds_jungle_damJungle1_wav = {
			Sound = "Sounds/jungle/damJungle1.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "100",
		},
	},
	tunnelrain = {
		Sounds_rain__raintunnel_wav = {
			Sound = "Sounds/rain//raintunnel.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "100",
		},
	},
	coolinsects1interior = {
		SOUNDS_jungle_cool_insects1lp_ogg = {
			Sound = "SOUNDS/jungle/cool_insects1lp.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "1",
			Timeout = "0",
			Volume = "200",
		},
	},
	musictest = {
		MUSIC_SeeShip_ogg = {
			Sound = "MUSIC/SeeShip.ogg",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "1",
			Timeout = "0",
			Volume = "200",
		},
	},
	swampfrogs = {
		SOUNDS_Ambient_E3_frog2_wav = {
			Sound = "SOUNDS/Ambient/E3/frog2.wav",
			Centered = "0",
			Chance = "70",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "10",
			Volume = "255",
		},
		SOUNDS_Ambient_E3_frog4_wav = {
			Sound = "SOUNDS/Ambient/E3/frog4.wav",
			Centered = "0",
			Chance = "75",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "10",
			Volume = "255",
		},
		SOUNDS_Ambient_E3_frog3_wav = {
			Sound = "SOUNDS/Ambient/E3/frog3.wav",
			Centered = "0",
			Chance = "65",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "10",
			Volume = "175",
		},
	},
	M05ambient = {
		SOUNDS_Ambient_bugs_buzjungle4_wav = {
			Sound = "SOUNDS/Ambient/bugs/buzjungle4.wav",
			Centered = "1",
			Chance = "1000",
			NoOverlap = "1",
			Streaming = "0",
			Timeout = "0",
			Volume = "30",
		},
	},
}