function PipeManager:InitMutants()

	AI:CreateGoalPipe("predator_hiding")
	AI:PushGoal("predator_hiding","setup_stand")
	AI:PushGoal("predator_hiding","do_it_running")
	AI:PushGoal("predator_hiding","locate",1,"beacon")
	AI:PushGoal("predator_hiding","acqtarget",1,"")
	-- AI:PushGoal("predator_hiding","locate",1,"atttarget")
	-- AI:PushGoal("predator_hiding","acqtarget",1,"")
	-- AI:PushGoal("predator_hiding","ignoreall",1,1)
	AI:PushGoal("predator_hiding","hide",1,30,HM_FARTHEST_FROM_TARGET,1)
	AI:PushGoal("predator_hiding","locate",1,"hidepoint")
	AI:PushGoal("predator_hiding","acqtarget",1,"")
	AI:PushGoal("predator_hiding","pathfind",1,"")
	AI:PushGoal("predator_hiding","trace",1,1,0)
	AI:PushGoal("predator_hiding","backoff",1,3)
	-- AI:PushGoal("predator_hiding","ignoreall",1,0)
	AI:PushGoal("predator_hiding","devalue",0,1)
	AI:PushGoal("predator_hiding","backoff",1,3)
	AI:PushGoal("predator_hiding","timeout",1,.5,1)
	AI:PushGoal("predator_hiding","lookat",1,-145,145)
	AI:PushGoal("predator_hiding","branch",0,-1)
	AI:PushGoal("predator_hiding","timeout",1,1)
	AI:PushGoal("predator_hiding","locate",1,"atttarget")
	AI:PushGoal("predator_hiding","acqtarget",1,"")
	AI:PushGoal("predator_hiding","pathfind",1,"")
	AI:PushGoal("predator_hiding","trace",1,1,0)
	AI:PushGoal("predator_hiding","signal",0,1,"SWITCH_TO_ATTACK",0)

	AI:CreateGoalPipe("predator_attack_left")
	AI:PushGoal("predator_attack_left","predator_is_invisible")
	AI:PushGoal("predator_attack_left","setup_stand")
	AI:PushGoal("predator_attack_left","ignoreall",1,0)
	AI:PushGoal("predator_attack_left","hide",1,300,HM_NEAREST)
	AI:PushGoal("predator_attack_left","ignoreall",1,1)
	AI:PushGoal("predator_attack_left","hide",1,30,HM_NEAREST_TO_TARGET)
	AI:PushGoal("predator_attack_left","timeout",1,.5,1.5)
	AI:PushGoal("predator_attack_left","hide",1,30,HM_NEAREST)
	AI:PushGoal("predator_attack_left","hide",1,20,HM_LEFTMOST_FROM_TARGET)
	AI:PushGoal("predator_attack_left","look_behind")
	-- AI:PushGoal("predator_attack_left","timeout",1,.5,1.5)
--	AI:PushGoal("predator_attack_left","devalue_target")
	AI:PushGoal("predator_attack_left","hide",1,20,HM_NEAREST)
	AI:PushGoal("predator_attack_left","hide",1,10,HM_LEFTMOST_FROM_TARGET)
	AI:PushGoal("predator_attack_left","timeout",1,.5,1.5)
--	AI:PushGoal("predator_attack_left","hide",1,10,HM_NEAREST)
	AI:PushGoal("predator_attack_left","hide",1,5,HM_LEFTMOST_FROM_TARGET)
--	AI:PushGoal("predator_attack_left","hide",1,30,HM_FARTHEST_FROM_TARGET)
	-- AI:PushGoal("predator_attack_left","devalue_target")
	AI:PushGoal("predator_attack_left","signal",0,1,"SWITCH_TO_ATTACK",0)

	AI:CreateGoalPipe("predator_attack_right")
	AI:PushGoal("predator_attack_right","predator_is_invisible")
	AI:PushGoal("predator_attack_right","setup_stand")
	AI:PushGoal("predator_attack_right","ignoreall",1,0)
	AI:PushGoal("predator_attack_right","hide",1,300,HM_NEAREST)
	AI:PushGoal("predator_attack_right","ignoreall",1,1)
	AI:PushGoal("predator_attack_right","hide",1,30,HM_NEAREST_TO_TARGET)
	AI:PushGoal("predator_attack_right","timeout",1,.5,1.5)
	AI:PushGoal("predator_attack_right","hide",1,30,HM_NEAREST)
	AI:PushGoal("predator_attack_right","hide",1,20,HM_RIGHTMOST_FROM_TARGET)
	AI:PushGoal("predator_attack_right","look_behind")
	-- AI:PushGoal("predator_attack_right","timeout",1,.5,1.5)
--	AI:PushGoal("predator_attack_right","devalue_target")
	AI:PushGoal("predator_attack_right","hide",1,20,HM_NEAREST)
	AI:PushGoal("predator_attack_right","hide",1,10,HM_RIGHTMOST_FROM_TARGET)
	AI:PushGoal("predator_attack_right","timeout",1,.5,1.5)
--	AI:PushGoal("predator_attack_right","hide",1,10,HM_NEAREST)
	AI:PushGoal("predator_attack_right","hide",1,5,HM_RIGHTMOST_FROM_TARGET)
--	AI:PushGoal("predator_attack_right","hide",1,30,HM_FARTHEST_FROM_TARGET)
	-- AI:PushGoal("predator_attack_right","devalue_target")
	AI:PushGoal("predator_attack_right","signal",0,1,"SWITCH_TO_ATTACK",0)

	-- AI:CreateGoalPipe("predator_just_attack")
	-- AI:PushGoal("predator_just_attack","setup_stand")
	-- AI:PushGoal("predator_just_attack","do_it_running")
	-- AI:PushGoal("predator_just_attack","locate",0,"beacon")
	-- AI:PushGoal("predator_just_attack","acqtarget",0,"")
	-- AI:PushGoal("predator_just_attack","approach",0,1)
	-- AI:PushGoal("predator_just_attack","trace",0,1,1)
	-- AI:PushGoal("predator_just_attack","timeout",1,.1,1)
	-- AI:PushGoal("predator_just_attack","signal",1,1,"SEEK_JUMP_ANCHOR",0)
	-- AI:PushGoal("predator_just_attack","signal",0,1,"CHECK_FOR_FIND_A_TARGET",0)

	AI:CreateGoalPipe("predator_melee")
	AI:PushGoal("predator_melee","approach",0,0)
	AI:PushGoal("predator_melee","timeout",1,0,.05)
	AI:PushGoal("predator_melee","signal",1,1,"PREDATOR_MELEE",0)

	AI:CreateGoalPipe("predator_after_jump_attack")
	AI:PushGoal("predator_after_jump_attack","do_it_running")
	AI:PushGoal("predator_after_jump_attack","approach",0,1)
	AI:PushGoal("predator_after_jump_attack","timeout",1,.1,.5)
	AI:PushGoal("predator_after_jump_attack","predator_just_attack")

	AI:CreateGoalPipe("predator_just_attack")
	AI:PushGoal("predator_just_attack","signal",1,1,"SEEK_JUMP_ANCHOR",0)
	AI:PushGoal("predator_just_attack","setup_stand")
	AI:PushGoal("predator_just_attack","do_it_running")
	-- AI:PushGoal("predator_just_attack","form",1,"beacon")
	-- AI:PushGoal("predator_just_attack","locate",0,"beacon")
	AI:PushGoal("predator_just_attack","locate",0,"atttarget")
	AI:PushGoal("predator_just_attack","form",1,"atttarget")
	-- AI:PushGoal("predator_just_attack","form",1,"atttarget")
	AI:PushGoal("predator_just_attack","acqtarget",1,"")
	-- AI:PushGoal("predator_just_attack","approach",0,0)
	AI:PushGoal("predator_just_attack","approach",0,1.1)
	AI:PushGoal("predator_just_attack","signal",0,1,"CHECK_FOR_FIND_A_TARGET",0)

	AI:CreateGoalPipe("predator_attack_pathfind")
	AI:PushGoal("predator_attack_pathfind","setup_stand")
	AI:PushGoal("predator_attack_pathfind","do_it_running")
	AI:PushGoal("predator_attack_pathfind","locate",0,"atttarget")
	AI:PushGoal("predator_attack_pathfind","acqtarget",1,"")
	AI:PushGoal("predator_attack_pathfind","pathfind",1,"")
	AI:PushGoal("predator_attack_pathfind","trace",1,1,1)
	AI:PushGoal("predator_attack_pathfind","signal",1,1,"PREDATOR_ATTACK",0) -- В случае отсутствия цели будет FIND_A_TARGET

	AI:CreateGoalPipe("predator_heads_up")
	AI:PushGoal("predator_heads_up","locate",0,"beacon")
	AI:PushGoal("predator_heads_up","acqtarget",0,"")
	-- AI:PushGoal("predator_heads_up","do_it_running")
	-- AI:PushGoal("predator_heads_up","approach",1,.8)
	AI:PushGoal("predator_heads_up","signal",0,1,"SWITCH_TO_ATTACK",0)

	AI:CreateGoalPipe("predator_wait_for_target")
	AI:PushGoal("predator_wait_for_target","setup_stand")
	AI:PushGoal("predator_wait_for_target","acqtarget",1,"")
	AI:PushGoal("predator_wait_for_target","timeout",1,0,60)
	AI:PushGoal("predator_wait_for_target","clear")

	AI:CreateGoalPipe("predator_interested")
	AI:PushGoal("predator_interested","do_it_walking")
	AI:PushGoal("predator_interested","setup_stand")
	AI:PushGoal("predator_interested","approach",1,1)
	AI:PushGoal("predator_interested","clear")

	AI:CreateGoalPipe("predator_hide_wait_attack")
	AI:PushGoal("predator_hide_wait_attack","setup_stand")
	AI:PushGoal("predator_hide_wait_attack","do_it_running")
	AI:PushGoal("predator_hide_wait_attack","locate",0,"beacon")
	AI:PushGoal("predator_hide_wait_attack","acqtarget",0,"")
	AI:PushGoal("predator_hide_wait_attack","timeout",1,.5,2)
	AI:PushGoal("predator_hide_wait_attack","hide",1,60,HM_NEAREST_TO_TARGET,1)
	AI:PushGoal("predator_hide_wait_attack","timeout",1,0,1)
	AI:PushGoal("predator_hide_wait_attack","locate",0,"hidepoint")
	AI:PushGoal("predator_hide_wait_attack","acqtarget",0,"")
	AI:PushGoal("predator_hide_wait_attack","timeout",1,0,1)
	AI:PushGoal("predator_hide_wait_attack","locate",0,"hidepoint")
	AI:PushGoal("predator_hide_wait_attack","acqtarget",0,"")
	AI:PushGoal("predator_hide_wait_attack","timeout",1,0,1)
	AI:PushGoal("predator_hide_wait_attack","locate",0,"beacon")
	AI:PushGoal("predator_hide_wait_attack","acqtarget",0,"")
	AI:PushGoal("predator_hide_wait_attack","timeout",1,0,15)
	AI:PushGoal("predator_hide_wait_attack","pathfind",1,"")
	AI:PushGoal("predator_hide_wait_attack","trace",1,1,0)
	AI:PushGoal("predator_hide_wait_attack","backoff",1,3)
	-- AI:PushGoal("predator_hide_wait_attack","approach",0,2)
	AI:PushGoal("predator_hide_wait_attack","signal",0,1,"SWITCH_TO_ATTACK",0)

	AI:CreateGoalPipe("predator_hide_wait_serach")
	AI:PushGoal("predator_hide_wait_serach","setup_stand")
	AI:PushGoal("predator_hide_wait_serach","do_it_running")
	AI:PushGoal("predator_hide_wait_serach","locate",0,"beacon")
	AI:PushGoal("predator_hide_wait_serach","acqtarget",1,"")
	AI:PushGoal("predator_hide_wait_serach","timeout",1,0,1)
	AI:PushGoal("predator_hide_wait_serach","hide",1,60,HM_NEAREST,1)
	AI:PushGoal("predator_hide_wait_serach","timeout",1,0,1)
	AI:PushGoal("predator_hide_wait_serach","look_around")
	AI:PushGoal("predator_hide_wait_serach","timeout",1,0,1)
	AI:PushGoal("predator_hide_wait_serach","locate",0,"beacon")
	AI:PushGoal("predator_hide_wait_serach","acqtarget",1,"")
	AI:PushGoal("predator_hide_wait_serach","timeout",1,0,60)
	AI:PushGoal("predator_hide_wait_serach","do_it_walking")
	AI:PushGoal("predator_hide_wait_serach","timeout",1,.5,1)
	AI:PushGoal("predator_hide_wait_serach","predator_is_visible")
	AI:PushGoal("predator_hide_wait_serach","timeout",1,.5,1)
	AI:PushGoal("predator_hide_wait_serach","signal",0,1,"FIND_A_TARGET",0)

	AI:CreateGoalPipe("predator_threatening")
	AI:PushGoal("predator_threatening","setup_stand")
	AI:PushGoal("predator_threatening","do_it_running")
	AI:PushGoal("predator_threatening","acqtarget",1,"")
	AI:PushGoal("predator_threatening","timeout",1,0,1)
	AI:PushGoal("predator_threatening","hide",1,60,HM_NEAREST,1)
	AI:PushGoal("predator_threatening","locate",0,"beacon")
	AI:PushGoal("predator_threatening","acqtarget",0,"")
	AI:PushGoal("predator_threatening","timeout",1,0,1)
	AI:PushGoal("predator_threatening","pathfind",1,"")
	AI:PushGoal("predator_threatening","trace",1,1,1)
	AI:PushGoal("predator_threatening","timeout",1,.5,1)
	AI:PushGoal("predator_threatening","predator_is_visible")
	AI:PushGoal("predator_threatening","timeout",1,.5,1)
	AI:PushGoal("predator_threatening","signal",0,1,"FIND_A_TARGET",0)

	AI:CreateGoalPipe("look_around")
	AI:PushGoal("look_around","locate",0,"hidepoint")
	AI:PushGoal("look_around","acqtarget",0,"")
	AI:PushGoal("look_around","timeout",1,0,2)
	AI:PushGoal("look_around","signal",0,1,"FORCE_RESPONSIVENESS_3",0)
	AI:PushGoal("look_around","lookat",1,-90,90)
	AI:PushGoal("look_around","signal",0,1,"FORCE_RESPONSIVENESS_CLEAR",0)
	AI:PushGoal("look_around","timeout",1,0,2)
	AI:PushGoal("look_around","branch",0,-1)
	AI:PushGoal("look_around","timeout",1,0,2)
	AI:PushGoal("look_around","signal",0,1,"FORCE_RESPONSIVENESS_3",0)
	AI:PushGoal("look_around","lookat",1,-90,90)
	AI:PushGoal("look_around","signal",0,1,"FORCE_RESPONSIVENESS_CLEAR",0)
	AI:PushGoal("look_around","locate",0,"hidepoint")
	AI:PushGoal("look_around","acqtarget",0,"")
	AI:PushGoal("look_around","timeout",1,0,2)
	AI:PushGoal("look_around","locate",0,"hidepoint")
	AI:PushGoal("look_around","acqtarget",0,"")
	AI:PushGoal("look_around","timeout",1,0,2)
	AI:PushGoal("look_around","signal",0,1,"FORCE_RESPONSIVENESS_3",0)
	AI:PushGoal("look_around","lookat",1,-145,145)
	AI:PushGoal("look_around","signal",0,1,"FORCE_RESPONSIVENESS_CLEAR",0)
	AI:PushGoal("look_around","timeout",1,0,2)
	AI:PushGoal("look_around","branch",0,-2)
	AI:PushGoal("look_around","timeout",1,0,2)
	AI:PushGoal("look_around","signal",0,1,"FORCE_RESPONSIVENESS_3",0)
	AI:PushGoal("look_around","lookat",1,-145,145)
	AI:PushGoal("look_around","signal",0,1,"FORCE_RESPONSIVENESS_CLEAR",0)
	AI:PushGoal("look_around","locate",0,"hidepoint")
	AI:PushGoal("look_around","acqtarget",0,"")

	AI:CreateGoalPipe("look_behind")
	-- AI:PushGoal("look_behind","timeout",1,0,2)
	-- AI:PushGoal("look_behind","branch",1,-4)
	-- AI:PushGoal("look_behind","timeout",1,0,2)
	AI:PushGoal("look_behind","lookat",1,-180,180)

	AI:CreateGoalPipe("abberation_hang_back")
	AI:PushGoal("abberation_hang_back","not_shoot")
	AI:PushGoal("abberation_hang_back","setup_stand")
	AI:PushGoal("abberation_hang_back","do_it_walking")
	AI:PushGoal("abberation_hang_back","signal",1,1,"MAKE_COMBAT_BREAK_ANIM",0)
	AI:PushGoal("abberation_hang_back","signal",1,1,"SELECT_MOVEMENT",0)
	AI:PushGoal("abberation_hang_back","timeout",1,.3,.8)

	AI:CreateGoalPipe("abberation_hang_left")
	AI:PushGoal("abberation_hang_left","hide",1,15,HM_FRONTLEFTMOST_FROM_TARGET)

	AI:CreateGoalPipe("abberation_hang_right")
	AI:PushGoal("abberation_hang_right","hide",1,15,HM_FRONTRIGHTMOST_FROM_TARGET)

	AI:CreateGoalPipe("abberation_hang_away")
	AI:PushGoal("abberation_hang_away","hide",1,10,HM_FARTHEST_FROM_TARGET)

	AI:CreateGoalPipe("abberation_wait_back")
	AI:PushGoal("abberation_wait_back","timeout",1,.5,1)

	AI:CreateGoalPipe("predator_seeking_enemies")
	AI:PushGoal("predator_seeking_enemies","locate",0,"beacon")
	AI:PushGoal("predator_seeking_enemies","acqtarget",1,"")
	AI:PushGoal("predator_seeking_enemies","approach",1,.6)
	-- AI:PushGoal("predator_seeking_enemies","approach",1,1)
	AI:PushGoal("predator_seeking_enemies","timeout",1,0,1)
	AI:PushGoal("predator_seeking_enemies","approach",1,6)
	AI:PushGoal("predator_seeking_enemies","timeout",1,0,1)
	AI:PushGoal("predator_seeking_enemies","backoff",0,1)
	AI:PushGoal("predator_seeking_enemies","timeout",1,0,2)
	AI:PushGoal("predator_seeking_enemies","hide",1,30,HM_RANDOM)
	AI:PushGoal("predator_seeking_enemies","timeout",1,0,2)
	AI:PushGoal("predator_seeking_enemies","lookat",1,-90,90)
	AI:PushGoal("predator_seeking_enemies","branch",1,-2)
	AI:PushGoal("predator_seeking_enemies","lookat",1,-145,145)
	AI:PushGoal("predator_seeking_enemies","timeout",1,0,2)
	AI:PushGoal("predator_seeking_enemies","lookat",1,-145,145)
	AI:PushGoal("predator_seeking_enemies","branch",1,-2)
	AI:PushGoal("predator_seeking_enemies","timeout",1,0,3)
	AI:PushGoal("predator_seeking_enemies","hide",1,80,HM_RANDOM,1)
	AI:PushGoal("predator_seeking_enemies","timeout",1,0,2)
	AI:PushGoal("predator_seeking_enemies","backoff",0,3)
	AI:PushGoal("predator_seeking_enemies","timeout",1,0,2)
	AI:PushGoal("predator_seeking_enemies","not_shoot")
	AI:PushGoal("predator_seeking_enemies","locate",0,"hidepoint")
	AI:PushGoal("predator_seeking_enemies","acqtarget",1,"")
	AI:PushGoal("predator_seeking_enemies","timeout",1,.5,1)
	AI:PushGoal("predator_seeking_enemies","approach",1,10)
	-- AI:PushGoal("predator_seeking_enemies","devalue",0,1)
	AI:PushGoal("predator_seeking_enemies","timeout",1,0,1)
	AI:PushGoal("predator_seeking_enemies","lookat",1,-145,145)
	AI:PushGoal("predator_seeking_enemies","timeout",1,.5,1)
	AI:PushGoal("predator_seeking_enemies","locate",0,"hidepoint")
	AI:PushGoal("predator_seeking_enemies","acqtarget",1,"")
	-- AI:PushGoal("predator_seeking_enemies","devalue",0,1)
	AI:PushGoal("predator_seeking_enemies","timeout",1,0,2)
	AI:PushGoal("predator_seeking_enemies","locate",0,"hidepoint")
	AI:PushGoal("predator_seeking_enemies","acqtarget",1,"")
	-- AI:PushGoal("predator_seeking_enemies","devalue",0,1)
	AI:PushGoal("predator_seeking_enemies","timeout",1,0,2)
	AI:PushGoal("predator_seeking_enemies","locate",0,"hidepoint")
	AI:PushGoal("predator_seeking_enemies","acqtarget",1,"")
	AI:PushGoal("predator_seeking_enemies","timeout",1,.5,1)
	AI:PushGoal("predator_seeking_enemies","approach",1,6)
	AI:PushGoal("predator_seeking_enemies","timeout",1,.5,2)
	AI:PushGoal("predator_seeking_enemies","approach",1,12)
	-- AI:PushGoal("predator_seeking_enemies","devalue",0,1)
	AI:PushGoal("predator_seeking_enemies","lookat",1,-45,45)
	AI:PushGoal("predator_seeking_enemies","branch",1,-2)
	AI:PushGoal("predator_seeking_enemies","timeout",1,0,2)
	AI:PushGoal("predator_seeking_enemies","lookat",1,-90,90)
	AI:PushGoal("predator_seeking_enemies","timeout",1,1,2)
	AI:PushGoal("predator_seeking_enemies","signal",0,1,"CHECK_FOR_SELECT_IDLE",0)

	AI:CreateGoalPipe("predator_seeking_enemies2")
	AI:PushGoal("predator_seeking_enemies2","locate",0,"beacon")
	AI:PushGoal("predator_seeking_enemies2","acqtarget",1,"")
	AI:PushGoal("predator_seeking_enemies2","pathfind",1,"")
	AI:PushGoal("predator_seeking_enemies2","trace",1,1,0)
	AI:PushGoal("predator_seeking_enemies2","approach",1,0)
	AI:PushGoal("predator_seeking_enemies2","approach",1,3)
	AI:PushGoal("predator_seeking_enemies2","timeout",1,0,1)
	AI:PushGoal("predator_seeking_enemies2","backoff",0,6)
	AI:PushGoal("predator_seeking_enemies2","timeout",1,0,2)
	AI:PushGoal("predator_seeking_enemies2","lookat",1,-145,145)
	AI:PushGoal("predator_seeking_enemies2","timeout",1,0,2)
	AI:PushGoal("predator_seeking_enemies2","hide",1,30,HM_RANDOM)
	AI:PushGoal("predator_seeking_enemies2","lookat",1,-145,145)
	AI:PushGoal("predator_seeking_enemies2","hide",1,100,HM_RANDOM,1)
	AI:PushGoal("predator_seeking_enemies2","lookat",1,-145,145)
	AI:PushGoal("predator_seeking_enemies2","timeout",1,0,2)
	AI:PushGoal("predator_seeking_enemies2","locate",0,"hidepoint")
	AI:PushGoal("predator_seeking_enemies2","acqtarget",1,"")
	AI:PushGoal("predator_seeking_enemies2","signal",0,1,"CHECK_FOR_SELECT_IDLE",0)

	AI:CreateGoalPipe("predator_scared")
	AI:PushGoal("predator_scared","do_it_running")
	AI:PushGoal("predator_scared","locate",0,"beacon")
	AI:PushGoal("predator_scared","acqtarget",0,"")
	AI:PushGoal("predator_scared","timeout","timeout",1,0,1)
	AI:PushGoal("predator_scared","hide",1,30,HM_NEAREST,1)
	AI:PushGoal("predator_scared","timeout","timeout",1,1)
	AI:PushGoal("predator_scared","branch",0,-2)
	AI:PushGoal("predator_scared","hide",1,30,HM_FARTHEST_FROM_TARGET,1)
	AI:PushGoal("predator_scared","timeout","timeout",1,1)
	AI:PushGoal("predator_scared","signal",1,1,"MAKE_COMBAT_BREAK_ANIM",0)
	AI:PushGoal("predator_scared","timeout","timeout",1,1)
	AI:PushGoal("predator_scared","lookat",1,-145,145)
	AI:PushGoal("predator_scared","lookat",1,-90,90)
	AI:PushGoal("predator_scared","lookat",1,-145,145)
	AI:PushGoal("predator_scared","lookat",1,-90,90)
	AI:PushGoal("predator_scared","lookat",1,-180,180)
	AI:PushGoal("predator_scared","locate",0,"hidepoint")
	AI:PushGoal("predator_scared","acqtarget",1,"")
	AI:PushGoal("predator_scared","lookat",1,-145,145)
	AI:PushGoal("predator_scared","lookat",1,-90,90)
	AI:PushGoal("predator_scared","lookat",1,-145,145)
	AI:PushGoal("predator_scared","lookat",1,-90,90)
	AI:PushGoal("predator_scared","lookat",1,-180,180)
	AI:PushGoal("predator_scared","signal",0,1,"FIND_A_TARGET",0)

	AI:CreateGoalPipe("predator_scared_in_action")
	AI:PushGoal("predator_scared_in_action","do_it_running")
	AI:PushGoal("predator_scared_in_action","hide",1,60,HM_NEAREST,1)
	AI:PushGoal("predator_scared_in_action","timeout","timeout",1,1)
	AI:PushGoal("predator_scared_in_action","branch",0,-2)
	AI:PushGoal("predator_scared_in_action","hide",1,30,HM_FARTHEST_FROM_TARGET,1)
	AI:PushGoal("predator_scared_in_action","timeout","timeout",1,1)
	AI:PushGoal("predator_scared_in_action","signal",1,1,"MAKE_COMBAT_BREAK_ANIM",0)
	AI:PushGoal("predator_scared_in_action","timeout","timeout",1,1)
	AI:PushGoal("predator_scared_in_action","signal",0,1,"SWITCH_TO_ATTACK",0)

	AI:CreateGoalPipe("predator_avoiding_grenade")
	AI:PushGoal("predator_avoiding_grenade","setup_stand")
	AI:PushGoal("predator_avoiding_grenade","do_it_running")
	AI:PushGoal("predator_avoiding_grenade","backoff",1,9)
	AI:PushGoal("predator_avoiding_grenade","clear",0)
	AI:PushGoal("predator_avoiding_grenade","predator_is_invisible")
	AI:PushGoal("predator_avoiding_grenade","signal",0,1,"SWITCH_TO_ATTACK",0)

	AI:CreateGoalPipe("predator_idling")
	AI:PushGoal("predator_idling","predator_is_visible")
	AI:PushGoal("predator_idling","do_it_walking")
	AI:PushGoal("predator_idling","not_shoot")
	AI:PushGoal("predator_idling","locate",0,"hidepoint")
	AI:PushGoal("predator_idling","acqtarget",1,"")
	AI:PushGoal("predator_idling","timeout",1,.5,1)
	AI:PushGoal("predator_idling","approach",1,8)
	AI:PushGoal("predator_idling","timeout",1,.5,1)
	AI:PushGoal("predator_idling","lookat",1,-90,90)
	AI:PushGoal("predator_idling","branch",1,-1)
	AI:PushGoal("predator_idling","approach",1,4)
	AI:PushGoal("predator_idling","lookat",1,-45,45)
	AI:PushGoal("predator_idling","branch",1,-1)
	-- AI:PushGoal("predator_idling","pathfind",1,"")
	-- AI:PushGoal("predator_idling","trace",1,1,1)
	AI:PushGoal("predator_idling","devalue",0)
	AI:PushGoal("predator_idling","lookat",1,-45,45)
	AI:PushGoal("predator_idling","timeout",1,0,1)
	AI:PushGoal("predator_idling","lookat",1,-45,45)
	AI:PushGoal("predator_idling","signal",1,1,"DO_SOMETHING_IDLE",0)

	AI:CreateGoalPipe("predator_is_invisible")
	AI:PushGoal("predator_is_invisible","signal",1,1,"GO_REFRACTIVE",0)

	AI:CreateGoalPipe("predator_is_visible")
	AI:PushGoal("predator_is_visible","signal",1,1,"GO_VISIBLE",0)

	AI:CreateGoalPipe("brief_invisibility")
	AI:PushGoal("brief_invisibility","signal",1,1,"GO_REFRACTIVE",0)
	AI:PushGoal("brief_invisibility","timeout",1,0,1.5)
	AI:PushGoal("brief_invisibility","signal",1,1,"GO_VISIBLE",0)

--
-----------------
--	Mutant rear
-----------------
--

	AI:CreateGoalPipe("mutant_refract_sneak")
	AI:PushGoal("mutant_refract_sneak","signal",1,1,"GO_REFRACTIVE",0)
	AI:PushGoal("mutant_refract_sneak","take_cover")
	AI:PushGoal("mutant_refract_sneak","do_it_running")
	AI:PushGoal("mutant_refract_sneak","hide",1,10,HM_NEAREST_TO_TARGET)
	AI:PushGoal("mutant_refract_sneak","branch",0,-1,1)
	AI:PushGoal("mutant_refract_sneak","signal",1,1,"GO_VISIBLE",0)
	AI:PushGoal("mutant_refract_sneak","clear",0)

	AI:CreateGoalPipe("mutant_refract_retreat")
	AI:PushGoal("mutant_refract_retreat","signal",1,1,"GO_REFRACTIVE",0)
	AI:PushGoal("mutant_refract_retreat","take_cover")
	AI:PushGoal("mutant_refract_retreat","hide",1,10,HM_FARTHEST_FROM_TARGET,1)
	AI:PushGoal("mutant_refract_retreat","timeout",1,0,2)
	AI:PushGoal("mutant_refract_retreat","signal",1,1,"GO_VISIBLE",0)
	AI:PushGoal("mutant_refract_retreat","clear",0)

	AI:CreateGoalPipe("mutant_monkey_attack")
	AI:PushGoal("mutant_monkey_attack","signal",1,1,"GO_REFRACTIVE",0)
	AI:PushGoal("mutant_monkey_attack","mutant_call_monkeys")
	AI:PushGoal("mutant_monkey_attack","just_shoot")
	AI:PushGoal("mutant_monkey_attack","shoot_cover")
	AI:PushGoal("mutant_monkey_attack","do_it_running")
	AI:PushGoal("mutant_monkey_attack","timeout",1,3,6)
	AI:PushGoal("mutant_monkey_attack","mutant_unleash_monkeys")
	AI:PushGoal("mutant_monkey_attack","signal",1,1,"GO_VISIBLE",0)
	AI:PushGoal("mutant_monkey_attack","not_shoot")
	AI:PushGoal("mutant_monkey_attack","hide",1,10,HM_FRONTLEFTMOST_FROM_TARGET)
	AI:PushGoal("mutant_monkey_attack","hide",1,10,HM_NEAREST_TO_TARGET)
	AI:PushGoal("mutant_monkey_attack","just_shoot")
	AI:PushGoal("mutant_monkey_attack","hide",1,10,HM_FRONTLEFTMOST_FROM_TARGET)
	AI:PushGoal("mutant_monkey_attack","hide",1,10,HM_NEAREST_TO_TARGET)
	AI:PushGoal("mutant_monkey_attack","clear",0)

	AI:CreateGoalPipe("mutant_call_monkeys")
	AI:PushGoal("mutant_call_monkeys","form",1,"mutant_form")
	AI:PushGoal("mutant_call_monkeys","signal",1,-1,"WakeUp",SIGNALFILTER_SUPERGROUP)
	AI:PushGoal("mutant_call_monkeys","signal",1,-1,"WakeUp2",SIGNALFILTER_SUPERGROUP)
	AI:PushGoal("mutant_call_monkeys","signal",1,1,"COME_TO_ME",SIGNALFILTER_SUPERGROUP)

	AI:CreateGoalPipe("mutant_unleash_monkeys")
	AI:PushGoal("mutant_unleash_monkeys","form",1,"")
	AI:PushGoal("mutant_unleash_monkeys","form",1,"beacon")
	AI:PushGoal("mutant_unleash_monkeys","signal",1,1,"ATTACK_BEACON",SIGNALFILTER_SUPERGROUP)

	AI:CreateGoalPipe("mutant_refract_attack")
	AI:PushGoal("mutant_refract_attack","not_shoot")
	AI:PushGoal("mutant_refract_attack","signal",1,1,"GO_REFRACTIVE",0)
	AI:PushGoal("mutant_refract_attack","take_cover")
	AI:PushGoal("mutant_refract_attack","do_it_running")
	AI:PushGoal("mutant_refract_attack","signal",1,1,"GO_VISIBLE",0)
	AI:PushGoal("mutant_refract_attack","just_shoot")
	AI:PushGoal("mutant_refract_attack","approach",1,3)
	AI:PushGoal("mutant_refract_attack","clear",0)

	AI:CreateGoalPipe("mutant_advance_one_cover")
	AI:PushGoal("mutant_advance_one_cover","strafe",0,0)
	AI:PushGoal("mutant_advance_one_cover","hide",1,10,HM_NEAREST_TO_TARGET,1,1)
	AI:PushGoal("mutant_advance_one_cover","branch",1,-1,1)

	AI:CreateGoalPipe("monkey_attack_beacon")
	AI:PushGoal("monkey_attack_beacon","locate",0,"beacon")
	AI:PushGoal("monkey_attack_beacon","acqtarget",0,"")
	AI:PushGoal("monkey_attack_beacon","do_it_running")
	AI:PushGoal("monkey_attack_beacon","approach",1,1)
	AI:PushGoal("monkey_attack_beacon","clear",0)

	AI:CreateGoalPipe("monkey_form")
	AI:PushGoal("monkey_form","locate",0,"formation")
	AI:PushGoal("monkey_form","ignoreall",0,1)
	AI:PushGoal("monkey_form","acqtarget",0,"")
	AI:PushGoal("monkey_form","do_it_running")
	AI:PushGoal("monkey_form","approach",1,1)

----------------------------------------

	AI:CreateGoalPipe("bust_lock_at")
	-- AI:PushGoal("bust_lock_at","timeout",1,.1) -- Чтобы не глючила анимация.
	AI:PushGoal("bust_lock_at","timeout",1,1,2)
	AI:PushGoal("bust_lock_at","ignoreall",0,1) -- Попробовать как-нибудь убрать игнорирование у мутантов, разбив материалы клеток и стекла на два разных.
	AI:PushGoal("bust_lock_at","acqtarget",0,"")
	AI:PushGoal("bust_lock_at","do_it_running")
	AI:PushGoal("bust_lock_at","approach",1,1,1)
	AI:PushGoal("bust_lock_at","ignoreall",0,0)
	AI:PushGoal("bust_lock_at","signal",1,1,"RELEASED",SIGNALFILTER_ANYONEINCOMM)
	AI:PushGoal("bust_lock_at","signal","clear")
	AI:PushGoal("bust_lock_at","signal",1,1,"FIND_A_TARGET",0)

	AI:CreateGoalPipe("mutant_caged_idle")
	AI:PushGoal("mutant_caged_idle","devalue",0)
	AI:PushGoal("mutant_caged_idle","signal",1,1,"MUTANT_RELAXED_ANIM",0)
	AI:PushGoal("mutant_caged_idle","lookat",1,-30,30)
--	AI:PushGoal("mutant_caged_idle","timeout",1,0,1)

	AI:CreateGoalPipe("mutant_caged_upset")
	AI:PushGoal("mutant_caged_upset","signal",1,1,"MUTANT_UPSET_ANIM",0)
	AI:PushGoal("mutant_caged_upset","timeout",1,0,.7)

	AI:CreateGoalPipe("wait_state")
	AI:PushGoal("wait_state","ignoreall",1,0)
	AI:PushGoal("wait_state","signal",1,1,"STILL_WAITING",0)
	AI:PushGoal("wait_state","timeout",1,.5)
	AI:PushGoal("wait_state","ignoreall",1,1)

	AI:CreateGoalPipe("waiting...")
	AI:PushGoal("waiting...","timeout",1,1)

	--------------------------------
	-- NEW MUTANT SCREWED
	--------------------------------

	AI:CreateGoalPipe("mutant_shared_bellowhowl")
	AI:PushGoal("mutant_shared_bellowhowl","not_shoot")
	AI:PushGoal("mutant_shared_bellowhowl","signal",1,1,"MAKE_BELLOW_HOWL_ANIMATION",0)
	AI:PushGoal("mutant_shared_bellowhowl","timeout",1,.2)

	AI:CreateGoalPipe("mutant_shared_bellowhowl2")
	AI:PushGoal("mutant_shared_bellowhowl2","mutant_shared_bellowhowl")
	AI:PushGoal("mutant_shared_bellowhowl2","big_shoot")

	AI:CreateGoalPipe("mutant_run_to_target")
	AI:PushGoal("mutant_run_to_target","setup_stand")
	AI:PushGoal("mutant_run_to_target","do_it_running")
--	AI:PushGoal("mutant_run_to_target","approach",1,3)
	AI:PushGoal("mutant_run_to_target","locate",0,"beacon") -- По маяку лучше, а то если бросить гранату, то почему-то после идёт спиной к врагу.
	AI:PushGoal("mutant_run_to_target","acqtarget",1,"")
	-- AI:PushGoal("mutant_run_to_target","locate",1,"atttarget")
	-- AI:PushGoal("mutant_run_to_target","pathfind",1,"")
	AI:PushGoal("mutant_run_to_target","trace",1,1)
	AI:PushGoal("mutant_run_to_target","do_it_walking")
	AI:PushGoal("mutant_run_to_target","signal",0,1,"CHECK_FOR_FIND_A_TARGET",0)

	AI:CreateGoalPipe("mutant_walk_to_beacon")
	AI:PushGoal("mutant_walk_to_beacon","locate",0,"beacon")
	AI:PushGoal("mutant_walk_to_beacon","acqtarget",0,"")
	AI:PushGoal("mutant_walk_to_beacon","mutant_walk_to_target")

	AI:CreateGoalPipe("mutant_run_to_beacon")
	AI:PushGoal("mutant_run_to_beacon","locate",0,"beacon")
	AI:PushGoal("mutant_run_to_beacon","acqtarget",0,"")
	AI:PushGoal("mutant_run_to_beacon","mutant_run_to_target")

	AI:CreateGoalPipe("mutant_run_towards_target")
	AI:PushGoal("mutant_run_towards_target","do_it_running")
	AI:PushGoal("mutant_run_towards_target","approach",1,.5)
	AI:PushGoal("mutant_run_towards_target","do_it_walking")
	
	AI:CreateGoalPipe("mutant_run_towards_target2")
	AI:PushGoal("mutant_run_towards_target2","timeout",1,.5,2)
	AI:PushGoal("mutant_run_towards_target2","do_it_running")
	AI:PushGoal("mutant_run_towards_target2","approach",1,.5)
	AI:PushGoal("mutant_run_towards_target2","do_it_walking")
	AI:PushGoal("mutant_run_towards_target2","timeout",1,1,3)

	AI:CreateGoalPipe("mutant_walk_to_target")
	AI:PushGoal("mutant_walk_to_target","not_shoot")
	AI:PushGoal("mutant_walk_to_target","do_it_walking")
	AI:PushGoal("mutant_walk_to_target","approach",1,2)
	AI:PushGoal("mutant_walk_to_target","just_shoot")
	
	AI:CreateGoalPipe("mutant_walk_to_target2")
	AI:PushGoal("mutant_walk_to_target2","timeout",1,.5,2)
	AI:PushGoal("mutant_walk_to_target2","not_shoot")
	AI:PushGoal("mutant_walk_to_target2","do_it_walking")
	AI:PushGoal("mutant_walk_to_target2","approach",1,2)
	AI:PushGoal("mutant_walk_to_target2","just_shoot")
	AI:PushGoal("mutant_walk_to_target2","timeout",1,1,3)

	AI:CreateGoalPipe("mutant_screwed_attack")
	AI:PushGoal("mutant_screwed_attack","mutant_run_to_target")
--	AI:PushGoal("mutant_screwed_attack","timeout",1,0,.5)

	AI:CreateGoalPipe("mutant_push_stuff_at")
	AI:PushGoal("mutant_push_stuff_at","do_it_running")
	AI:PushGoal("mutant_push_stuff_at","ignoreall",0,1)
	AI:PushGoal("mutant_push_stuff_at","acqtarget",0,"")
	AI:PushGoal("mutant_push_stuff_at","approach",1,2)
	AI:PushGoal("mutant_push_stuff_at","signal",1,1,"APPLY_IMPULSE_TO_ENVIRONMENT",0)
	AI:PushGoal("mutant_push_stuff_at","ignoreall",0,0)

	AI:CreateGoalPipe("jump_wrapper")
	AI:PushGoal("jump_wrapper","not_shoot")
	AI:PushGoal("jump_wrapper","just_shoot")
	AI:PushGoal("jump_wrapper","signal",1,1,"JUMP_FINISHED",0)

	-----------------------------------
	-- NEW MUTANT SCOUT
	-----------------------------------

	AI:CreateGoalPipe("jump_left_hide")
	AI:PushGoal("jump_left_hide","not_shoot")
	AI:PushGoal("jump_left_hide","jump",1,20,HM_LEFTMOST_FROM_TARGET,1)	-- calculate jump only DONT ACTUALLY JUMP
	AI:PushGoal("jump_left_hide","signal",1,1,"START_DESIRED_ANIMATION",0)
	AI:PushGoal("jump_left_hide","signal",1,1,"SET_CORRECT_ANIMATION_SCALE",0)
	AI:PushGoal("jump_left_hide","jump",1,20,HM_LEFTMOST_FROM_TARGET)	-- actual jump executed here
	AI:PushGoal("jump_left_hide","signal",1,1,"RESET_JUMP_VARIABLES",0)

	AI:CreateGoalPipe("jump_right_hide")
	AI:PushGoal("jump_right_hide","not_shoot")
	AI:PushGoal("jump_right_hide","jump",1,20,HM_RIGHTMOST_FROM_TARGET,1)	-- calculate jump only DONT ACTUALLY JUMP
	AI:PushGoal("jump_right_hide","signal",1,1,"START_DESIRED_ANIMATION",0)
	AI:PushGoal("jump_right_hide","signal",1,1,"SET_CORRECT_ANIMATION_SCALE",0)
	AI:PushGoal("jump_right_hide","jump",1,20,HM_RIGHTMOST_FROM_TARGET)	-- actual jump executed here
	AI:PushGoal("jump_right_hide","signal",1,1,"RESET_JUMP_VARIABLES",0)

	AI:CreateGoalPipe("fast_shoot")
	AI:PushGoal("fast_shoot","setup_stand")
	AI:PushGoal("fast_shoot","not_shoot")
	AI:PushGoal("fast_shoot","just_shoot")
	AI:PushGoal("fast_shoot","do_it_running")
	AI:PushGoal("fast_shoot","timeout",1,3,60)
	AI:PushGoal("fast_shoot","signal",0,1,"CHECK_FOR_FIND_A_TARGET",0)
	AI:PushGoal("fast_shoot","signal",0,1,"JUMP_ON_ANCHOR",0)

	AI:CreateGoalPipe("fast_investigate")
	AI:PushGoal("fast_investigate","mutant_walk_to_target")

	AI:CreateGoalPipe("fast_shoot_approach")
	AI:PushGoal("fast_shoot_approach","bodypos",0,BODYPOS_COMBAT)
	AI:PushGoal("fast_shoot_approach","not_shoot")
	AI:PushGoal("fast_shoot_approach","just_shoot")
	AI:PushGoal("fast_shoot_approach","approach",1,.5)
	AI:PushGoal("fast_shoot_approach","signal",0,1,"CHECK_FOR_FIND_A_TARGET",0)

	AI:CreateGoalPipe("fast_alert_shoot_approach")
	AI:PushGoal("fast_alert_shoot_approach","bodypos",0,BODYPOS_COMBAT)
	AI:PushGoal("fast_alert_shoot_approach","do_it_walking")
	AI:PushGoal("fast_alert_shoot_approach","not_shoot")
	AI:PushGoal("fast_alert_shoot_approach","just_shoot")
	AI:PushGoal("fast_alert_shoot_approach","approach",0,.9)
	AI:PushGoal("fast_alert_shoot_approach","trace",1,0,1)
	AI:PushGoal("fast_alert_shoot_approach","signal",0,1,"FIND_A_TARGET",0)

	AI:CreateGoalPipe("fast_walk_to_target")
	AI:PushGoal("fast_walk_to_target","bodypos",0,BODYPOS_COMBAT)
	AI:PushGoal("fast_walk_to_target","not_shoot")
	AI:PushGoal("fast_walk_to_target","do_it_walking")
	AI:PushGoal("fast_walk_to_target","locate",1,"atttarget")
	AI:PushGoal("fast_walk_to_target","pathfind",1,"")
	AI:PushGoal("fast_walk_to_target","trace",1,1)
	AI:PushGoal("fast_walk_to_target","signal",0,1,"FIND_A_TARGET",0)

	AI:CreateGoalPipe("fast_run_to_target")
	AI:PushGoal("fast_run_to_target","bodypos",0,BODYPOS_COMBAT)
	AI:PushGoal("fast_run_to_target","not_shoot")
	AI:PushGoal("fast_run_to_target","do_it_running")
	AI:PushGoal("fast_run_to_target","locate",1,"atttarget")
	AI:PushGoal("fast_run_to_target","pathfind",1,"")
	AI:PushGoal("fast_run_to_target","trace",1,1)
	AI:PushGoal("fast_run_to_target","signal",0,1,"FIND_A_TARGET",0)

	AI:CreateGoalPipe("fast_run_to_beacon")
	AI:PushGoal("fast_run_to_beacon","bodypos",0,BODYPOS_COMBAT)
	AI:PushGoal("fast_run_to_beacon","locate",0,"beacon")
	AI:PushGoal("fast_run_to_beacon","acqtarget",0,"")
	AI:PushGoal("fast_run_to_beacon","fast_run_to_target")

	AI:CreateGoalPipe("krieger_fast_shoot")
	AI:PushGoal("krieger_fast_shoot","setup_stand")
	AI:PushGoal("krieger_fast_shoot","do_it_running")
	AI:PushGoal("krieger_fast_shoot","just_shoot")
	AI:PushGoal("krieger_fast_shoot","timeout",1,1,2)
	AI:PushGoal("krieger_fast_shoot","signal",1,1,"CHANGE_POSITION",0)

	AI:CreateGoalPipe("fast_idling")
	AI:PushGoal("fast_idling","setup_relax")
	AI:PushGoal("fast_idling","do_it_walking")
	AI:PushGoal("fast_idling","not_shoot")
	AI:PushGoal("fast_idling","not_shoot")
	AI:PushGoal("fast_idling","locate",0,"hidepoint")
	AI:PushGoal("fast_idling","acqtarget",0,"")
	AI:PushGoal("fast_idling","approach",1,.4)
	AI:PushGoal("fast_idling","devalue",0)
	AI:PushGoal("fast_idling","lookat",1,-45,45)
	AI:PushGoal("fast_idling","timeout",1,0,1)
	AI:PushGoal("fast_idling","lookat",1,-45,45)
	AI:PushGoal("fast_idling","signal",1,1,"DO_SOMETHING_IDLE",0)

	AI:CreateGoalPipe("fast_idling_stand")
	AI:PushGoal("fast_idling_stand","setup_relax")
	AI:PushGoal("fast_idling_stand","not_shoot")
	AI:PushGoal("fast_idling_stand","not_shoot")
	AI:PushGoal("fast_idling_stand","locate",0,"hidepoint")
	AI:PushGoal("fast_idling_stand","acqtarget",0,"")
	-- AI:PushGoal("fast_idling_stand","approach",1,.4)
	AI:PushGoal("fast_idling_stand","devalue",0)
	AI:PushGoal("fast_idling_stand","lookat",1,-45,45)
	AI:PushGoal("fast_idling_stand","timeout",1,0,1)
	AI:PushGoal("fast_idling_stand","lookat",1,-45,45)
	AI:PushGoal("fast_idling_stand","signal",0,1,"DO_SOMETHING_IDLE",0)

	AI:CreateGoalPipe("fast_invisible_attack_left")
	AI:PushGoal("fast_invisible_attack_left","not_shoot")
	AI:PushGoal("fast_invisible_attack_left","do_it_running")
	AI:PushGoal("fast_invisible_attack_left","hide",1,20,HM_LEFTMOST_FROM_TARGET)
	AI:PushGoal("fast_invisible_attack_left","hide",1,20,HM_LEFTMOST_FROM_TARGET)
	AI:PushGoal("fast_invisible_attack_left","approach",1,2)
	AI:PushGoal("fast_invisible_attack_left","just_shoot")
	AI:PushGoal("fast_invisible_attack_left","do_it_walking")

	AI:CreateGoalPipe("fast_invisible_attack_right")
	AI:PushGoal("fast_invisible_attack_right","not_shoot")
	AI:PushGoal("fast_invisible_attack_right","do_it_running")
	AI:PushGoal("fast_invisible_attack_right","hide",1,20,HM_RIGHTMOST_FROM_TARGET)
	AI:PushGoal("fast_invisible_attack_right","hide",1,20,HM_RIGHTMOST_FROM_TARGET)
	AI:PushGoal("fast_invisible_attack_right","approach",1,2)
	AI:PushGoal("fast_invisible_attack_right","just_shoot")
	AI:PushGoal("fast_invisible_attack_right","do_it_walking")

	AI:CreateGoalPipe("fast_hide")
	AI:PushGoal("fast_hide","just_shoot")
	AI:PushGoal("fast_hide","do_it_running")
	AI:PushGoal("fast_hide","hide",1,20,HM_NEAREST)
	AI:PushGoal("fast_hide","signal",1,1,"SWITCH_TO_SHOOT",0)

	AI:CreateGoalPipe("fast_hide2")
	AI:PushGoal("fast_hide2","just_shoot")
	AI:PushGoal("fast_hide2","do_it_running")
	AI:PushGoal("fast_hide2","hide",1,20,HM_NEAREST)
	AI:PushGoal("fast_hide2","signal",1,1,"JUMP_ON_ANCHOR",0)

	AI:CreateGoalPipe("fast_look_around")
	AI:PushGoal("fast_look_around","setup_stand")
	AI:PushGoal("fast_look_around","just_shoot")
	AI:PushGoal("fast_look_around","locate",0,"beacon")
	AI:PushGoal("fast_look_around","acqtarget",0,"")
	AI:PushGoal("fast_look_around","timeout",1,0,1)
	AI:PushGoal("fast_look_around","lookat",1,-180,180)
	AI:PushGoal("fast_look_around","timeout",1,0,1)
	AI:PushGoal("fast_look_around","locate",0,"hidepoint")
	AI:PushGoal("fast_look_around","acqtarget",0,"")
	AI:PushGoal("fast_look_around","timeout",1,0,1)
	AI:PushGoal("fast_look_around","look_behind")
	AI:PushGoal("fast_look_around","signal",0,1,"CHECK_FOR_SELECT_IDLE",0)

	AI:CreateGoalPipe("fast_alert_look_around")
	AI:PushGoal("fast_alert_look_around","fast_look_around")
	AI:PushGoal("fast_alert_look_around","signal",0,1,"CHECK_FOR_FIND_A_TARGET",0)
	AI:PushGoal("fast_alert_look_around","signal",1,1,"JUMP_ON_ANCHOR",0)

	AI:CreateGoalPipe("on_damage_scared")
	AI:PushGoal("on_damage_scared","setup_stand")
	AI:PushGoal("on_damage_scared","do_it_running")
	AI:PushGoal("on_damage_scared","just_shoot")
	AI:PushGoal("on_damage_scared","locate",0,"beacon")
	AI:PushGoal("on_damage_scared","acqtarget",1,"")
	AI:PushGoal("on_damage_scared","timeout",1,1,3)
	AI:PushGoal("on_damage_scared","hide",1,60,HM_NEAREST,1)
	AI:PushGoal("on_damage_scared","signal",1,1,"JUMP_ON_ANCHOR",0)
	AI:PushGoal("on_damage_scared","signal",0,1,"FIND_A_TARGET",0)

	AI:CreateGoalPipe("fast_seeking_enemies")
	-- AI:PushGoal("fast_seeking_enemies","DropBeaconAt",0)
	AI:PushGoal("fast_seeking_enemies","just_shoot")
	AI:PushGoal("fast_seeking_enemies","bodypos",0,BODYPOS_COMBAT)
	AI:PushGoal("fast_seeking_enemies","locate",0,"beacon")
	AI:PushGoal("fast_seeking_enemies","acqtarget",0,"")
	AI:PushGoal("fast_seeking_enemies","do_it_running")
	AI:PushGoal("fast_seeking_enemies","approach",1,.5)
	-- AI:PushGoal("fast_seeking_enemies","trace",1,1)
	AI:PushGoal("fast_seeking_enemies","locate",0,"beacon")
	AI:PushGoal("fast_seeking_enemies","acqtarget",0,"")
	AI:PushGoal("fast_seeking_enemies","pathfind",1,"")
	AI:PushGoal("fast_seeking_enemies","trace",1,1)
	-- AI:PushGoal("fast_seeking_enemies","signal",1,1,"JUMP_ON_ANCHOR",0)
	-- AI:PushGoal("fast_seeking_enemies","bodypos",0,BODYPOS_COMBAT)
	AI:PushGoal("fast_seeking_enemies","locate",0,"beacon")
	AI:PushGoal("fast_seeking_enemies","acqtarget",0,"")
	AI:PushGoal("fast_seeking_enemies","hide",1,30,HM_NEAREST)
	AI:PushGoal("fast_seeking_enemies","timeout",1,.5)
	AI:PushGoal("fast_seeking_enemies","timeout",1,.5)
	AI:PushGoal("fast_seeking_enemies","branch",0,-4)
	AI:PushGoal("fast_seeking_enemies","timeout",1,.5)
	AI:PushGoal("fast_seeking_enemies","timeout",1,.5)
	AI:PushGoal("fast_seeking_enemies","lookat",1,-145,145)
	AI:PushGoal("fast_seeking_enemies","lookat",1,-90,90)
	AI:PushGoal("fast_seeking_enemies","lookat",1,-145,145)
	AI:PushGoal("fast_seeking_enemies","timeout",1,1)
	AI:PushGoal("fast_seeking_enemies","lookat",1,-180,180)
	AI:PushGoal("fast_seeking_enemies","look_behind")
	AI:PushGoal("fast_seeking_enemies","locate",0,"hidepoint")
	AI:PushGoal("fast_seeking_enemies","acqtarget",0,"")
	AI:PushGoal("fast_seeking_enemies","lookat",1,-90,90)
	AI:PushGoal("fast_seeking_enemies","lookat",1,-90,90)
	AI:PushGoal("fast_seeking_enemies","lookat",1,-145,145)
	AI:PushGoal("fast_seeking_enemies","timeout",1,2)
	AI:PushGoal("fast_seeking_enemies","look_behind")
	AI:PushGoal("fast_seeking_enemies","hide",1,50,HM_FARTHEST_FROM_TARGET)
	AI:PushGoal("fast_seeking_enemies","signal",0,1,"CHECK_FOR_SELECT_IDLE",0)
	-- AI:PushGoal("fast_seeking_enemies","signal",1,1,"JUMP_ON_ANCHOR",0)
	-- AI:PushGoal("fast_seeking_enemies","devalue_target",0)

	AI:CreateGoalPipe("fast_scared_approaching")
	AI:PushGoal("fast_scared_approaching","bodypos",0,BODYPOS_COMBAT)
	AI:PushGoal("fast_scared_approaching","lookat",0,-145,145)
	AI:PushGoal("fast_scared_approaching","timeout",1,1)
	AI:PushGoal("fast_scared_approaching","lookat",0,-90,90)
	AI:PushGoal("fast_scared_approaching","timeout",1,1)
	AI:PushGoal("fast_scared_approaching","lookat",0,-145,145)
	AI:PushGoal("fast_scared_approaching","timeout",1,1)
	AI:PushGoal("fast_scared_approaching","lookat",0,-90,90)
	AI:PushGoal("fast_scared_approaching","timeout",1,1)
	AI:PushGoal("fast_scared_approaching","locate",0,"hidepoint")
	AI:PushGoal("fast_scared_approaching","acqtarget",1,"")
	AI:PushGoal("fast_scared_approaching","timeout",1,0,1)
	AI:PushGoal("fast_scared_approaching","hide",1,15,HM_NEAREST,0)
	AI:PushGoal("fast_scared_approaching","hide",1,60,HM_NEAREST,1)
	AI:PushGoal("fast_scared_approaching","signal",1,1,"MAKE_COMBAT_BREAK_ANIM",0)
	AI:PushGoal("fast_scared_approaching","timeout",1,0,1)
	AI:PushGoal("fast_scared_approaching","look_behind")
	AI:PushGoal("fast_scared_approaching","locate",0,"hidepoint")
	AI:PushGoal("fast_scared_approaching","acqtarget",1,"")
	AI:PushGoal("fast_scared_approaching","timeout",1,0,1)
	AI:PushGoal("fast_scared_approaching","signal",0,1,"CHECK_FOR_FIND_A_TARGET",0)
	AI:PushGoal("fast_scared_approaching","signal",1,1,"JUMP_ON_ANCHOR",0)

	AI:CreateGoalPipe("krieger_fast_hide")
	AI:PushGoal("krieger_fast_hide","just_shoot")
	AI:PushGoal("krieger_fast_hide","do_it_running")
	AI:PushGoal("krieger_fast_hide","signal",1,1,"SELECT_HIDE_METHOD",0)
	AI:PushGoal("krieger_fast_hide","signal",1,1,"SWITCH_TO_SHOOT",0)

	AI:CreateGoalPipe("krieger_hide_left")
	AI:PushGoal("krieger_hide_left","hide",1,30,HM_LEFTMOST_FROM_TARGET)

	AI:CreateGoalPipe("krieger_hide_right")
	AI:PushGoal("krieger_hide_right","hide",1,30,HM_RIGHTMOST_FROM_TARGET)


	---------------------------------------
	-- NEW MUTANT COVER
	---------------------------------------

	AI:CreateGoalPipe("big_shoot")
	AI:PushGoal("big_shoot","not_shoot")
	AI:PushGoal("big_shoot","signal",1,1,"SHOOT_TYPE",0)

	AI:CreateGoalPipe("big_single_shoot")
	AI:PushGoal("big_single_shoot","not_shoot")
	AI:PushGoal("big_single_shoot","signal",1,1,"PLAY_SHOOT_ANIMATION",0)
	AI:PushGoal("big_single_shoot","signal",1,1,"RUN_TO_TARGET",0)

	AI:CreateGoalPipe("big_auto_shoot")
	AI:PushGoal("big_auto_shoot","just_shoot")
	AI:PushGoal("big_auto_shoot","timeout",1,0,10)
	AI:PushGoal("big_auto_shoot","not_shoot")
	AI:PushGoal("big_auto_shoot","signal",1,1,"RUN_TO_TARGET",0)

	AI:CreateGoalPipe("big_new_shoot")
	AI:PushGoal("big_new_shoot","timeout",1,.5,1)
	AI:PushGoal("big_new_shoot","just_shoot")
	AI:PushGoal("big_new_shoot","timeout",1,1,2)
	AI:PushGoal("big_new_shoot","not_shoot")

	AI:CreateGoalPipe("big_pindown")
	AI:PushGoal("big_pindown","setup_stand")
	AI:PushGoal("big_pindown","do_it_running")
	--AI:PushGoal("big_pindown","hide",1,15,HM_NEAREST_TO_TARGET,0)
	AI:PushGoal("big_pindown","signal",1,1,"SELECT_LEFT_RIGHT_COMEOUT",0)

	AI:CreateGoalPipe("big_roam")
	AI:PushGoal("big_roam","do_it_walking")
	AI:PushGoal("big_roam","locate",0,"hidepoint")
	AI:PushGoal("big_roam","pathfind",1,"")
	AI:PushGoal("big_roam","trace",1,1)
	AI:PushGoal("big_roam","lookat",1,-45,45)
	AI:PushGoal("big_roam","timeout",1,1,2)
	AI:PushGoal("big_roam","lookat",1,-45,45)
	AI:PushGoal("big_roam","timeout",1,1,2)

	AI:CreateGoalPipe("big_comeout_left")
	AI:PushGoal("big_comeout_left","strafe",1,-3)
	AI:PushGoal("big_comeout_left","clear",0)

	AI:CreateGoalPipe("big_comeout_right")
	AI:PushGoal("big_comeout_right","strafe",1,3)
	AI:PushGoal("big_comeout_right","clear",0)

	AI:CreateGoalPipe("big_run_to_beacon")
	AI:PushGoal("big_run_to_beacon","locate",0,"beacon")
	AI:PushGoal("big_run_to_beacon","acqtarget",0,"")
	AI:PushGoal("big_run_to_beacon","big_run_to_target")

	AI:CreateGoalPipe("big_run_to_target")
	AI:PushGoal("big_run_to_target","setup_stand")
	AI:PushGoal("big_run_to_target","do_it_running")
	AI:PushGoal("big_run_to_target","approach",0,2)
	AI:PushGoal("big_run_to_target","timeout",1,1) --
	AI:PushGoal("big_run_to_target","signal",1,1,"DECIDE_TO_SHOOT_OR_NOT",0)
--	AI:PushGoal("big_run_to_target","timeout",1,1,2)
	AI:PushGoal("big_run_to_target","branch",1,-1)
	AI:PushGoal("big_run_to_target","do_it_walking")
	AI:PushGoal("big_run_to_target","signal",0,1,"THREATEN",SIGNALID_READIBILITY)
	--------------------------------------------------------------


	---------------------------------------
	-- NEW MUTANT STEALTH
	---------------------------------------

	AI:CreateGoalPipe("stealth_investigate")
	AI:PushGoal("stealth_investigate","setup_stand")
	AI:PushGoal("stealth_investigate","approach",1,.6)
	AI:PushGoal("stealth_investigate","lookat",1,-45,45)
	AI:PushGoal("stealth_investigate","lookat",1,-45,45)
	AI:PushGoal("stealth_investigate","signal",1,1,"DECIDE_IF_INVESTIGATING_MORE",0)

	AI:CreateGoalPipe("stealth_hunt")
	AI:PushGoal("stealth_hunt","locate",0,"beacon")
	AI:PushGoal("stealth_hunt","acqtarget",0,"")
	AI:PushGoal("stealth_hunt","do_it_running")
	AI:PushGoal("stealth_hunt","signal",1,1,"GO_REFRACTIVE",0)
	AI:PushGoal("stealth_hunt","hide",1,20,HM_NEAREST)
	AI:PushGoal("stealth_hunt","do_it_walking")
	AI:PushGoal("stealth_hunt","setup_stealth")
	AI:PushGoal("stealth_hunt","timeout",1,0,1)
	AI:PushGoal("stealth_hunt","hide",1,20,HM_FRONTLEFTMOST_FROM_TARGET,1)
	AI:PushGoal("stealth_hunt","timeout",1,0,1)
	AI:PushGoal("stealth_hunt","hide",1,20,HM_NEAREST_TO_TARGET,1)
	AI:PushGoal("stealth_hunt","timeout",1,0,1)
	AI:PushGoal("stealth_hunt","hide",1,20,HM_FRONTLEFTMOST_FROM_TARGET,1)
	AI:PushGoal("stealth_hunt","timeout",1,0,1)
	AI:PushGoal("stealth_hunt","hide",1,20,HM_NEAREST_TO_TARGET,1)
	AI:PushGoal("stealth_hunt","timeout",1,0,1)
	AI:PushGoal("stealth_hunt","approach",1,2)
	AI:PushGoal("stealth_hunt","signal",1,1,"GO_VISIBLE",0)
	AI:PushGoal("stealth_hunt","signal",1,1,"RETURN_TO_FIRST",0)

	AI:CreateGoalPipe("stealth_normal_attack")
	AI:PushGoal("stealth_normal_attack","signal",1,1,"GO_VISIBLE",0) -- just in case
	AI:PushGoal("stealth_normal_attack","setup_stand")
	AI:PushGoal("stealth_normal_attack","do_it_running")
	AI:PushGoal("stealth_normal_attack","just_shoot")
	AI:PushGoal("stealth_normal_attack","hide",1,20,HM_FRONTLEFTMOST_FROM_TARGET)
	AI:PushGoal("stealth_normal_attack","hide",1,20,HM_FRONTRIGHTMOST_FROM_TARGET)

	AI:CreateGoalPipe("stealth_sneakup_left")
	AI:PushGoal("stealth_sneakup_left","signal",1,1,"GO_REFRACTIVE",0)
	AI:PushGoal("stealth_sneakup_left","not_shoot")
	AI:PushGoal("stealth_sneakup_left","setup_stand")
	AI:PushGoal("stealth_sneakup_left","do_it_running")
	AI:PushGoal("stealth_sneakup_left","hide",1,20,HM_FRONTLEFTMOST_FROM_TARGET)
	AI:PushGoal("stealth_sneakup_left","timeout",1,.5,1.5)
	AI:PushGoal("stealth_sneakup_left","hide",1,20,HM_NEAREST_TO_TARGET)
	AI:PushGoal("stealth_sneakup_left","timeout",1,.5,1.5)
	AI:PushGoal("stealth_sneakup_left","hide",1,20,HM_FRONTLEFTMOST_FROM_TARGET)
	AI:PushGoal("stealth_sneakup_left","timeout",1,.5,1.5)
	AI:PushGoal("stealth_sneakup_left","approach",1,3)
	AI:PushGoal("stealth_sneakup_left","signal",1,1,"GO_VISIBLE",0)

	AI:CreateGoalPipe("stealth_sneakup_right")
	AI:PushGoal("stealth_sneakup_right","signal",1,1,"GO_REFRACTIVE",0)
	AI:PushGoal("stealth_sneakup_right","not_shoot")
	AI:PushGoal("stealth_sneakup_right","setup_stand")
	AI:PushGoal("stealth_sneakup_right","do_it_running")
	AI:PushGoal("stealth_sneakup_right","hide",1,20,HM_FRONTRIGHTMOST_FROM_TARGET)
	AI:PushGoal("stealth_sneakup_right","timeout",1,.5,1.5)
	AI:PushGoal("stealth_sneakup_right","hide",1,20,HM_NEAREST_TO_TARGET)
	AI:PushGoal("stealth_sneakup_right","timeout",1,.5,1.5)
	AI:PushGoal("stealth_sneakup_right","hide",1,20,HM_FRONTRIGHTMOST_FROM_TARGET)
	AI:PushGoal("stealth_sneakup_right","timeout",1,.5,1.5)
	AI:PushGoal("stealth_sneakup_right","approach",1,3)
	AI:PushGoal("stealth_sneakup_right","signal",1,1,"GO_VISIBLE",0)

	---------------------------------------
	-- MUTANT MORPHER
	---------------------------------------

	AI:CreateGoalPipe("morpher_attack_wrapper")
	AI:PushGoal("morpher_attack_wrapper","just_shoot")
	AI:PushGoal("morpher_attack_wrapper","setup_stand")
	AI:PushGoal("morpher_attack_wrapper","signal",1,1,"SELECT_MORPH_ATTACK")
	AI:PushGoal("morpher_attack_wrapper","timeout",1,0,.5)
	AI:PushGoal("morpher_attack_wrapper","signal",0,1,"CHECK_FOR_FIND_A_TARGET",0)

	AI:CreateGoalPipe("morpher_attack_wrapper2")
	AI:PushGoal("morpher_attack_wrapper2","just_shoot")
	AI:PushGoal("morpher_attack_wrapper2","setup_stand")
	AI:PushGoal("morpher_attack_wrapper2","do_it_running")
	AI:PushGoal("morpher_attack_wrapper2","approach",1,3) -- Лучше в упор (1,1) не подходить, иначе будет постоянно вызываться OnInterestingSoundHeard.
	AI:PushGoal("morpher_attack_wrapper2","signal",1,1,"SELECT_MORPH_ATTACK")
	AI:PushGoal("morpher_attack_wrapper2","signal",0,1,"FIND_A_TARGET",0)

	AI:CreateGoalPipe("morpher_attack_left")
	AI:PushGoal("morpher_attack_left","just_shoot")
	AI:PushGoal("morpher_attack_left","setup_stand")
	AI:PushGoal("morpher_attack_left","do_it_running")
	AI:PushGoal("morpher_attack_left","hide",1,60,HM_FRONTLEFTMOST_FROM_TARGET)
	AI:PushGoal("morpher_attack_left","signal",0,1,"CHECK_FOR_FIND_A_TARGET",0)

	AI:CreateGoalPipe("morpher_attack_right")
	AI:PushGoal("morpher_attack_right","just_shoot")
	AI:PushGoal("morpher_attack_right","setup_stand")
	AI:PushGoal("morpher_attack_right","do_it_running")
	AI:PushGoal("morpher_attack_right","hide",1,60,HM_FRONTRIGHTMOST_FROM_TARGET)
	AI:PushGoal("morpher_attack_right","signal",0,1,"CHECK_FOR_FIND_A_TARGET",0)

	AI:CreateGoalPipe("morpher_attack_retreat")
	AI:PushGoal("morpher_attack_retreat","just_shoot")
	AI:PushGoal("morpher_attack_retreat","setup_stand")
	AI:PushGoal("morpher_attack_retreat","do_it_running")
	AI:PushGoal("morpher_attack_retreat","hide",1,60,HM_FARTHEST_FROM_TARGET)
	AI:PushGoal("morpher_attack_retreat","signal",0,1,"CHECK_FOR_FIND_A_TARGET",0)

	AI:CreateGoalPipe("morpher_wait_for_target")
	AI:PushGoal("morpher_wait_for_target","not_shoot")
--	AI:PushGoal("morpher_wait_for_target","ignoreall",0,1)
	AI:PushGoal("morpher_wait_for_target","locate",0,"hidepoint")
	AI:PushGoal("morpher_wait_for_target","acqtarget",0,"")
	AI:PushGoal("morpher_wait_for_target","setup_stand")
	AI:PushGoal("morpher_wait_for_target","do_it_walking")
	AI:PushGoal("morpher_wait_for_target","timeout",1,60)
	AI:PushGoal("morpher_wait_for_target","signal",0,1,"CHECK_FOR_FIND_A_TARGET",0)

	AI:CreateGoalPipe("morpher_invisible_attack")
	AI:PushGoal("morpher_invisible_attack","not_shoot")
	AI:PushGoal("morpher_invisible_attack","do_it_running")
	AI:PushGoal("morpher_invisible_attack","setup_stand")
	-- AI:PushGoal("morpher_invisible_attack","hide",1,60,HM_LEFTMOST_FROM_TARGET)
	AI:PushGoal("morpher_invisible_attack","signal",1,1,"SELECT_MORPH_ATTACK")
	AI:PushGoal("morpher_invisible_attack","approach",1,2)
	AI:PushGoal("morpher_invisible_attack","signal",0,1,"CHECK_FOR_FIND_A_TARGET",0)

	AI:CreateGoalPipe("morpher_chase")
	AI:PushGoal("morpher_chase","setup_stand")
	AI:PushGoal("morpher_chase","timeout",1,1,2)
	AI:PushGoal("morpher_chase","signal",1,1,"CHASE_TARGET",0)

	AI:CreateGoalPipe("morpher_morph_at")
	AI:PushGoal("morpher_morph_at","setup_stand")
--	AI:PushGoal("morpher_morph_at","ignoreall",0,1)
	AI:PushGoal("morpher_morph_at","acqtarget",0,"")
	AI:PushGoal("morpher_morph_at","do_it_running")
	AI:PushGoal("morpher_morph_at","approach",1,2)
	AI:PushGoal("morpher_morph_at","signal",1,1,"MORPH",0)
--	AI:PushGoal("morpher_morph_at","ignoreall",0,0)

	----------------------------
	-- ABBERATION STUFF
	-------------------------------


	AI:CreateGoalPipe("abberation_scared")
	AI:PushGoal("abberation_scared","setup_stand")
	AI:PushGoal("abberation_scared","setup_stand")
	AI:PushGoal("abberation_scared","do_it_running")
	AI:PushGoal("abberation_scared","locate",0,"hidepoint")
	AI:PushGoal("abberation_scared","acqtarget",0,"")
	AI:PushGoal("abberation_scared","approach",1,3)
	AI:PushGoal("abberation_scared","signal",1,1,"MAKE_COMBAT_BREAK_ANIM",0)
	AI:PushGoal("abberation_scared","lookat",1,-90,90)
	AI:PushGoal("abberation_scared","lookat",1,-90,90)
	AI:PushGoal("abberation_scared","lookat",1,-90,90)

	AI:CreateGoalPipe("jump_decision")
	AI:PushGoal("jump_decision","signal",1,1,"SEEK_JUMP_ANCHOR",0)

	AI:CreateGoalPipe("abberation_attack")
	AI:PushGoal("abberation_attack","not_shoot")
	AI:PushGoal("abberation_attack","setup_stand")
	AI:PushGoal("abberation_attack","do_it_running")
	AI:PushGoal("abberation_attack","approach",1,.5)
	AI:PushGoal("abberation_attack","signal",1,1,"SEEK_JUMP_ANCHOR",0)

	-- AI:CreateGoalPipe("abberation_hang_back")
	-- AI:PushGoal("abberation_hang_back","not_shoot")
	-- AI:PushGoal("abberation_hang_back","setup_stand")
	-- AI:PushGoal("abberation_hang_back","do_it_running")
	-- AI:PushGoal("abberation_hang_back","signal",1,1,"MAKE_COMBAT_BREAK_ANIM",0)
	-- AI:PushGoal("abberation_hang_back","signal",1,1,"SELECT_MOVEMENT",0)
	-- AI:PushGoal("abberation_hang_back","timeout",1,.3,.8)

	-- AI:CreateGoalPipe("abberation_hang_left")
	-- AI:PushGoal("abberation_hang_left","hide",1,15,HM_FRONTLEFTMOST_FROM_TARGET)

	-- AI:CreateGoalPipe("abberation_hang_right")
	-- AI:PushGoal("abberation_hang_right","hide",1,15,HM_FRONTRIGHTMOST_FROM_TARGET)

	-- AI:CreateGoalPipe("abberation_hang_away")
	-- AI:PushGoal("abberation_hang_away","hide",1,10,HM_FARTHEST_FROM_TARGET)

	-- AI:CreateGoalPipe("abberation_wait_back")
	-- AI:PushGoal("abberation_wait_back","timeout",1,.5,1)


	AI:CreateGoalPipe("abberation_melee")
	AI:PushGoal("abberation_melee","not_shoot")
	AI:PushGoal("abberation_melee","setup_stand")
	AI:PushGoal("abberation_melee","timeout",1,1)
	AI:PushGoal("abberation_melee","signal",1,1,"SWITCH_TO_ABBERATION_ATTACK",0)

	AI:CreateGoalPipe("mutant_idling")
	AI:PushGoal("mutant_idling","not_shoot")
	AI:PushGoal("mutant_idling","not_shoot")
	AI:PushGoal("mutant_idling","locate",0,"hidepoint")
	AI:PushGoal("mutant_idling","acqtarget",0,"")
	AI:PushGoal("mutant_idling","approach",1,.4)
	AI:PushGoal("mutant_idling","hide",1,60,HM_RANDOM,1) -- Работает ли здесь?
	AI:PushGoal("mutant_idling","devalue",0)
	AI:PushGoal("mutant_idling","lookat",1,-45,45)
	AI:PushGoal("mutant_idling","timeout",1,0,1)
	AI:PushGoal("mutant_idling","lookat",1,-45,45)
	AI:PushGoal("mutant_idling","signal",1,1,"DO_SOMETHING_IDLE",0)

	AI:CreateGoalPipe("mutant_investigate_target")
	AI:PushGoal("mutant_investigate_target","hide",0,10,HM_NEAREST_TO_TARGET)
	AI:PushGoal("mutant_investigate_target","lookat",1,-90,90)
	AI:PushGoal("mutant_investigate_target","branch",0,-1)
	AI:PushGoal("mutant_investigate_target","lookat",1,-180,180)
	AI:PushGoal("mutant_investigate_target","timeout",1,0,2)

	AI:CreateGoalPipe("mutant_avoid_grenade")
	AI:PushGoal("mutant_avoid_grenade","not_shoot")
	AI:PushGoal("mutant_avoid_grenade","do_it_running")
	AI:PushGoal("mutant_avoid_grenade","hide",1,10,HM_FARTHEST_FROM_TARGET,1)
	AI:PushGoal("mutant_avoid_grenade","devalue",1)

	AI:CreateGoalPipe("mutant_random_walk")
	AI:PushGoal("mutant_random_walk","locate",0,"hidepoint")
--	AI:PushGoal("mutant_random_walk","acqtarget",0,"")
	AI:PushGoal("mutant_random_walk","timeout",1,.5,2)
	AI:PushGoal("mutant_random_walk","approach",1,.7)
	AI:PushGoal("mutant_random_walk","signal",0,1,"MUTANT_SELECT_IDLE",0)

	AI:CreateGoalPipe("mutant_random_look")
	AI:PushGoal("mutant_random_look","locate",0,"hidepoint")
	AI:PushGoal("mutant_random_look","acqtarget",0,"")
--	AI:PushGoal("mutant_random_look","timeout",0,2,3)
	AI:PushGoal("mutant_random_look","lookat",1,-10,10)
	AI:PushGoal("mutant_random_look","lookat",1,-10,10)
--	AI:PushGoal("mutant_random_look","branch",1,-2)
	AI:PushGoal("mutant_random_look","signal",0,1,"MUTANT_SELECT_IDLE",0)

	AI:CreateGoalPipe("m_c_shoot")
	AI:PushGoal("m_c_shoot","not_shoot")
	AI:PushGoal("m_c_shoot","signal",1,1,"START_PREP_ANIMATION",0)
	AI:PushGoal("m_c_shoot","timeout",1,.4)
	AI:PushGoal("m_c_shoot","just_shoot")
	AI:PushGoal("m_c_shoot","timeout",1,.2)
	AI:PushGoal("m_c_shoot","not_shoot")
	AI:PushGoal("m_c_shoot","timeout",1,1,2)
	AI:PushGoal("m_c_shoot","signal",1,1,"STOPPED_FIRING",0)
	AI:PushGoal("m_c_shoot","signal",1,1,"RUSH_TARGET",0)

	AI:CreateGoalPipe("m_c_quickhide")
	AI:PushGoal("m_c_quickhide","do_it_running")
	AI:PushGoal("m_c_quickhide","hide",1,10,HM_NEAREST)

	AI:CreateGoalPipe("m_c_rush_target")
	AI:PushGoal("m_c_rush_target","do_it_running")
	AI:PushGoal("m_c_rush_target","not_shoot")
	AI:PushGoal("m_c_rush_target","approach",1,1)
	AI:PushGoal("m_c_rush_target","clear",0)

	AI:CreateGoalPipe("m_c_rush_memory")
	AI:PushGoal("m_c_rush_target","do_it_running")
	AI:PushGoal("m_c_rush_target","approach",1,.5)
	AI:PushGoal("m_c_rush_target","timeout",1,.5,1)
	AI:PushGoal("m_c_rush_target","signal",0,1,"ENEMY_TARGET_LOST",SIGNALID_READIBILITY)


	AI:CreateGoalPipe("m_c_find_target")
	AI:PushGoal("m_c_find_target","do_it_walking")
	AI:PushGoal("m_c_find_target","approach",1,1)


	AI:CreateGoalPipe("m_c_melee_attack")
	AI:PushGoal("m_c_melee_attack","signal",0,1,"SELECT_MELEE_ANIMATION",0)
	AI:PushGoal("m_c_melee_attack","signal",0,1,"APPLY_MELEE_DAMAGE",0)
	AI:PushGoal("m_c_melee_attack","signal",0,1,"RESET_MELEE_DAMAGE",0)


	AI:CreateGoalPipe("mutant_cover_cover")
	AI:PushGoal("mutant_cover_cover","not_shoot")
	AI:PushGoal("mutant_cover_cover","signal",0,1,"MUTANT_COVER_UP",0)
	AI:PushGoal("mutant_cover_cover","timeout",1,2,3)
	AI:PushGoal("mutant_cover_cover","just_shoot")
	AI:PushGoal("mutant_cover_cover","signal",0,1,"MUTANT_COVER_DOWN",0)
--	AI:PushGoal("mutant_cover_cover","just_shoot")
	AI:PushGoal("mutant_cover_cover","signal",0,1,"MUTANT_NORMAL_ATTACK",0)

	AI:CreateGoalPipe("mutant_cover_attack")
--	AI:PushGoal("mutant_cover_attack","not_shoot")
--	AI:PushGoal("mutant_cover_attack","signal",0,1,"MUTANT_COVER_UP",0)
----	AI:PushGoal("mutant_cover_attack","timeout",1,2)
--	AI:PushGoal("mutant_cover_attack","timeout",1,1,4)
--	AI:PushGoal("mutant_cover_attack","signal",0,1,"MUTANT_COVER_DOWN",0)
--	AI:PushGoal("mutant_cover_attack","timeout",1,.1,.3)
	AI:PushGoal("mutant_cover_attack","just_shoot")
	AI:PushGoal("mutant_cover_attack","approach",1,.5)
	AI:PushGoal("mutant_cover_attack","signal",0,1,"MUTANT_NORMAL_ATTACK",0)

	AI:CreateGoalPipe("mutant_cover_close_attack")
--AI:PushGoal("mutant_cover_close_attack","setup_crouch")
	AI:PushGoal("mutant_cover_close_attack","just_shoot")
	AI:PushGoal("mutant_cover_close_attack","do_it_running")
	AI:PushGoal("mutant_cover_close_attack","approach",1,5)
--AI:PushGoal("mutant_cover_close_attack","setup_stand")
	AI:PushGoal("mutant_cover_close_attack","not_shoot")
	AI:PushGoal("mutant_cover_close_attack","approach",1,1)
	AI:PushGoal("mutant_cover_close_attack","signal",0,1,"MUTANT_CLOSE_ATTACK",0)
--	AI:PushGoal("mutant_cover_close_attack","hide",1,10,HM_RANDOM,1)
--	AI:PushGoal("mutant_cover_close_attack","signal",0,1,"MUTANT_NORMAL_ATTACK",0)


	AI:CreateGoalPipe("mutant_cover_backoffattack")
	AI:PushGoal("mutant_cover_backoffattack","just_shoot")
	AI:PushGoal("mutant_cover_backoffattack","backoff",1,7)
	AI:PushGoal("mutant_cover_backoffattack","signal",0,1,"MUTANT_NORMAL_ATTACK",0)

	AI:CreateGoalPipe("mutant_standard_attack")
	AI:PushGoal("mutant_standard_attack","not_shoot")
	AI:PushGoal("mutant_standard_attack","do_it_running")
	AI:PushGoal("mutant_standard_attack","hide",1,10,HM_NEAREST,1)
	AI:PushGoal("mutant_standard_attack","just_shoot")
	AI:PushGoal("mutant_standard_attack","timeout",1,0,2)
	AI:PushGoal("mutant_standard_attack","signal",0,1,"MUTANT_NORMAL_ATTACK",0)

	AI:CreateGoalPipe("mutant_cover_strafe_left")
	AI:PushGoal("mutant_cover_strafe_left","strafe",1,-1)

	AI:CreateGoalPipe("mutant_cover_strafe_right")
	AI:PushGoal("mutant_cover_strafe_right","strafe",1,1)

	AI:CreateGoalPipe("mutant_cover_strafe")
	AI:PushGoal("mutant_cover_strafe","bodypos",1,0)
	AI:PushGoal("mutant_cover_strafe","just_shoot")
	AI:PushGoal("mutant_cover_strafe","signal",0,1,"MUTANT_COVER_STRAFE",0)
	AI:PushGoal("mutant_cover_strafe","timeout",1,.2,2.8)
	AI:PushGoal("mutant_cover_strafe","strafe",1,0)
	AI:PushGoal("mutant_cover_strafe","signal",0,1,"MUTANT_NORMAL_ATTACK",0)

	AI:CreateGoalPipe("mutant_cover_strafe_hunt_right")
	AI:PushGoal("mutant_cover_strafe_hunt_right","bodypos",1,0)
	AI:PushGoal("mutant_cover_strafe_hunt_right","strafe",1,1)
	AI:PushGoal("mutant_cover_strafe_hunt_right","timeout",1,.2,.8)
	AI:PushGoal("mutant_cover_strafe_hunt_right","strafe",1,0)
	AI:PushGoal("mutant_cover_strafe_hunt_right","signal",0,1,"MUTANT_COVER_HUNT",0)

	AI:CreateGoalPipe("mutant_cover_strafe_hunt_left")
	AI:PushGoal("mutant_cover_strafe_hunt_left","bodypos",1,0)
	AI:PushGoal("mutant_cover_strafe_hunt_left","strafe",1,1)
	AI:PushGoal("mutant_cover_strafe_hunt_left","timeout",1,.2,.8)
	AI:PushGoal("mutant_cover_strafe_hunt_left","strafe",1,0)
	AI:PushGoal("mutant_cover_strafe_hunt_left","signal",0,1,"MUTANT_COVER_HUNT",0)

	AI:CreateGoalPipe("mutant_cover_hunt")
	AI:PushGoal("mutant_cover_hunt","locate",0,"hidepoint")
	AI:PushGoal("mutant_cover_hunt","acqtarget",0,"")
	AI:PushGoal("mutant_cover_hunt","approach",0,2)
	AI:PushGoal("mutant_cover_hunt","lookat",1,-90,90)
	AI:PushGoal("mutant_cover_hunt","timeout",1,.2,.8)
	AI:PushGoal("mutant_cover_hunt","branch",1,-2)
	AI:PushGoal("mutant_cover_hunt","signal",0,1,"MUTANT_COVER_HUNT",0)

	AI:CreateGoalPipe("mutant_cover_stay")
	AI:PushGoal("mutant_cover_stay","not_shoot")
	AI:PushGoal("mutant_cover_stay","timeout",0,.8)
	AI:PushGoal("mutant_cover_stay","signal",0,1,"MUTANT_CLOSE_ATTACK",0)

	AI:CreateGoalPipe("mutant_crazy_attack")
	AI:PushGoal("mutant_crazy_attack","do_it_running")
	AI:PushGoal("mutant_crazy_attack","approach",1,1)
	--AI:PushGoal("mutant_crazy_attack","signal",0,1,"MUTANT_NORMAL_ATTACK",0)

	AI:CreateGoalPipe("mutant_side_attack")
	AI:PushGoal("mutant_side_attack","locate",0,"hidepoint")
	AI:PushGoal("mutant_side_attack","ignoreall",0,1)
	AI:PushGoal("mutant_side_attack","approach",1,.8)
	AI:PushGoal("mutant_side_attack","ignoreall",0,0)
	AI:PushGoal("mutant_side_attack","mutant_crazy_attack")

	AI:CreateGoalPipe("mutant_small_jump_attack")
	AI:PushGoal("mutant_small_jump_attack","mutanthide",1,7,HM_NEAREST)
	AI:PushGoal("mutant_small_jump_attack","mutant_crazy_attack")

	AI:CreateGoalPipe("mutant_runaway")
	AI:PushGoal("mutant_runaway","do_it_running")
	AI:PushGoal("mutant_runaway","hide",1,20,HM_FARTHEST_FROM_TARGET,1)
	AI:PushGoal("mutant_runaway","signal",0,1,"MUTANT_NORMAL_ATTACK",0)

	AI:CreateGoalPipe("mutant_stay")
	AI:PushGoal("mutant_stay","not_shoot")
	AI:PushGoal("mutant_stay","approach",0,.1)
	AI:PushGoal("mutant_stay","timeout",0,.8)
	AI:PushGoal("mutant_stay","backoff",0,.1)
	AI:PushGoal("mutant_stay","signal",0,1,"MUTANT_NORMAL_ATTACK",0)

	AI:CreateGoalPipe("mutant_shocker")
	AI:PushGoal("mutant_shocker","just_shoot")
--	AI:PushGoal("mutant_shocker","backoff",1,.4)
--	AI:PushGoal("mutant_shocker","just_shoot")
	AI:PushGoal("mutant_shocker","timeout",0,.5,1)
	AI:PushGoal("mutant_shocker","signal",0,1,"MUTANT_NORMAL_ATTACK",0)


--
-----------------
--	Mutant Scout
-----------------
--

	AI:CreateGoalPipe("mutant_scout_attack_far")
	AI:PushGoal("mutant_scout_attack_far","setup_stand")
	AI:PushGoal("mutant_scout_attack_far","just_shoot")
	AI:PushGoal("mutant_scout_attack_far","do_it_running")
	AI:PushGoal("mutant_scout_attack_far","mutanthide",1,15,HM_LEFTMOST_FROM_TARGET)
	AI:PushGoal("mutant_scout_attack_far","reload")
	AI:PushGoal("mutant_scout_attack_far","timeout",1,1,2)

	AI:CreateGoalPipe("mutant_scout_attack_left")
	AI:PushGoal("mutant_scout_attack_left","setup_stand")
	AI:PushGoal("mutant_scout_attack_left","just_shoot")
	AI:PushGoal("mutant_scout_attack_left","timeout",1,0,.5)
	AI:PushGoal("mutant_scout_attack_left","do_it_running")
	AI:PushGoal("mutant_scout_attack_left","mutanthide",1,15,HM_FRONTLEFTMOST_FROM_TARGET)
	AI:PushGoal("mutant_scout_attack_left","reload")
	AI:PushGoal("mutant_scout_attack_left","timeout",1,1,2)

	AI:CreateGoalPipe("mutant_scout_attack_right")
	AI:PushGoal("mutant_scout_attack_right","setup_stand")
	AI:PushGoal("mutant_scout_attack_right","just_shoot")
	AI:PushGoal("mutant_scout_attack_right","timeout",1,0,.5)
	AI:PushGoal("mutant_scout_attack_right","do_it_running")
	AI:PushGoal("mutant_scout_attack_right","mutanthide",1,15,HM_FRONTRIGHTMOST_FROM_TARGET)
	AI:PushGoal("mutant_scout_attack_right","reload")
	AI:PushGoal("mutant_scout_attack_right","timeout",1,1,2)

	AI:CreateGoalPipe("mutant_scout_attack_rand")
	AI:PushGoal("mutant_scout_attack_rand","setup_stand")
	AI:PushGoal("mutant_scout_attack_rand","just_shoot")
	AI:PushGoal("mutant_scout_attack_rand","timeout",1,0,.5)
	AI:PushGoal("mutant_scout_attack_rand","do_it_running")
	AI:PushGoal("mutant_scout_attack_rand","mutanthide",1,15,HM_RANDOM)
--	AI:PushGoal("mutant_scout_attack_rand","reload")
	AI:PushGoal("mutant_scout_attack_rand","timeout",1,1,2)

	AI:CreateGoalPipe("mutant_scout_cover_NOW")
	AI:PushGoal("mutant_scout_cover_NOW","just_shoot")
	AI:PushGoal("mutant_scout_cover_NOW","mutanthide",1,15,HM_NEAREST)
	AI:PushGoal("mutant_scout_cover_NOW","signal",0,1,"SCOUT_NORMALATTACK",0)

	AI:CreateGoalPipe("mutant_scout_tooclose_attack_beacon")
	AI:PushGoal("mutant_scout_tooclose_attack_beacon","DropBeaconAt",0)
	AI:PushGoal("mutant_scout_tooclose_attack_beacon","mutant_scout_tooclose_attack",0)

	AI:CreateGoalPipe("mutant_scout_tooclose_attack")
	AI:PushGoal("mutant_scout_tooclose_attack","just_shoot")
	AI:PushGoal("mutant_scout_tooclose_attack","request_cover")
	AI:PushGoal("mutant_scout_tooclose_attack","do_it_running")
	AI:PushGoal("mutant_scout_tooclose_attack","setup_stand")
	AI:PushGoal("mutant_scout_tooclose_attack","not_shoot")
	AI:PushGoal("mutant_scout_tooclose_attack","mutanthide",1,15,HM_FARTHEST_FROM_TARGET,1)
	AI:PushGoal("mutant_scout_tooclose_attack","just_shoot")
--	AI:PushGoal("scout_tooclose_attack","hide",1,5,HM_NEAREST)
	AI:PushGoal("mutant_scout_tooclose_attack","do_it_walking")
	AI:PushGoal("mutant_scout_tooclose_attack","reload")
	AI:PushGoal("mutant_scout_tooclose_attack","signal",0,1,"SCOUT_NORMALATTACK",0)

	AI:CreateGoalPipe("mutant_scout_hunt")
	AI:PushGoal("mutant_scout_hunt","setup_crouch")
	AI:PushGoal("mutant_scout_hunt","mutanthide",1,15,HM_NEAREST_TO_TARGET)
	AI:PushGoal("mutant_scout_hunt","lookat",1,-90,90)
	AI:PushGoal("mutant_scout_hunt","timeout",1,1,2)
	AI:PushGoal("mutant_scout_hunt","branch",0,-3,1)
	-- try to get closer as long as there is cover to advance
	AI:PushGoal("mutant_scout_hunt","scout_dropebeacon_and_target")
	AI:PushGoal("mutant_scout_hunt","signal",0,1,"SCOUT_HIDE_LEFT_OR_RIGHT",0)
	AI:PushGoal("mutant_scout_hunt","lookat",1,-90,90)
	AI:PushGoal("mutant_scout_hunt","timeout",1,1,2)
	AI:PushGoal("mutant_scout_hunt","scout_dropebeacon_and_target")
	AI:PushGoal("mutant_scout_hunt","signal",0,1,"SCOUT_HIDE_LEFT_OR_RIGHT",0)
	AI:PushGoal("mutant_scout_hunt","lookat",1,-90,90)
	AI:PushGoal("mutant_scout_hunt","timeout",1,1,2)
	AI:PushGoal("mutant_scout_hunt","branch",0,-12,1)	-- if you succeeded moving left,now try moving closer again
	-- if you get here,it means that you cannot move with cover anywhere
	AI:PushGoal("mutant_scout_hunt","timeout",1,2,5)	-- think about it some time
	AI:PushGoal("mutant_scout_hunt","setup_crouch")
	AI:PushGoal("mutant_scout_hunt","approach",1,.5)	-- halve the distance to your target
	AI:PushGoal("mutant_scout_hunt","signal",0,1,"SCOUT_GOTO_ALERT",0)


	AI:CreateGoalPipe("approach_and_look_at")
	AI:PushGoal("approach_and_look_at","acqtarget",0,"")
	AI:PushGoal("approach_and_look_at","approach",1,1)
	AI:PushGoal("approach_and_look_at","lookat",1,0,0)

	AI:CreateGoalPipe("mutant_eat")
	AI:PushGoal("mutant_eat","signal",0,1,"PLAY_FEED_LOOP",0)
	AI:PushGoal("mutant_eat","signal",0,1,"DECISION_POINT",0)

	System:Log("MUTANT PIPES LOADED")
end