-- TEMPLATE
-- DO NOT MODIFY THIS TEMPLATE
--
-- This template has all the readability signals currently in use.  
-- Change the <Template> string to the pack name
-- 
-- To switch between alternate sound responses add a new set of 
-- bracketed parameters, making sure there is a comma after the bracket eg,
--				{
--				PROBABILITY = 500,
--				soundFile = "SOUNDS/<full path to wav file>",
--				Volume = 175,
--				min = 12,
--				max = 300,
--				sound_unscalable = 1,
--				},
-- Probability determines how often a wave is played in response to the signal
-- To allow for possibility of no sound in response to a signal, sounds should sum
-- to less than 1000. eg. if you dont want sound to be played every single time 
-- player receives an order might have total PROBABILITY for all sounds = 500.
--------------------------------------------------
--    Created By: <your_name>
--   Description: <short_description>
--------------------------	
SOUNDPACK.coreworkerA = {
	
	ORDER_RECEIVED = {
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/coreworkerA/affirmative_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/coreworkerA/affirmative_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/coreworkerA/affirmative_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/coreworkerA/affirmative_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/coreworkerA/affirmative_5_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/coreworkerA/affirmative_6_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/coreworkerA/affirmative_7_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/coreworkerA/affirmative_8_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/coreworkerA/affirmative_9_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/coreworkerA/affirmative_10_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	CALL_ALARM = {
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/alarm_alone_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/alarm_alone_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/alarm_alone_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/alarm_alone_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/alarm_alone_5_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	CALL_ALARM_GROUP = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/coreworkerA/alarm_group_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/coreworkerA/alarm_group_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/coreworkerA/alarm_group_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	FIRST_HOSTILE_CONTACT = {
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_combat_al_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_combat_al_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_combat_al_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_combat_al_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_combat_al_5_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_combat_al_6_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_combat_al_7_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_combat_al_8_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	FIRST_HOSTILE_CONTACT_GROUP = {
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_combat_gp_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_combat_gp_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_combat_gp_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_combat_gp_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_combat_gp_5_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_combat_gp_6_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	INTERESTED_TO_IDLE = {
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_idle_al_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_idle_al_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_idle_al_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_idle_al_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_idle_al_5_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_idle_al_6_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_idle_al_7_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_idle_al_8_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	INTERESTED_TO_IDLE_GROUP = {
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_idle_gp_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_idle_gp_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_idle_gp_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_idle_gp_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/alert_to_idle_gp_5_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	THREATEN = {
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/coreworkerA/combat_alone_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/coreworkerA/combat_alone_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/coreworkerA/combat_alone_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/coreworkerA/combat_alone_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/coreworkerA/combat_alone_5_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/coreworkerA/combat_alone_6_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/coreworkerA/combat_alone_7_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/coreworkerA/combat_alone_8_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/coreworkerA/combat_alone_9_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/coreworkerA/combat_alone_10_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/coreworkerA/combat_alone_11_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/coreworkerA/combat_alone_12_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/coreworkerA/combat_alone_13_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/coreworkerA/combat_alone_14_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/coreworkerA/combat_alone_15_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	THREATEN_GROUP = {
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/coreworkerA/combat_group_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/coreworkerA/combat_group_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/coreworkerA/combat_group_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/coreworkerA/combat_group_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/coreworkerA/combat_group_5_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/coreworkerA/combat_group_6_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/coreworkerA/combat_group_7_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	ENEMY_TARGET_LOST = {
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/combat_to_alert_al_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/combat_to_alert_al_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/combat_to_alert_al_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/combat_to_alert_al_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/combat_to_alert_al_5_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/combat_to_alert_al_6_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/combat_to_alert_al_7_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/combat_to_alert_al_8_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	ENEMY_TARGET_LOST_GROUP = {
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/combat_to_alert_gp_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/combat_to_alert_gp_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/combat_to_alert_gp_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/combat_to_alert_gp_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/combat_to_alert_gp_5_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/combat_to_alert_gp_6_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
						
	LO_SPLIT_LEFT = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/coreworkerA/comm_flank_left_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/coreworkerA/comm_flank_left_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/coreworkerA/comm_flank_left_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	LO_SPLIT_RIGHT = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/coreworkerA/comm_flank_right_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/coreworkerA/comm_flank_right_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/coreworkerA/comm_flank_right_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	RETREATING_NOW = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/coreworkerA/comm_retreat_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/coreworkerA/comm_retreat_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/coreworkerA/comm_retreat_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
					
	PROVIDING_COVER = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/coreworkerA/comm_suppress_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/coreworkerA/comm_suppress_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/coreworkerA/comm_suppress_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	ROOM_DARK = {
				--??
				--there are the wavs, but not the readability signal.
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/darkness_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/darkness_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/darkness_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/darkness_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/darkness_5_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
						
	FLASHBANG_GRENADE_EFFECT = {
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/coreworkerA/flashbang_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/coreworkerA/flashbang_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/coreworkerA/flashbang_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/coreworkerA/flaslight_face_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/coreworkerA/flaslight_face_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/coreworkerA/flaslight_face_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/coreworkerA/flaslight_face_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--receiving and throwing grenade?
	FIRE_IN_THE_HOLE = {
				{
				PROBABILITY = 250,
				soundFile = "Languages/voicepacks/coreworkerA/grenade_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Languages/voicepacks/coreworkerA/grenade_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Languages/voicepacks/coreworkerA/grenade_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Languages/voicepacks/coreworkerA/grenade_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	IDLE_TO_THREATENED = {
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/idle_to_alert_al_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/idle_to_alert_al_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/idle_to_alert_al_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/idle_to_alert_al_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/idle_to_alert_al_5_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/idle_to_alert_al_6_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/idle_to_alert_al_7_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/coreworkerA/idle_to_alert_al_8_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	IDLE_TO_THREATENED_GROUP = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/coreworkerA/idle_to_alert_gp_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/coreworkerA/idle_to_alert_gp_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/coreworkerA/idle_to_alert_gp_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	IDLE_TO_INTERESTED = {
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alert_hear_al_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alert_hear_al_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alert_hear_al_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alert_hear_al_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alert_hear_al_5_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alert_hear_al_6_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alert_seen_al_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alert_seen_al_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alert_seen_al_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alert_seen_al_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alert_seen_al_5_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	IDLE_TO_INTERESTED_GROUP = {
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alert_hear_gp_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alert_hear_gp_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alert_hear_gp_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alert_seen_gp_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alert_seen_gp_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alert_seen_gp_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	RANDOM_IDLE_SOUND = {
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alone_cough_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alone_schuckl_1_voiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alone_sneeze_1_voiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alone_sniffle_1_voiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alone_song_1_voiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alone_spit_1_voiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/coreworkerA/idle_alone_throatc_1_voiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	RELOADING = { --or lowammo?
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/low_ammo_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/low_ammo_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/low_ammo_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/reloaded_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/reloaded_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/reloaded_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
	
	FRIEND_DEATH = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/coreworkerA/mandown_alone_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/coreworkerA/mandown_alone_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/coreworkerA/mandown_alone_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	FRIEND_DEATH_GROUP = {
				{
				PROBABILITY = 250,
				soundFile = "Languages/voicepacks/coreworkerA/mandown_group_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Languages/voicepacks/coreworkerA/mandown_group_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Languages/voicepacks/coreworkerA/mandown_group_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Languages/voicepacks/coreworkerA/mandown_group_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI			
	GETTING_SHOT_AT = {
				--??
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/receive_fire_alone_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/receive_fire_alone_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/receive_fire_alone_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/receive_fire_alone_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/receive_fire_alone_5_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/coreworkerA/receive_fire_alone_6_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	GETTING_SHOT_AT_GROUP = {
				--??
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/receive_fire_group_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/receive_fire_group_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/receive_fire_group_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/receive_fire_group_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/receive_fire_group_5_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	GET_REINFORCEMENTS = {
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/coreworkerA/reinforce_go_get_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/coreworkerA/reinforce_go_get_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/coreworkerA/reinforce_go_get_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/coreworkerA/reinforce_go_get_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/coreworkerA/reinforce_go_get_5_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				--
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/coreworkerA/reinforce_tell_get_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/coreworkerA/reinforce_tell_get_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/coreworkerA/reinforce_tell_get_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/coreworkerA/reinforce_tell_get_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/coreworkerA/reinforce_tell_get_5_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	CALL_REINFORCEMENTS = {
				--??
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/reinforce_talk_to_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/reinforce_talk_to_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/reinforce_talk_to_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/reinforce_talk_to_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/coreworkerA/reinforce_talk_to_5_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
						
	AI_AGGRESSIVE = {
				{
				PROBABILITY = 47,
				soundFile = "Languages/voicepacks/coreworkerA/yell_attention_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 47,
				soundFile = "Languages/voicepacks/coreworkerA/yell_attention_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 47,
				soundFile = "Languages/voicepacks/coreworkerA/yell_attention_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 47,
				soundFile = "Languages/voicepacks/coreworkerA/yell_attention_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 47,
				soundFile = "Languages/voicepacks/coreworkerA/yell_attention_5_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				
				--
				{
				PROBABILITY = 47,
				soundFile = "Languages/voicepacks/coreworkerA/yell_fear_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 47,
				soundFile = "Languages/voicepacks/coreworkerA/yell_fear_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 47,
				soundFile = "Languages/voicepacks/coreworkerA/yell_fear_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 47,
				soundFile = "Languages/voicepacks/coreworkerA/yell_fear_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 47,
				soundFile = "Languages/voicepacks/coreworkerA/yell_fear_5_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 47,
				soundFile = "Languages/voicepacks/coreworkerA/yell_fear_6_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 47,
				soundFile = "Languages/voicepacks/coreworkerA/yell_fear_7_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 47,
				soundFile = "Languages/voicepacks/coreworkerA/yell_fear_8_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				
				--
				{
				PROBABILITY = 47,
				soundFile = "Languages/voicepacks/coreworkerA/yell_macho_1_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 47,
				soundFile = "Languages/voicepacks/coreworkerA/yell_macho_2_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 47,
				soundFile = "Languages/voicepacks/coreworkerA/yell_macho_3_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 47,
				soundFile = "Languages/voicepacks/coreworkerA/yell_macho_4_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 47,
				soundFile = "Languages/voicepacks/coreworkerA/yell_macho_5_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 47,
				soundFile = "Languages/voicepacks/coreworkerA/yell_macho_6_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 47,
				soundFile = "Languages/voicepacks/coreworkerA/yell_macho_7_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 47,
				soundFile = "Languages/voicepacks/coreworkerA/yell_macho_8_VoiceA.wav",
				Volume = 175,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
}