-- TEMPLATE
-- DO NOT MODIFY THIS TEMPLATE
--
-- This template has all the readability signals currently in use.
-- Change the <Template> string to the pack name
--
-- To switch between alternate sound responses add a new set of
-- bracketed parameters,making sure there is a comma after the bracket eg,
--				{
--				PROBABILITY = 500,
--				soundFile = "SOUNDS/<full path to wav file>",
--				Volume = 175,
--				min = 7.1,
--				max = 160.1,
--				sound_unscalable = 1,
--				},
-- Probability determines how often a wave is played in response to the signal
-- To allow for possibility of no sound in response to a signal,sounds should sum
-- to less than 1000. eg. if you dont want sound to be played every single time
-- player receives an order might have total PROBABILITY for all sounds = 500.
--------------------------------------------------
--    Created By: <your_name>
--   Description: <short_description>
--------------------------
SOUNDPACK.coreworkerA = {

	ORDER_RECEIVED = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/affirmative_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/affirmative_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/affirmative_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/affirmative_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/affirmative_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/affirmative_6_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/affirmative_7_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/affirmative_8_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/affirmative_9_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/affirmative_10_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	CALL_ALARM = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alarm_alone_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alarm_alone_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alarm_alone_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alarm_alone_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alarm_alone_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	CALL_ALARM_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alarm_group_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alarm_group_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alarm_group_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alarm_alone_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alarm_alone_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alarm_alone_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alarm_alone_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alarm_alone_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	FIRST_HOSTILE_CONTACT = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_combat_al_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_combat_al_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_combat_al_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_combat_al_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_combat_al_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_combat_al_6_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_combat_al_7_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_combat_al_8_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	FIRST_HOSTILE_CONTACT_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_combat_gp_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_combat_gp_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_combat_gp_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_combat_gp_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_combat_gp_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_combat_gp_6_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_combat_al_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_combat_al_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_combat_al_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_combat_al_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_combat_al_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_combat_al_6_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_combat_al_7_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_combat_al_8_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	INTERESTED_TO_IDLE = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_idle_al_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_idle_al_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_idle_al_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_idle_al_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_idle_al_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_idle_al_6_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_idle_al_7_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_idle_al_8_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	INTERESTED_TO_IDLE_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_idle_gp_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_idle_gp_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_idle_gp_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_idle_gp_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_idle_gp_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_idle_al_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_idle_al_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_idle_al_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_idle_al_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_idle_al_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_idle_al_6_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_idle_al_7_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/alert_to_idle_al_8_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	THREATEN = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_6_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_7_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_8_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_9_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_10_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_11_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_12_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_13_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_14_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_15_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	THREATEN_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_group_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_group_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_group_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_group_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_group_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_group_6_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_group_7_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_6_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_7_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_8_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_9_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_10_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_11_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_12_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_13_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_14_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_alone_15_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	ENEMY_TARGET_LOST = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_to_alert_al_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_to_alert_al_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_to_alert_al_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_to_alert_al_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_to_alert_al_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_to_alert_al_6_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_to_alert_al_7_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_to_alert_al_8_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	ENEMY_TARGET_LOST_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_to_alert_gp_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_to_alert_gp_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_to_alert_gp_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_to_alert_gp_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_to_alert_gp_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_to_alert_gp_6_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_to_alert_al_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_to_alert_al_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_to_alert_al_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_to_alert_al_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_to_alert_al_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_to_alert_al_6_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_to_alert_al_7_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/combat_to_alert_al_8_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	LO_SPLIT_LEFT = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/comm_flank_left_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/comm_flank_left_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/comm_flank_left_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	LO_SPLIT_RIGHT = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/comm_flank_right_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/comm_flank_right_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/comm_flank_right_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	RETREATING_NOW = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/comm_retreat_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/comm_retreat_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/comm_retreat_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	PROVIDING_COVER = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/comm_suppress_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/comm_suppress_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/comm_suppress_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	ROOM_DARK = {
				--??
				--there are the wavs,but not the readability signal.
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/darkness_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/darkness_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/darkness_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/darkness_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/darkness_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	FLASHBANG_GRENADE_EFFECT = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/flashbang_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/flashbang_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/flashbang_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/flaslight_face_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/flaslight_face_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/flaslight_face_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/flaslight_face_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--receiving and throwing grenade?
	FIRE_IN_THE_HOLE = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/grenade_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/grenade_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/grenade_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/grenade_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	IDLE_TO_THREATENED = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_to_alert_al_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_to_alert_al_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_to_alert_al_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_to_alert_al_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_to_alert_al_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_to_alert_al_6_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_to_alert_al_7_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_to_alert_al_8_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	IDLE_TO_THREATENED_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_to_alert_gp_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_to_alert_gp_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_to_alert_gp_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_to_alert_al_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_to_alert_al_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_to_alert_al_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_to_alert_al_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_to_alert_al_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_to_alert_al_6_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_to_alert_al_7_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_to_alert_al_8_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	IDLE_TO_ALERT_HEARD = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_hear_al_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_hear_al_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_hear_al_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_hear_al_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_hear_al_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_hear_al_6_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	IDLE_TO_ALERT_HEARD_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_hear_gp_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_hear_gp_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_hear_gp_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_hear_al_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_hear_al_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_hear_al_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_hear_al_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_hear_al_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_hear_al_6_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	IDLE_TO_ALERT_SEEN = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_seen_al_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_seen_al_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_seen_al_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_seen_al_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_seen_al_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	IDLE_TO_ALERT_SEEN_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_seen_gp_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_seen_gp_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_seen_gp_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_seen_al_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_seen_al_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_seen_al_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_seen_al_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alert_seen_al_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	RANDOM_IDLE_SOUND = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alone_cough_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alone_schuckl_1_voiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alone_sneeze_1_voiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alone_sniffle_1_voiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alone_song_1_voiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alone_spit_1_voiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/idle_alone_throatc_1_voiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	RELOADING = {--or lowammo?
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/low_ammo_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/low_ammo_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/low_ammo_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/reloaded_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/reloaded_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/reloaded_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	FRIEND_DEATH = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/mandown_alone_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/mandown_alone_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/mandown_alone_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	FRIEND_DEATH_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/mandown_group_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/mandown_group_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/mandown_group_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/mandown_group_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/mandown_alone_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/mandown_alone_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/mandown_alone_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	GETTING_SHOT_AT = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/receive_fire_alone_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/receive_fire_alone_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/receive_fire_alone_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/receive_fire_alone_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/receive_fire_alone_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/receive_fire_alone_6_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	GETTING_SHOT_AT_GROUP = {
				--??
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/receive_fire_group_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/receive_fire_group_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/receive_fire_group_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/receive_fire_group_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/receive_fire_group_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/receive_fire_alone_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/receive_fire_alone_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/receive_fire_alone_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/receive_fire_alone_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/receive_fire_alone_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/receive_fire_alone_6_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	GET_REINFORCEMENTS = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/reinforce_go_get_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/reinforce_go_get_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/reinforce_go_get_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/reinforce_go_get_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/reinforce_go_get_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				--
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/reinforce_tell_get_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/reinforce_tell_get_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/reinforce_tell_get_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/reinforce_tell_get_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/reinforce_tell_get_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	CALL_REINFORCEMENTS = {
				--??
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/reinforce_talk_to_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/reinforce_talk_to_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/reinforce_talk_to_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/reinforce_talk_to_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/reinforce_talk_to_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	AI_AGGRESSIVE = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/yell_attention_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/yell_attention_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/yell_attention_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/yell_attention_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/yell_attention_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},

				--
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/yell_fear_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/yell_fear_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/yell_fear_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/yell_fear_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/yell_fear_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/yell_fear_6_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/yell_fear_7_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/yell_fear_8_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},

				--
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/yell_macho_1_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/yell_macho_2_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/yell_macho_3_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/yell_macho_4_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/yell_macho_5_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/yell_macho_6_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/yell_macho_7_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/yell_macho_8_VoiceA.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	SEARCHING_GENERIC = {
				--??
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/searching_generic_1.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/searching_generic_2.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/searching_generic_3.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/searching_generic_4.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/searching_generic_5.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/searching_generic_6.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/searching_generic_7.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	SEARCHING_GENERIC_X = {
				--??
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/searching_generic_1.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/searching_generic_2.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				-- {
				-- PROBABILITY = 500,
				-- soundFile = "Languages/voicepacks/CoreworkerA/searching_generic_3.wav",
				-- Volume = 175,
				-- min = 7.1,
				-- max = 160.1,
				-- sound_unscalable = 0,
				--},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/searching_generic_4.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				-- {
				-- PROBABILITY = 500,
				-- soundFile = "Languages/voicepacks/CoreworkerA/searching_generic_5.wav",
				-- Volume = 175,
				-- min = 7.1,
				-- max = 160.1,
				-- sound_unscalable = 0,
				--},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/searching_generic_6.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/CoreworkerA/searching_generic_7.wav",
				Volume = 175,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},
}