-- TEMPLATE
-- DO NOT MODIFY THIS TEMPLATE
--
-- This template has all the readability signals currently in use.  
-- Change the <Template> string to the pack name
-- 
-- To switch between alternate sound responses add a new set of 
-- bracketed parameters, making sure there is a comma after the bracket eg,
--				{
--				PROBABILITY = 500,
--				soundFile = "SOUNDS/<full path to wav file>",
--				Volume = 255,
--				min = 12,
--				max = 300,
--				sound_unscalable = 1,
--				},
-- Probability determines how often a wave is played in response to the signal
-- To allow for possibility of no sound in response to a signal, sounds should sum
-- to less than 1000. eg. if you dont want sound to be played every single time 
-- player receives an order might have total PROBABILITY for all sounds = 500.
--------------------------------------------------
--    Created By: <your_name>
--   Description: <short_description>
--------------------------	
SOUNDPACK.mutant_readability = {
				
	FIRST_HOSTILE_CONTACT = {
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/alert_to_combat_alone_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/alert_to_combat_alone_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/alert_to_combat_alone_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/alert_to_combat_alone_4.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/alert_to_combat_alone_5.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/alert_to_combat_alone_6.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/alert_to_combat_alone_7.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/alert_to_combat_alone_8.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/alert_to_combat_alone_9.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/alert_to_combat_alone_10.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/alert_to_combat_alone_11.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/alert_to_combat_alone_12.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/alert_to_combat_alone_13.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/alert_to_combat_alone_14.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/alert_to_combat_alone_15.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/alert_to_combat_alone_16.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	FIRST_HOSTILE_CONTACT_GROUP = {
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/mutant_readability/alert_to_combat_group_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/mutant_readability/alert_to_combat_group_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/mutant_readability/alert_to_combat_group_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/mutant_readability/alert_to_combat_group_4.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/mutant_readability/alert_to_combat_group_5.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/mutant_readability/alert_to_combat_group_6.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
									
	ENEMY_TARGET_LOST = {
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/combat_to_alert_alone_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/combat_to_alert_alone_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/combat_to_alert_alone_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/combat_to_alert_alone_4.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/combat_to_alert_alone_5.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/combat_to_alert_alone_6.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/combat_to_alert_alone_7.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/combat_to_alert_alone_8.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/combat_to_alert_alone_9.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/combat_to_alert_alone_10.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/combat_to_alert_alone_11.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/combat_to_alert_alone_12.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/combat_to_alert_alone_13.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/combat_to_alert_alone_14.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/combat_to_alert_alone_15.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/mutant_readability/combat_to_alert_alone_16.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	ENEMY_TARGET_LOST_GROUP = {
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/mutant_readability/combat_to_alert_group_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/mutant_readability/combat_to_alert_group_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/mutant_readability/combat_to_alert_group_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/mutant_readability/combat_to_alert_group_4.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/mutant_readability/combat_to_alert_group_5.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/mutant_readability/combat_to_alert_group_6.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
						
	IDLE_TO_INTERESTED = {
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/mutant_readability/idle_to_alert_heard_alone_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/mutant_readability/idle_to_alert_heard_alone_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/mutant_readability/idle_to_alert_heard_alone_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/mutant_readability/idle_to_alert_heard_alone_4.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/mutant_readability/idle_to_alert_heard_alone_5.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/mutant_readability/idle_to_alert_heard_alone_6.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/mutant_readability/idle_to_alert_seen_alone_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/mutant_readability/idle_to_alert_seen_alone_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/mutant_readability/idle_to_alert_seen_alone_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/mutant_readability/idle_to_alert_seen_alone_4.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/mutant_readability/idle_to_alert_seen_alone_5.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	IDLE_TO_INTERESTED_GROUP = {
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/mutant_readability/idle_to_alert_heard_group_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/mutant_readability/idle_to_alert_heard_group_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/mutant_readability/idle_to_alert_heard_group_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/mutant_readability/idle_2_alert_seen_group_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/mutant_readability/idle_2_alert_seen_group_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/mutant_readability/idle_2_alert_seen_group_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	IDLE_TO_THREATENED_GROUP = {
	--Enemy was careless and happy before, and now there is an obviously hostile target 
	--which may or may not be an actual enemy (can be an explosion or a gunshot).
	-- eg. "Holy cow!"
			 	{
				PROBABILITY = 333,
				soundFile = "languages/voicepacks/mutant_readability/idle_to_alert_group_1.wav",
				Volume = 255,
				min = 12,
				max = 300,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "languages/voicepacks/mutant_readability/idle_to_alert_group_2.wav",
				Volume = 255,
				min = 12,
				max = 300,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "languages/voicepacks/mutant_readability/idle_to_alert_group_3.wav",
				Volume = 255,
				min = 12,
				max = 300,
				sound_unscalable = 0,
				},
			 },
------------------------------------------------------------------------------------
	IDLE_TO_THREATENED = {
	--same as IDLE_TO_THREATENED_GROUP
			 	{
				PROBABILITY = 333,
				soundFile = "languages/voicepacks/mutant_readability/idle_to_alert_group_1.wav",
				Volume = 255,
				min = 12,
				max = 300,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "languages/voicepacks/mutant_readability/idle_to_alert_group_2.wav",
				Volume = 255,
				min = 12,
				max = 300,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "languages/voicepacks/mutant_readability/idle_to_alert_group_3.wav",
				Volume = 255,
				min = 12,
				max = 300,
				sound_unscalable = 0,
				},
			 },
}