-- TEMPLATE
-- DO NOT MODIFY THIS TEMPLATE
--
-- This template has all the readability signals currently in use.  
-- Change the <Template> string to the pack name
-- 
-- To switch between alternate sound responses add a new set of 
-- bracketed parameters, making sure there is a comma after the bracket eg,
--				{
--				PROBABILITY = 500,
--				soundFile = "SOUNDS/<full path to wav file>",
--				Volume = 255,
--				min = 12,
--				max = 300,
--				sound_unscalable = 1,
--				},
-- Probability determines how often a wave is played in response to the signal
-- To allow for possibility of no sound in response to a signal, sounds should sum
-- to less than 1000. eg. if you dont want sound to be played every single time 
-- player receives an order might have total PROBABILITY for all sounds = 500.
--------------------------------------------------
--    Created By: <your_name>
--   Description: <short_description>
--------------------------	
SOUNDPACK.voiceD = {
	
	ORDER_RECEIVED = {
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/voiceD/affirmative_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/voiceD/affirmative_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/voiceD/affirmative_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/voiceD/affirmative_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/voiceD/affirmative_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/voiceD/affirmative_6_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/voiceD/affirmative_7_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/voiceD/affirmative_8_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/voiceD/affirmative_9_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/voiceD/affirmative_10_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	CALL_ALARM = {
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/alarm_alone_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/alarm_alone_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/alarm_alone_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/alarm_alone_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/alarm_alone_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	CALL_ALARM_GROUP = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceD/alarm_group_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceD/alarm_group_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceD/alarm_group_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	FIRST_HOSTILE_CONTACT = {
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_combat_alone_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_combat_alone_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_combat_alone_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_combat_alone_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				NOMUTANT = 1,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_combat_alone_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_combat_alone_6_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_combat_alone_7_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_combat_alone_8_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_combat_alone_9_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_combat_alone_10_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_combat_alone_11_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_combat_alone_12_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_combat_alone_13_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_combat_alone_14_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_combat_alone_15_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_combat_alone_16_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	FIRST_HOSTILE_CONTACT_GROUP = {
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/alert_to_combat_group_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/alert_to_combat_group_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/alert_to_combat_group_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/alert_to_combat_group_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/alert_to_combat_group_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/alert_to_combat_group_6_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				NOMUTANT = 1,
				},
			},
			
	INTERESTED_TO_IDLE = {
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_idle_alone_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_idle_alone_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_idle_alone_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_idle_alone_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_idle_alone_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_idle_alone_6_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_idle_alone_7_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_idle_alone_8_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_idle_alone_9_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_idle_alone_10_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_idle_alone_11_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_idle_alone_12_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_idle_alone_13_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_idle_alone_14_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_idle_alone_15_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/alert_to_idle_alone_16_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	INTERESTED_TO_IDLE_GROUP = {
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/alert_to_idle_group_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/alert_to_idle_group_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/alert_to_idle_group_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/alert_to_idle_group_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/alert_to_idle_group_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	THREATEN = {
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				NOMUTANT=1,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_6_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_7_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_8_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_9_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_10_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_11_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_12_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_13_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_14_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_15_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_16_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_17_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_18_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_19_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_20_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_21_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_22_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_23_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_24_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_25_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_26_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_27_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_28_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_29_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_30_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_31_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_32_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_33_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_34_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_35_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_36_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_37_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_38_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_39_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_40_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_41_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_42_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_43_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_44_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceD/combat_alone_45_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	THREATEN_GROUP = {
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceD/combat_group_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceD/combat_group_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceD/combat_group_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceD/combat_group_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceD/combat_group_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceD/combat_group_6_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceD/combat_group_7_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceD/combat_group_8_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceD/combat_group_9_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceD/combat_group_10_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceD/combat_group_11_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceD/combat_group_12_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceD/combat_group_13_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceD/combat_group_14_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceD/combat_group_15_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceD/combat_group_16_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceD/combat_group_17_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceD/combat_group_18_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceD/combat_group_19_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceD/combat_group_20_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	ENEMY_TARGET_LOST = {
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/combat_to_alert_alone_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/combat_to_alert_alone_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/combat_to_alert_alone_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/combat_to_alert_alone_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/combat_to_alert_alone_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/combat_to_alert_alone_6_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/combat_to_alert_alone_7_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/combat_to_alert_alone_8_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/combat_to_alert_alone_9_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/combat_to_alert_alone_10_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/combat_to_alert_alone_11_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/combat_to_alert_alone_12_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/combat_to_alert_alone_13_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/combat_to_alert_alone_14_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/combat_to_alert_alone_15_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceD/combat_to_alert_alone_16_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	ENEMY_TARGET_LOST_GROUP = {
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/combat_to_alert_group_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/combat_to_alert_group_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/combat_to_alert_group_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/combat_to_alert_group_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/combat_to_alert_group_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/combat_to_alert_group_6_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	LO_LEFT_ADVANCE = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceD/comm_advance_left_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceD/comm_advance_left_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceD/comm_advance_left_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	LO_RIGHT_ADVANCE = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceD/comm_advance_right_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceD/comm_advance_right_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceD/comm_advance_right_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	LO_SPLIT_LEFT = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceD/comm_flank_left_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceD/comm_flank_left_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceD/comm_flank_left_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	LO_SPLIT_RIGHT = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceD/comm_flank_right_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceD/comm_flank_right_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceD/comm_flank_right_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	RETREATING_NOW = {
				--??
				--there are the wavs, but not the readability signal.
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/voiceD/comm_retreat_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/voiceD/comm_retreat_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
		
	--filippo: this readability signal is not yet used by the AI
	LO_RUSH = {
				--??
				--there are the wavs, but not the readability signal.
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/voiceD/comm_rush_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/voiceD/comm_rush_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	PROVIDING_COVER = {
				--??
				--there are the wavs, but not the readability signal.
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/comm_suppress_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/comm_suppress_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/comm_suppress_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/comm_suppress_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/comm_suppress_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/comm_suppress_6_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	ROOM_DARK = {
				--??
				--there are the wavs, but not the readability signal.
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/darkness_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/darkness_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/darkness_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/darkness_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/darkness_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
						
	FLASHBANG_GRENADE_EFFECT = {
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/flashbang_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/flashbang_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/flashbang_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/flashbang_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/flashbang_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/flashbang_6_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--receiving and throwing grenade?
	FIRE_IN_THE_HOLE = {
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceD/grenade_1_alone_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceD/grenade_2_alone_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceD/grenade_3_alone_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceD/grenade_4_alone_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceD/grenade_5_alone_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceD/grenade_1_group_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceD/grenade_2_group_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceD/grenade_3_group_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceD/grenade_4_group_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	IDLE_TO_THREATENED = {
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_alone_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_alone_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_alone_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_alone_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_alone_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_alone_6_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_alone_7_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_alone_8_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	IDLE_TO_THREATENED_GROUP = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_group_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_group_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_group_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	IDLE_TO_INTERESTED = {
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_heard_alone_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_heard_alone_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_heard_alone_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_heard_alone_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_heard_alone_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_heard_alone_6_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_seen_alone_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_seen_alone_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_seen_alone_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_seen_alone_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_seen_alone_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	IDLE_TO_INTERESTED_GROUP = {
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_heard_group_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_heard_group_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_heard_group_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_seen_group_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_seen_group_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/idle_to_alert_seen_group_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	
	
	FRIEND_DEATH = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceD/mandown_alone_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceD/mandown_alone_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceD/mandown_alone_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	FRIEND_DEATH_GROUP = {
				{
				PROBABILITY = 250,
				soundFile = "Languages/voicepacks/voiceD/mandown_group_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Languages/voicepacks/voiceD/mandown_group_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Languages/voicepacks/voiceD/mandown_group_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Languages/voicepacks/voiceD/mandown_group_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI			
	GETTING_SHOT_AT = {
				--??
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_alone_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_alone_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_alone_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_alone_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_alone_6_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_alone_7_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_alone_8_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_alone_9_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_alone_10_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_alone_11_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_alone_12_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_alone_15_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_alone_18_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_alone_19_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_alone_20_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	GETTING_SHOT_AT_GROUP = {
				--??
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_group_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_group_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_group_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_group_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_group_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_group_6_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_group_7_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_group_8_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceD/receive_fire_group_9_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	GET_REINFORCEMENTS = {
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/reinforce_go_get_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/reinforce_go_get_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/reinforce_go_get_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/reinforce_go_get_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/reinforce_go_get_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	CALL_REINFORCEMENTS = {
				--??
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/reinforce_talk_to_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/reinforce_talk_to_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/reinforce_talk_to_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/reinforce_talk_to_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceD/reinforce_talk_to_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	GET_IN_VEHICLE = {
				--??
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/vehicle_in_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/vehicle_in_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/vehicle_in_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/vehicle_in_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/vehicle_in_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/vehicle_in_6_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/vehicle_in_7_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/vehicle_in_8_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	AI_AGGRESSIVE = {
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/yell_attention_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/yell_attention_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/yell_attention_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/yell_attention_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/yell_attention_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				
				--
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/yell_fear_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/yell_fear_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/yell_fear_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/yell_fear_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/yell_fear_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				
				--
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/yell_macho_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/yell_macho_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/yell_macho_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/yell_macho_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceD/yell_macho_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
		
	--filippo: this readability signal is not yet used by the AI
	GET_WEAPON = {
				--??
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/get_weapon_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/get_weapon_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/get_weapon_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/get_weapon_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/get_weapon_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/get_weapon_6_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	VEHICLE_SIGHTING_PLAYER = {
				--?? should be both for helicopter and boat (BOAT/HELICOPTER SIGHTING PLAYER)
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/helicopter_sight_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/helicopter_sight_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/helicopter_sight_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/helicopter_sight_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/helicopter_sight_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/helicopter_sight_6_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/helicopter_sight_7_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceD/helicopter_sight_8_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	SEARCHING_GENERIC = {
				--??
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/voiceD/searching_generic_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/voiceD/searching_generic_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/voiceD/searching_generic_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/voiceD/searching_generic_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/voiceD/searching_generic_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/voiceD/searching_generic_6_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/voiceD/searching_generic_7_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	SEARCHING_MUTANTS = {
				--??
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/searching_mutants_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/searching_mutants_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/searching_mutants_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/searching_mutants_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/searching_mutants_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/searching_mutants_6_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	SEARCHING_PLAYER = {
				--??
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/searching_player_1_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/searching_player_2_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/searching_player_3_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/searching_player_4_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/searching_player_5_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceD/searching_player_6_VoiceD.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
}