-- TEMPLATE
-- DO NOT MODIFY THIS TEMPLATE
--
-- This template has all the readability signals currently in use.  
-- Change the <Template> string to the pack name
-- 
-- To switch between alternate sound responses add a new set of 
-- bracketed parameters, making sure there is a comma after the bracket eg,
--				{
--				PROBABILITY = 500,
--				soundFile = "SOUNDS/<full path to wav file>",
--				Volume = 255,
--				min = 12,
--				max = 300,
--				sound_unscalable = 1,
--				},
-- Probability determines how often a wave is played in response to the signal
-- To allow for possibility of no sound in response to a signal, sounds should sum
-- to less than 1000. eg. if you dont want sound to be played every single time 
-- player receives an order might have total PROBABILITY for all sounds = 500.
--------------------------------------------------
--    Created By: <your_name>
--   Description: <short_description>
--------------------------	
SOUNDPACK.voiceC = {
	
	ORDER_RECEIVED = {
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/voiceC/affirmative_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/voiceC/affirmative_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/voiceC/affirmative_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/voiceC/affirmative_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/voiceC/affirmative_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/voiceC/affirmative_6_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/voiceC/affirmative_7_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/voiceC/affirmative_8_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/voiceC/affirmative_9_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/voiceC/affirmative_10_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	CALL_ALARM = {
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/alarm_alone_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/alarm_alone_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/alarm_alone_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/alarm_alone_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/alarm_alone_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	CALL_ALARM_GROUP = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceC/alarm_group_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceC/alarm_group_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceC/alarm_group_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	FIRST_HOSTILE_CONTACT = {
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_combat_alone_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_combat_alone_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_combat_alone_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_combat_alone_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				NOMUTANT = 1,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_combat_alone_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_combat_alone_6_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_combat_alone_7_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_combat_alone_8_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_combat_alone_9_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_combat_alone_10_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_combat_alone_11_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_combat_alone_12_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_combat_alone_13_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_combat_alone_14_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_combat_alone_15_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_combat_alone_16_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	FIRST_HOSTILE_CONTACT_GROUP = {
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/alert_to_combat_group_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/alert_to_combat_group_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/alert_to_combat_group_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/alert_to_combat_group_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/alert_to_combat_group_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/alert_to_combat_group_6_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				NOMUTANT=1,
				},
			},
			
	INTERESTED_TO_IDLE = {
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_idle_alone_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_idle_alone_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_idle_alone_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_idle_alone_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_idle_alone_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_idle_alone_6_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_idle_alone_7_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_idle_alone_8_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_idle_alone_9_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_idle_alone_10_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_idle_alone_11_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_idle_alone_12_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_idle_alone_13_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_idle_alone_14_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_idle_alone_15_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/alert_to_idle_alone_16_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	INTERESTED_TO_IDLE_GROUP = {
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/alert_to_idle_group_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/alert_to_idle_group_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/alert_to_idle_group_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/alert_to_idle_group_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/alert_to_idle_group_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	THREATEN = {
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				NOMUTANT=1,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_6_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_7_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_8_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_9_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_10_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_11_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_12_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_13_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_14_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_15_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_16_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_17_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_18_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_19_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_20_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_21_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_22_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_23_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_24_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_25_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_26_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_27_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_28_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_29_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_30_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_31_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_32_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_33_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_34_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_35_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_36_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_37_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_38_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_39_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_40_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_41_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_42_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_43_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_44_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/voiceC/combat_alone_45_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	THREATEN_GROUP = {
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceC/combat_group_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceC/combat_group_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceC/combat_group_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceC/combat_group_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceC/combat_group_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceC/combat_group_6_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceC/combat_group_7_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceC/combat_group_8_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceC/combat_group_9_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceC/combat_group_10_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceC/combat_group_11_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceC/combat_group_12_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceC/combat_group_13_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceC/combat_group_14_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceC/combat_group_15_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceC/combat_group_16_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceC/combat_group_17_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceC/combat_group_18_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceC/combat_group_19_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/voiceC/combat_group_20_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	ENEMY_TARGET_LOST = {
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/combat_to_alert_alone_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/combat_to_alert_alone_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/combat_to_alert_alone_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/combat_to_alert_alone_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/combat_to_alert_alone_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/combat_to_alert_alone_6_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/combat_to_alert_alone_7_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/combat_to_alert_alone_8_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/combat_to_alert_alone_9_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/combat_to_alert_alone_10_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/combat_to_alert_alone_11_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/combat_to_alert_alone_12_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/combat_to_alert_alone_13_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/combat_to_alert_alone_14_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/combat_to_alert_alone_15_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/voiceC/combat_to_alert_alone_16_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	ENEMY_TARGET_LOST_GROUP = {
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/combat_to_alert_group_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/combat_to_alert_group_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/combat_to_alert_group_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/combat_to_alert_group_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/combat_to_alert_group_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/combat_to_alert_group_6_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	LO_LEFT_ADVANCE = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceC/comm_advance_left_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceC/comm_advance_left_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceC/comm_advance_left_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	LO_RIGHT_ADVANCE = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceC/comm_advance_right_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceC/comm_advance_right_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceC/comm_advance_right_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	LO_SPLIT_LEFT = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceC/comm_flank_left_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceC/comm_flank_left_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceC/comm_flank_left_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	LO_SPLIT_RIGHT = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceC/comm_flank_right_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceC/comm_flank_right_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceC/comm_flank_right_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	RETREATING_NOW = {
				--??
				--there are the wavs, but not the readability signal.
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/voiceC/comm_retreat_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/voiceC/comm_retreat_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
		
	--filippo: this readability signal is not yet used by the AI
	LO_RUSH = {
				--??
				--there are the wavs, but not the readability signal.
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/voiceC/comm_rush_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/voiceC/comm_rush_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	PROVIDING_COVER = {
				--??
				--there are the wavs, but not the readability signal.
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/comm_suppress_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/comm_suppress_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/comm_suppress_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/comm_suppress_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/comm_suppress_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/comm_suppress_6_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	ROOM_DARK = {
				--??
				--there are the wavs, but not the readability signal.
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/darkness_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/darkness_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/darkness_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/darkness_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/darkness_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
						
	FLASHBANG_GRENADE_EFFECT = {
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/flashbang_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/flashbang_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/flashbang_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/flashbang_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/flashbang_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/flashbang_6_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--receiving and throwing grenade?
	FIRE_IN_THE_HOLE = {
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceC/grenade_1_alone_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceC/grenade_2_alone_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceC/grenade_3_alone_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceC/grenade_4_alone_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceC/grenade_5_alone_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceC/grenade_1_group_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceC/grenade_2_group_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceC/grenade_3_group_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceC/grenade_4_group_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	IDLE_TO_THREATENED = {
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_alone_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_alone_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_alone_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_alone_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_alone_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_alone_6_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_alone_7_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_alone_8_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	IDLE_TO_THREATENED_GROUP = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_group_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_group_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_group_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	IDLE_TO_INTERESTED = {
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_heard_alone_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_heard_alone_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_heard_alone_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_heard_alone_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_heard_alone_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_heard_alone_6_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_seen_alone_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_seen_alone_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_seen_alone_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_seen_alone_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_seen_alone_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	IDLE_TO_INTERESTED_GROUP = {
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_heard_group_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_heard_group_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_heard_group_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_seen_group_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_seen_group_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/idle_to_alert_seen_group_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	
	
	FRIEND_DEATH = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceC/mandown_alone_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceC/mandown_alone_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/voiceC/mandown_alone_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	FRIEND_DEATH_GROUP = {
				{
				PROBABILITY = 250,
				soundFile = "Languages/voicepacks/voiceC/mandown_group_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Languages/voicepacks/voiceC/mandown_group_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Languages/voicepacks/voiceC/mandown_group_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Languages/voicepacks/voiceC/mandown_group_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI			
	GETTING_SHOT_AT = {
				--??
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_alone_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_alone_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_alone_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_alone_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_alone_6_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_alone_7_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_alone_8_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_alone_9_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_alone_10_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_alone_11_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_alone_12_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_alone_15_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_alone_18_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_alone_19_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_alone_20_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	GETTING_SHOT_AT_GROUP = {
				--??
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_group_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_group_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_group_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_group_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_group_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_group_6_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_group_7_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_group_8_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/voiceC/receive_fire_group_9_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	GET_REINFORCEMENTS = {
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/reinforce_go_get_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/reinforce_go_get_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/reinforce_go_get_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/reinforce_go_get_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/reinforce_go_get_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	CALL_REINFORCEMENTS = {
				--??
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/reinforce_talk_to_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/reinforce_talk_to_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/reinforce_talk_to_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/reinforce_talk_to_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/voiceC/reinforce_talk_to_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	GET_IN_VEHICLE = {
				--??
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/vehicle_in_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/vehicle_in_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/vehicle_in_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/vehicle_in_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/vehicle_in_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/vehicle_in_6_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/vehicle_in_7_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/vehicle_in_8_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	AI_AGGRESSIVE = {
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/yell_attention_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/yell_attention_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/yell_attention_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/yell_attention_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/yell_attention_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				
				--
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/yell_fear_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/yell_fear_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/yell_fear_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/yell_fear_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/yell_fear_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				
				--
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/yell_macho_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/yell_macho_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/yell_macho_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/yell_macho_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/voiceC/yell_macho_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
		
	--filippo: this readability signal is not yet used by the AI
	GET_WEAPON = {
				--??
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/get_weapon_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/get_weapon_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/get_weapon_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/get_weapon_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/get_weapon_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/get_weapon_6_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	VEHICLE_SIGHTING_PLAYER = {
				--?? should be both for helicopter and boat (BOAT/HELICOPTER SIGHTING PLAYER)
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/helicopter_sight_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/helicopter_sight_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/helicopter_sight_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/helicopter_sight_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/helicopter_sight_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/helicopter_sight_6_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/helicopter_sight_7_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/voiceC/helicopter_sight_8_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	SEARCHING_GENERIC = {
				--??
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/voiceC/searching_generic_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/voiceC/searching_generic_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/voiceC/searching_generic_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/voiceC/searching_generic_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/voiceC/searching_generic_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/voiceC/searching_generic_6_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/voiceC/searching_generic_7_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	SEARCHING_MUTANTS = {
				--??
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/searching_mutants_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/searching_mutants_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/searching_mutants_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/searching_mutants_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/searching_mutants_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/searching_mutants_6_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	SEARCHING_PLAYER = {
				--??
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/searching_player_1_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/searching_player_2_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/searching_player_3_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/searching_player_4_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/searching_player_5_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/voiceC/searching_player_6_VoiceC.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
}