-- TEMPLATE
-- DO NOT MODIFY THIS TEMPLATE
--
-- This template has all the readability signals currently in use.
-- Change the <Template> string to the pack name
--
-- To switch between alternate sound responses add a new set of
-- bracketed parameters,making sure there is a comma after the bracket eg,
--				{
--				PROBABILITY = 500,
--				soundFile = "SOUNDS/<full path to wav file>",
--				Volume = 255,
--				min = 7.1,
--				max = 160.1,
--				sound_unscalable = 1,
--				},
-- Probability determines how often a wave is played in response to the signal
-- To allow for possibility of no sound in response to a signal,sounds should sum
-- to less than 1000. eg. if you dont want sound to be played every single time
-- player receives an order might have total PROBABILITY for all sounds = 500.
--------------------------------------------------
--    Created By: <your_name>
--   Description: <short_description>
--------------------------
SOUNDPACK.voiceD = {

	ORDER_RECEIVED = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/affirmative_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/affirmative_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/affirmative_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/affirmative_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/affirmative_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/affirmative_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/affirmative_7_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/affirmative_8_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/affirmative_9_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/affirmative_10_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	CALL_ALARM = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alarm_alone_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alarm_alone_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alarm_alone_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alarm_alone_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alarm_alone_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	CALL_ALARM_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alarm_group_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alarm_group_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alarm_group_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alarm_alone_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alarm_alone_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alarm_alone_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alarm_alone_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alarm_alone_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	FIRST_HOSTILE_CONTACT = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				NOMUTANT = 1,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_7_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_8_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_9_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_10_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_11_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_12_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_13_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_14_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_15_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_16_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	FIRST_HOSTILE_CONTACT_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_group_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_group_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_group_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_group_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_group_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_group_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				NOMUTANT = 1,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				NOMUTANT = 1,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_7_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_8_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_9_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_10_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_11_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_12_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_13_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_14_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_15_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_combat_alone_16_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	INTERESTED_TO_IDLE = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_7_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_8_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_9_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_10_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_11_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_12_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_13_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_14_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_15_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_16_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	INTERESTED_TO_IDLE_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_group_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_group_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_group_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_group_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_group_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_7_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_8_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_9_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_10_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_11_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_12_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_13_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_14_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_15_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/alert_to_idle_alone_16_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	THREATEN = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				NOMUTANT=1,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_7_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_8_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_9_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_10_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_11_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_12_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_13_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_14_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_15_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_16_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_17_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_18_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_19_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_20_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_21_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_22_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_23_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_24_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_25_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_26_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_27_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_28_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_29_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_30_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_31_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_32_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_33_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_34_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_35_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_36_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_37_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_38_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_39_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_40_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_41_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_42_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_43_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_44_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_45_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	THREATEN_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_group_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_group_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_group_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_group_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_group_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_group_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_group_7_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_group_8_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_group_9_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_group_10_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_group_11_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_group_12_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_group_13_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_group_14_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_group_15_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_group_16_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_group_17_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_group_18_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_group_19_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_group_20_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				NOMUTANT=1,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_7_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_8_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_9_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_10_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_11_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_12_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_13_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_14_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_15_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_16_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_17_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_18_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_19_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_20_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_21_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_22_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_23_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_24_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_25_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_26_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_27_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_28_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_29_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_30_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_31_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_32_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_33_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_34_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_35_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_36_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_37_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_38_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_39_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_40_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_41_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_42_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_43_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_44_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_alone_45_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	ENEMY_TARGET_LOST = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_7_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_8_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_9_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_10_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_11_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_12_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_13_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_14_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_15_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_16_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	ENEMY_TARGET_LOST_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_group_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_group_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_group_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_group_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_group_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_group_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_7_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_8_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_9_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_10_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_11_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_12_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_13_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_14_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_15_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/combat_to_alert_alone_16_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	LO_LEFT_ADVANCE = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/comm_advance_left_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/comm_advance_left_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/comm_advance_left_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	LO_RIGHT_ADVANCE = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/comm_advance_right_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/comm_advance_right_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/comm_advance_right_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	LO_SPLIT_LEFT = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/comm_flank_left_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/comm_flank_left_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/comm_flank_left_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	LO_SPLIT_RIGHT = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/comm_flank_right_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/comm_flank_right_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/comm_flank_right_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	RETREATING_NOW = {
				--??
				--there are the wavs,but not the readability signal.
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/comm_retreat_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/comm_retreat_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	LO_RUSH = {
				--??
				--there are the wavs,but not the readability signal.
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/comm_rush_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/comm_rush_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	PROVIDING_COVER = {
				--??
				--there are the wavs,but not the readability signal.
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/comm_suppress_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/comm_suppress_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/comm_suppress_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/comm_suppress_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/comm_suppress_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/comm_suppress_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	-- Если просто темно.
	ROOM_DARK_1 = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/darkness_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/darkness_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	-- Если свет вдруг пропал.
	ROOM_DARK_2 = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/darkness_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/darkness_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/darkness_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	FLASHBANG_GRENADE_EFFECT = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/flashbang_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/flashbang_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/flashbang_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/flashbang_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/flashbang_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/flashbang_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--receiving and throwing grenade?
	FIRE_IN_THE_HOLE = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/grenade_1_alone_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/grenade_2_alone_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/grenade_3_alone_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/grenade_4_alone_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/grenade_5_alone_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/grenade_1_group_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/grenade_2_group_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/grenade_3_group_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/grenade_4_group_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	IDLE_TO_THREATENED = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_alone_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_alone_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_alone_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_alone_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_alone_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_alone_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_alone_7_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_alone_8_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	IDLE_TO_THREATENED_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_group_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_group_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_group_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_alone_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_alone_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_alone_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_alone_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_alone_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_alone_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_alone_7_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_alone_8_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	IDLE_TO_ALERT_HEARD = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_heard_alone_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_heard_alone_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_heard_alone_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_heard_alone_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_heard_alone_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_heard_alone_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	IDLE_TO_ALERT_HEARD_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_heard_group_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_heard_group_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_heard_group_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_heard_alone_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_heard_alone_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_heard_alone_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_heard_alone_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_heard_alone_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_heard_alone_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	IDLE_TO_ALERT_SEEN = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_seen_alone_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_seen_alone_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_seen_alone_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_seen_alone_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_seen_alone_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	IDLE_TO_ALERT_SEEN_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_seen_group_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_seen_group_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_seen_group_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_seen_alone_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_seen_alone_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_seen_alone_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_seen_alone_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_to_alert_seen_alone_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	RANDOM_IDLE_SOUND = {
				-- {
				-- PROBABILITY = 500,
				-- soundFile = "Languages/voicepacks/VoiceD/idle_alone_chuckle_1.wav",
				-- Volume = 255,
				-- min = 7.1,
				-- max = 160.1,
				-- sound_unscalable = 0,
				--},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_alone_cough_1.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_alone_sneeze_1.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_alone_sniffle_1.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_alone_spit_1.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_alone_throatclear_1.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_alone_hum_1.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_alone_hum_2.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_alone_hum_3.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_alone_hum_4.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_alone_hum_5.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_alone_song_1.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_alone_song_2.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_alone_song_3.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_alone_song_4.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_alone_song_5.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_alone_whistle_1.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_alone_whistle_2.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_alone_whistle_3.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_alone_whistle_4.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/idle_alone_whistle_5.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},


	FRIEND_DEATH = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/mandown_alone_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/mandown_alone_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/mandown_alone_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	FRIEND_DEATH_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/mandown_group_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/mandown_group_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/mandown_group_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/mandown_group_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/mandown_alone_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/mandown_alone_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/mandown_alone_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	GETTING_SHOT_AT = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_7_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_8_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_9_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_10_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_11_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_12_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_15_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_18_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_19_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_20_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	GETTING_SHOT_AT_GROUP = {
				--??
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_group_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_group_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_group_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_group_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_group_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_group_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_group_7_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_group_8_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_group_9_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_7_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_8_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_9_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_10_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_11_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_12_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_15_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_18_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_19_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/receive_fire_alone_20_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	GET_REINFORCEMENTS = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/reinforce_go_get_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/reinforce_go_get_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/reinforce_go_get_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/reinforce_go_get_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/reinforce_go_get_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	CALL_REINFORCEMENTS = {
				--??
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/reinforce_talk_to_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/reinforce_talk_to_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/reinforce_talk_to_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/reinforce_talk_to_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/reinforce_talk_to_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	GET_IN_VEHICLE = {
				--??
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/vehicle_in_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/vehicle_in_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/vehicle_in_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/vehicle_in_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/vehicle_in_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/vehicle_in_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/vehicle_in_7_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/vehicle_in_8_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	-- Тихое обращение к врагу. П-с-с. Ты. Эй. Э-э-э. Эй ты.
	AI_AGGRESSIVE_ATTENTION = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/yell_attention_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/yell_attention_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/yell_attention_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/yell_attention_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/yell_attention_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},
	-- Когда больно от огня. Иногда походит на испуг.
	AI_AGGRESSIVE_FEAR = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/yell_fear_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/yell_fear_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/yell_fear_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/yell_fear_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/yell_fear_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/yell_fear_6.wav", -- Не хватает фонем.
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/yell_fear_7.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/yell_fear_8.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},
	-- Яху-у-у-у-у.
	AI_AGGRESSIVE_MACHO = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/yell_macho_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/yell_macho_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/yell_macho_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/yell_macho_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/yell_macho_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/yell_macho_6.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/yell_macho_7.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/yell_macho_8.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},
	GET_WEAPON = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/get_weapon_1.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/get_weapon_2.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/get_weapon_3.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/get_weapon_4.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/get_weapon_5.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/get_weapon_6.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	VEHICLE_SIGHTING_PLAYER = {
				--?? should be both for helicopter and boat (BOAT/HELICOPTER SIGHTING PLAYER)
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/helicopter_sight_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/helicopter_sight_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/helicopter_sight_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/helicopter_sight_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/helicopter_sight_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/helicopter_sight_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/helicopter_sight_7_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/helicopter_sight_8_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	SEARCHING_GENERIC = {
				--??
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/searching_generic_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/searching_generic_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/searching_generic_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/searching_generic_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/searching_generic_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/searching_generic_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/searching_generic_7_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	SEARCHING_GENERIC_X = {
				--??
				-- {
				-- PROBABILITY = 500,
				-- soundFile = "Languages/voicepacks/VoiceD/searching_generic_1_VoiceD.wav",
				-- Volume = 255,
				-- min = 7.1,
				-- max = 160.1,
				-- sound_unscalable = 0,
				--},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/searching_generic_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				-- {
				-- PROBABILITY = 500,
				-- soundFile = "Languages/voicepacks/VoiceD/searching_generic_3_VoiceD.wav",
				-- Volume = 255,
				-- min = 7.1,
				-- max = 160.1,
				-- sound_unscalable = 0,
				--},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/searching_generic_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				-- {
				-- PROBABILITY = 500,
				-- soundFile = "Languages/voicepacks/VoiceD/searching_generic_5_VoiceD.wav",
				-- Volume = 255,
				-- min = 7.1,
				-- max = 160.1,
				-- sound_unscalable = 0,
				--},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/searching_generic_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/searching_generic_7_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	SEARCHING_MUTANTS = {
				--??
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/searching_mutants_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/searching_mutants_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/searching_mutants_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/searching_mutants_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/searching_mutants_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/searching_mutants_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	SEARCHING_PLAYER = {
				--??
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/searching_player_1_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/searching_player_2_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/searching_player_3_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/searching_player_4_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/searching_player_5_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceD/searching_player_6_VoiceD.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},
}