-- TEMPLATE
-- DO NOT MODIFY THIS TEMPLATE
--
-- This template has all the readability signals currently in use.
-- Change the <Template> string to the pack name
--
-- To switch between alternate sound responses add a new set of
-- bracketed parameters,making sure there is a comma after the bracket eg,
--				{
--				PROBABILITY = 500,
--				soundFile = "SOUNDS/<full path to wav file>",
--				Volume = 255,
--				min = 7.1,
--				max = 160.1,
--				sound_unscalable = 1,
--				},
-- Probability determines how often a wave is played in response to the signal
-- To allow for possibility of no sound in response to a signal,sounds should sum
-- to less than 1000. eg. if you dont want sound to be played every single time
-- player receives an order might have total PROBABILITY for all sounds = 500.
--------------------------------------------------
--    Created By: <your_name>
--   Description: <short_description>
--------------------------
SOUNDPACK.voiceA = {

	ORDER_RECEIVED = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/affirmative_1_VoiceA.wav",
				Volume = 255, -- Должно быть всегда на максимуме чтобы было плавное затухане между min и max.
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/affirmative_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/affirmative_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/affirmative_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/affirmative_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/affirmative_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/affirmative_7_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/affirmative_8_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/affirmative_9_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/affirmative_10_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	CALL_ALARM = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alarm_alone_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alarm_alone_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alarm_alone_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alarm_alone_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alarm_alone_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	CALL_ALARM_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alarm_group_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alarm_group_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alarm_group_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alarm_alone_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alarm_alone_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alarm_alone_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alarm_alone_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alarm_alone_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	FIRST_HOSTILE_CONTACT = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				NOMUTANT=1,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_7_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_8_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_9_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_10_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_11_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_12_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_13_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_14_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_15_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_16_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	FIRST_HOSTILE_CONTACT_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_group_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_group_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_group_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_group_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_group_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_group_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				NOMUTANT = 1,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				NOMUTANT=1,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_7_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_8_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_9_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_10_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_11_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_12_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_13_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_14_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_15_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_combat_alone_16_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	INTERESTED_TO_IDLE = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_7_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_8_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_9_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_10_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_11_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_12_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_13_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_14_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_15_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_16_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	INTERESTED_TO_IDLE_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_group_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_group_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_group_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_group_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_group_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_7_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_8_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_9_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_10_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_11_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_12_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_13_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_14_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_15_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/alert_to_idle_alone_16_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	THREATEN = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				NOMUTANT = 1,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_7_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_8_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_9_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_10_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_11_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_12_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_13_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_14_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_15_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_16_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_17_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_18_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_19_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_20_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_21_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_22_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_23_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_24_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_25_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_26_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_27_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_28_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_29_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_30_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_31_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_32_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_33_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_34_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_35_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_36_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_37_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_38_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_39_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_40_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_41_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_42_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_43_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_44_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_45_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	THREATEN_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_group_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_group_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_group_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_group_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_group_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_group_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_group_7_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_group_8_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_group_9_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_group_10_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_group_11_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_group_12_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_group_13_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_group_14_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_group_15_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_group_16_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_group_17_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_group_18_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_group_19_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_group_20_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				NOMUTANT = 1,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_7_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_8_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_9_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_10_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_11_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_12_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_13_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_14_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_15_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_16_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_17_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_18_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_19_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_20_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_21_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_22_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_23_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_24_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_25_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_26_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_27_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_28_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_29_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_30_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_31_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_32_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_33_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_34_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_35_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_36_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_37_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_38_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_39_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_40_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_41_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_42_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_43_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_44_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_alone_45_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	ENEMY_TARGET_LOST = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_7_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_8_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_9_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_10_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_11_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_12_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_13_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_14_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_15_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_16_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	ENEMY_TARGET_LOST_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_group_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_group_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_group_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_group_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_group_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_group_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_7_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_8_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_9_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_10_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_11_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_12_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_13_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_14_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_15_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/combat_to_alert_alone_16_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	LO_LEFT_ADVANCE = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/comm_advance_left_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/comm_advance_left_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/comm_advance_left_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	LO_RIGHT_ADVANCE = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/comm_advance_right_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/comm_advance_right_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/comm_advance_right_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	LO_SPLIT_LEFT = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/comm_flank_left_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/comm_flank_left_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/comm_flank_left_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	LO_SPLIT_RIGHT = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/comm_flank_right_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/comm_flank_right_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/comm_flank_right_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	RETREATING_NOW = {
				--??
				--there are the wavs,but not the readability signal.
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/comm_retreat_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/comm_retreat_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	LO_RUSH = {
				--??
				--there are the wavs,but not the readability signal.
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/comm_rush_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/comm_rush_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	PROVIDING_COVER = {
				--??
				--there are the wavs,but not the readability signal.
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/comm_suppress_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/comm_suppress_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/comm_suppress_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/comm_suppress_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/comm_suppress_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/comm_suppress_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	-- Если просто темно.
	ROOM_DARK_1 = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/darkness_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/darkness_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	-- Если свет вдруг пропал.
	ROOM_DARK_2 = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/darkness_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/darkness_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/darkness_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	FLASHBANG_GRENADE_EFFECT = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/flashbang_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/flashbang_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/flashbang_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/flashbang_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/flashbang_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/flashbang_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--receiving and throwing grenade?
	FIRE_IN_THE_HOLE = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/grenade_1_alone_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/grenade_2_alone_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/grenade_3_alone_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/grenade_4_alone_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/grenade_5_alone_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/grenade_1_group_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/grenade_2_group_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/grenade_3_group_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/grenade_4_group_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	IDLE_TO_THREATENED = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_alone_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_alone_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_alone_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_alone_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_alone_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_alone_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_alone_7_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_alone_8_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	IDLE_TO_THREATENED_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_group_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_group_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_group_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_alone_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_alone_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_alone_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_alone_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_alone_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_alone_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_alone_7_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_alone_8_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	IDLE_TO_ALERT_HEARD = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_heard_alone_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_heard_alone_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_heard_alone_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_heard_alone_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_heard_alone_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_heard_alone_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	IDLE_TO_ALERT_HEARD_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_heard_group_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_heard_group_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_heard_group_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_heard_alone_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_heard_alone_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_heard_alone_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_heard_alone_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_heard_alone_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_heard_alone_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	IDLE_TO_ALERT_SEEN = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_seen_alone_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_seen_alone_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_seen_alone_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_seen_alone_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_seen_alone_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	IDLE_TO_ALERT_SEEN_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_seen_group_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_seen_group_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_seen_group_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_seen_alone_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_seen_alone_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_seen_alone_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_seen_alone_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_to_alert_seen_alone_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	RANDOM_IDLE_SOUND = {
				-- {
				-- PROBABILITY = 500,
				-- soundFile = "Languages/voicepacks/VoiceA/idle_alone_chuckle_1.wav",
				-- Volume = 255,
				-- min = 7.1,
				-- max = 160.1,
				-- sound_unscalable = 0,
				--},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_alone_cough_1.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_alone_sneeze_1.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_alone_sniffle_1.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_alone_spit_1.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_alone_throatclear_1.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_alone_hum_1.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_alone_hum_2.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_alone_hum_3.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_alone_hum_4.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_alone_hum_5.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_alone_song_1.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_alone_song_2.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_alone_song_3.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_alone_song_4.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_alone_song_5.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_alone_whistle_1.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_alone_whistle_2.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_alone_whistle_3.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_alone_whistle_4.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/idle_alone_whistle_5.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	FRIEND_DEATH = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/mandown_alone_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{-- Иногда "не в тему" это "Что здесь произошло?", скорее подходит, если труп виден визуально.
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/mandown_alone_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/mandown_alone_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	FRIEND_DEATH_GROUP = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/mandown_group_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/mandown_group_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/mandown_group_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/mandown_group_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/mandown_alone_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{-- Иногда "не в тему" это "Что здесь произошло?", скорее подходит, если труп виден визуально.
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/mandown_alone_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/mandown_alone_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	GETTING_SHOT_AT = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_7_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_8_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_9_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_10_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_11_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_12_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_15_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_18_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_19_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_20_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	GETTING_SHOT_AT_GROUP = {
				--??
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_group_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_group_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_group_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_group_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_group_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_group_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_group_7_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_group_8_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_group_9_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_7_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_8_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_9_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_10_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_11_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_12_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_15_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_18_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_19_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/receive_fire_alone_20_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	GET_REINFORCEMENTS = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/reinforce_go_get_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/reinforce_go_get_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/reinforce_go_get_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/reinforce_go_get_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/reinforce_go_get_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	CALL_REINFORCEMENTS = {
				--??
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/reinforce_talk_to_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/reinforce_talk_to_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/reinforce_talk_to_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/reinforce_talk_to_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/reinforce_talk_to_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	GET_IN_VEHICLE = {
				--??
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/vehicle_in_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/vehicle_in_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/vehicle_in_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/vehicle_in_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/vehicle_in_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/vehicle_in_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/vehicle_in_7_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/vehicle_in_8_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},
	-- Тихое обращение к врагу. П-с-с. Ты. Эй. Э-э-э. Эй ты.
	AI_AGGRESSIVE_ATTENTION = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/yell_attention_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/yell_attention_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/yell_attention_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/yell_attention_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/yell_attention_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},
	-- Когда больно от огня. Иногда походит на испуг.
	AI_AGGRESSIVE_FEAR = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/yell_fear_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/yell_fear_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/yell_fear_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/yell_fear_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/yell_fear_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/yell_fear_6.wav", -- Не хватает фонем.
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/yell_fear_7.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/yell_fear_8.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},
	-- Яху-у-у-у-у.
	AI_AGGRESSIVE_MACHO = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/yell_macho_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/yell_macho_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/yell_macho_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/yell_macho_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/yell_macho_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/yell_macho_6.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/yell_macho_7.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/yell_macho_8.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	GET_WEAPON = {
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/get_weapon_1.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/get_weapon_2.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/get_weapon_3.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/get_weapon_4.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/get_weapon_5.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/get_weapon_6.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	VEHICLE_SIGHTING_PLAYER = {
				--?? should be both for helicopter and boat (BOAT/HELICOPTER SIGHTING PLAYER)
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/helicopter_sight_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/helicopter_sight_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/helicopter_sight_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/helicopter_sight_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/helicopter_sight_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/helicopter_sight_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/helicopter_sight_7_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/helicopter_sight_8_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	SEARCHING_GENERIC = {
				--??
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/searching_generic_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/searching_generic_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/searching_generic_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/searching_generic_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/searching_generic_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/searching_generic_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/searching_generic_7_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	SEARCHING_GENERIC_X = {
				--??
				-- {
				-- PROBABILITY = 500,
				-- soundFile = "Languages/voicepacks/VoiceA/searching_generic_1_VoiceA.wav",
				-- Volume = 255,
				-- min = 7.1,
				-- max = 160.1,
				-- sound_unscalable = 0,
				--},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/searching_generic_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				-- {
				-- PROBABILITY = 500,
				-- soundFile = "Languages/voicepacks/VoiceA/searching_generic_3_VoiceA.wav",
				-- Volume = 255,
				-- min = 7.1,
				-- max = 160.1,
				-- sound_unscalable = 0,
				--},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/searching_generic_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				-- {
				-- PROBABILITY = 500,
				-- soundFile = "Languages/voicepacks/VoiceA/searching_generic_5_VoiceA.wav",
				-- Volume = 255,
				-- min = 7.1,
				-- max = 160.1,
				-- sound_unscalable = 0,
				--},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/searching_generic_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/searching_generic_7_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	SEARCHING_MUTANTS = {
				--??
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/searching_mutants_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/searching_mutants_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/searching_mutants_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/searching_mutants_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/searching_mutants_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/searching_mutants_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},

	--filippo: this readability signal is not yet used by the AI
	SEARCHING_PLAYER = {
				--??
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/searching_player_1_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/searching_player_2_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/searching_player_3_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/searching_player_4_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/searching_player_5_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceA/searching_player_6_VoiceA.wav",
				Volume = 255,
				min = 7.1,
				max = 160.1,
				sound_unscalable = 0,
				},
			},
}