-- TEMPLATE
-- DO NOT MODIFY THIS TEMPLATE
--
-- This template has all the readability signals currently in use.  
-- Change the <Template> string to the pack name
-- 
-- To switch between alternate sound responses add a new set of 
-- bracketed parameters, making sure there is a comma after the bracket eg,
--				{
--				PROBABILITY = 500,
--				soundFile = "SOUNDS/<full path to wav file>",
--				Volume = 255,
--				min = 12,
--				max = 300,
--				sound_unscalable = 1,
--				},
-- Probability determines how often a wave is played in response to the signal
-- To allow for possibility of no sound in response to a signal, sounds should sum
-- to less than 1000. eg. if you dont want sound to be played every single time 
-- player receives an order might have total PROBABILITY for all sounds = 500.
--------------------------------------------------
--    Created By: <your_name>
--   Description: <short_description>
--------------------------	
SOUNDPACK.voiceB = {
	
	ORDER_RECEIVED = {
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/VoiceB/affirmative_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/VoiceB/affirmative_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/VoiceB/affirmative_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/VoiceB/affirmative_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/VoiceB/affirmative_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/VoiceB/affirmative_6_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/VoiceB/affirmative_7_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/VoiceB/affirmative_8_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/VoiceB/affirmative_9_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 100,
				soundFile = "Languages/voicepacks/VoiceB/affirmative_10_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	CALL_ALARM = {
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/alarm_alone_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/alarm_alone_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/alarm_alone_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/alarm_alone_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/alarm_alone_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	CALL_ALARM_GROUP = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/VoiceB/alarm_group_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/VoiceB/alarm_group_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/VoiceB/alarm_group_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	FIRST_HOSTILE_CONTACT = {
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_combat_alone_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_combat_alone_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_combat_alone_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_combat_alone_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				NOMUTANT = 1,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_combat_alone_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_combat_alone_6_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_combat_alone_7_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_combat_alone_8_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_combat_alone_9_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_combat_alone_10_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_combat_alone_11_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_combat_alone_12_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_combat_alone_13_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_combat_alone_14_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_combat_alone_15_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_combat_alone_16_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	FIRST_HOSTILE_CONTACT_GROUP = {
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_combat_group_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_combat_group_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_combat_group_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_combat_group_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_combat_group_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_combat_group_6_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				NOMUTANT=1,
				},
			},
			
	INTERESTED_TO_IDLE = {
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_idle_alone_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_idle_alone_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_idle_alone_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_idle_alone_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_idle_alone_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_idle_alone_6_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_idle_alone_7_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_idle_alone_8_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_idle_alone_9_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_idle_alone_10_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_idle_alone_11_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_idle_alone_12_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_idle_alone_13_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_idle_alone_14_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_idle_alone_15_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_idle_alone_16_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	INTERESTED_TO_IDLE_GROUP = {
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_idle_group_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_idle_group_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_idle_group_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_idle_group_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/alert_to_idle_group_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	THREATEN = {
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				NOMUTANT = 1,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_6_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_7_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_8_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_9_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_10_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_11_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_12_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_13_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_14_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_15_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_16_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_17_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_18_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_19_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_20_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_21_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_22_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_23_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_24_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_25_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_26_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_27_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_28_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_29_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_30_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_31_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_32_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_33_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_34_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_35_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_36_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_37_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_38_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_39_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_40_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_41_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_42_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_43_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_44_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 22,
				soundFile = "Languages/voicepacks/VoiceB/combat_alone_45_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	THREATEN_GROUP = {
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/VoiceB/combat_group_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/VoiceB/combat_group_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/VoiceB/combat_group_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/VoiceB/combat_group_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/VoiceB/combat_group_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/VoiceB/combat_group_6_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/VoiceB/combat_group_7_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/VoiceB/combat_group_8_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/VoiceB/combat_group_9_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/VoiceB/combat_group_10_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/VoiceB/combat_group_11_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/VoiceB/combat_group_12_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/VoiceB/combat_group_13_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/VoiceB/combat_group_14_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/VoiceB/combat_group_15_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/VoiceB/combat_group_16_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/VoiceB/combat_group_17_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/VoiceB/combat_group_18_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/VoiceB/combat_group_19_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 50,
				soundFile = "Languages/voicepacks/VoiceB/combat_group_20_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	ENEMY_TARGET_LOST = {
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/combat_to_alert_alone_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/combat_to_alert_alone_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/combat_to_alert_alone_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/combat_to_alert_alone_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/combat_to_alert_alone_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/combat_to_alert_alone_6_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/combat_to_alert_alone_7_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/combat_to_alert_alone_8_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/combat_to_alert_alone_9_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/combat_to_alert_alone_10_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/combat_to_alert_alone_11_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/combat_to_alert_alone_12_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/combat_to_alert_alone_13_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/combat_to_alert_alone_14_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/combat_to_alert_alone_15_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 62,
				soundFile = "Languages/voicepacks/VoiceB/combat_to_alert_alone_16_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	ENEMY_TARGET_LOST_GROUP = {
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/combat_to_alert_group_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/combat_to_alert_group_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/combat_to_alert_group_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/combat_to_alert_group_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/combat_to_alert_group_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/combat_to_alert_group_6_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	LO_LEFT_ADVANCE = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/VoiceB/comm_advance_left_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/VoiceB/comm_advance_left_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/VoiceB/comm_advance_left_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	LO_RIGHT_ADVANCE = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/VoiceB/comm_advance_right_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/VoiceB/comm_advance_right_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/VoiceB/comm_advance_right_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	LO_SPLIT_LEFT = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/VoiceB/comm_flank_left_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/VoiceB/comm_flank_left_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/VoiceB/comm_flank_left_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	LO_SPLIT_RIGHT = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/VoiceB/comm_flank_right_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/VoiceB/comm_flank_right_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/VoiceB/comm_flank_right_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	RETREATING_NOW = {
				--??
				--there are the wavs, but not the readability signal.
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceB/comm_retreat_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceB/comm_retreat_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
		
	--filippo: this readability signal is not yet used by the AI
	LO_RUSH = {
				--??
				--there are the wavs, but not the readability signal.
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceB/comm_rush_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 500,
				soundFile = "Languages/voicepacks/VoiceB/comm_rush_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	PROVIDING_COVER = {
				--??
				--there are the wavs, but not the readability signal.
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/comm_suppress_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/comm_suppress_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/comm_suppress_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/comm_suppress_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/comm_suppress_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/comm_suppress_6_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	ROOM_DARK = {
				--??
				--there are the wavs, but not the readability signal.
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/darkness_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/darkness_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/darkness_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/darkness_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/darkness_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
						
	FLASHBANG_GRENADE_EFFECT = {
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/flashbang_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/flashbang_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/flashbang_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/flashbang_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/flashbang_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/flashbang_6_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--receiving and throwing grenade?
	FIRE_IN_THE_HOLE = {
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/VoiceB/grenade_1_alone_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/VoiceB/grenade_2_alone_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/VoiceB/grenade_3_alone_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/VoiceB/grenade_4_alone_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/VoiceB/grenade_5_alone_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/VoiceB/grenade_1_group_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/VoiceB/grenade_2_group_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/VoiceB/grenade_3_group_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/VoiceB/grenade_4_group_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	IDLE_TO_THREATENED = {
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_alone_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_alone_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_alone_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_alone_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_alone_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_alone_6_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_alone_7_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_alone_8_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	IDLE_TO_THREATENED_GROUP = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_group_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_group_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_group_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	IDLE_TO_INTERESTED = {
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_heard_alone_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_heard_alone_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_heard_alone_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_heard_alone_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_heard_alone_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_heard_alone_6_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_seen_alone_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_seen_alone_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_seen_alone_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_seen_alone_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 90,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_seen_alone_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	IDLE_TO_INTERESTED_GROUP = {
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_heard_group_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_heard_group_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_heard_group_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_seen_group_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_seen_group_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/idle_to_alert_seen_group_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	
	
	FRIEND_DEATH = {
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/VoiceB/mandown_alone_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/VoiceB/mandown_alone_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "Languages/voicepacks/VoiceB/mandown_alone_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	FRIEND_DEATH_GROUP = {
				{
				PROBABILITY = 250,
				soundFile = "Languages/voicepacks/VoiceB/mandown_group_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Languages/voicepacks/VoiceB/mandown_group_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Languages/voicepacks/VoiceB/mandown_group_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Languages/voicepacks/VoiceB/mandown_group_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI			
	GETTING_SHOT_AT = {
				--??
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_alone_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_alone_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_alone_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_alone_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_alone_6_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_alone_7_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_alone_8_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_alone_9_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_alone_10_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_alone_11_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_alone_12_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_alone_15_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_alone_18_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_alone_19_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_alone_20_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	GETTING_SHOT_AT_GROUP = {
				--??
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_group_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_group_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_group_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_group_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_group_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_group_6_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_group_7_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_group_8_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Languages/voicepacks/VoiceB/receive_fire_group_9_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	GET_REINFORCEMENTS = {
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/reinforce_go_get_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/reinforce_go_get_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/reinforce_go_get_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/reinforce_go_get_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/reinforce_go_get_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	CALL_REINFORCEMENTS = {
				--??
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/reinforce_talk_to_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/reinforce_talk_to_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/reinforce_talk_to_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/reinforce_talk_to_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Languages/voicepacks/VoiceB/reinforce_talk_to_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	GET_IN_VEHICLE = {
				--??
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/vehicle_in_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/vehicle_in_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/vehicle_in_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/vehicle_in_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/vehicle_in_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/vehicle_in_6_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/vehicle_in_7_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/vehicle_in_8_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	AI_AGGRESSIVE = {
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/yell_attention_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/yell_attention_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/yell_attention_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/yell_attention_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/yell_attention_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				
				--
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/yell_fear_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/yell_fear_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/yell_fear_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/yell_fear_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/yell_fear_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				
				--
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/yell_macho_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/yell_macho_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/yell_macho_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/yell_macho_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 66,
				soundFile = "Languages/voicepacks/VoiceB/yell_macho_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
		
	--filippo: this readability signal is not yet used by the AI
	GET_WEAPON = {
				--??
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/get_weapon_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/get_weapon_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/get_weapon_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/get_weapon_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/get_weapon_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/get_weapon_6_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	VEHICLE_SIGHTING_PLAYER = {
				--?? should be both for helicopter and boat (BOAT/HELICOPTER SIGHTING PLAYER)
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/helicopter_sight_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/helicopter_sight_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/helicopter_sight_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/helicopter_sight_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/helicopter_sight_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/helicopter_sight_6_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/helicopter_sight_7_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Languages/voicepacks/VoiceB/helicopter_sight_8_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	SEARCHING_GENERIC = {
				--??
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/VoiceB/searching_generic_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/VoiceB/searching_generic_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/VoiceB/searching_generic_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/VoiceB/searching_generic_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/VoiceB/searching_generic_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/VoiceB/searching_generic_6_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 142,
				soundFile = "Languages/voicepacks/VoiceB/searching_generic_7_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	SEARCHING_MUTANTS = {
				--??
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/searching_mutants_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/searching_mutants_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/searching_mutants_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/searching_mutants_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/searching_mutants_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/searching_mutants_6_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	--filippo: this readability signal is not yet used by the AI
	SEARCHING_PLAYER = {
				--??
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/searching_player_1_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/searching_player_2_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/searching_player_3_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/searching_player_4_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/searching_player_5_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Languages/voicepacks/VoiceB/searching_player_6_VoiceB.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
}